# Code generated by tfpfgen from blueprints/thousandeyes
# (sha256:0705a06d171a00d2bf9756d028fa63d1589968e3dae11ee9272c1c4039c2d00f). DO NOT EDIT.

# The widest configuration the evidence supports: every writable attribute with a derivable
# value, chosen by the same derivation the rehearsal probe sends to the live API.
#
# Regenerated and policed, deliberately. This file used to be a hand-owned scaffold, and
# hand edits are how its values drifted from the generated assertions -- the checks derive
# from the blueprint, so the blueprint is where a value is corrected: an accFixture hint for
# something only a human knows, recorded behaviour for everything the probe observed. What
# could not be derived is listed inside the block, each with the reason.

resource "thousandeyes_user" "test" {
  # Where a value came from.
  #
  # account_group_roles: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # email: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # login_account_group_id: curated in the blueprint's accFixture; the generator cannot derive
  # it
  #
  # Not filled in, because no correct value could be derived. Each of these is optional, so this
  # configuration is valid as it stands -- but it is testing less than it could.
  #
  # all_account_group_role_ids: curated omission; individually valid, refused in combination --
  # see the attribute's documentation
  account_group_roles    = [{ account_group_id = "281474976742769", role_ids = ["281474976759598"] }]
  email                  = "dafydd.watkins+tfacc@deploymenttheory.com"
  login_account_group_id = "281474976742769"
  name                   = "tfacc-name"
}
