// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Endpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter struct {
	Endpoint_Test_Results_API_EndpointResultRequestFilter
	// Web site base domain visited during the session.
	typeEscaped []Endpoint_Test_Results_API_NetworkTopologyType
}

// NewEndpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter instantiates a new Endpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter and sets the default values.
func NewEndpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter() *Endpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter {
	m := &Endpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter{
		Endpoint_Test_Results_API_EndpointResultRequestFilter: *NewEndpoint_Test_Results_API_EndpointResultRequestFilter(),
	}
	return m
}

// CreateEndpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilterFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEndpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilterFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewEndpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter(), nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Endpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.Endpoint_Test_Results_API_EndpointResultRequestFilter.GetFieldDeserializers()
	res["type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfEnumValues(ParseEndpoint_Test_Results_API_NetworkTopologyType)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Endpoint_Test_Results_API_NetworkTopologyType, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*Endpoint_Test_Results_API_NetworkTopologyType)
				}
			}
			m.SetTypeEscaped(res)
		}
		return nil
	}
	return res
}

// GetTypeEscaped gets the type property value. Web site base domain visited during the session.
// returns a []Endpoint_Test_Results_API_NetworkTopologyType when successful
func (m *Endpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter) GetTypeEscaped() []Endpoint_Test_Results_API_NetworkTopologyType {
	return m.typeEscaped
}

// Serialize serializes information the current object
func (m *Endpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.Endpoint_Test_Results_API_EndpointResultRequestFilter.Serialize(writer)
	if err != nil {
		return err
	}
	if m.GetTypeEscaped() != nil {
		err = writer.WriteCollectionOfStringValues("type", SerializeEndpoint_Test_Results_API_NetworkTopologyType(m.GetTypeEscaped()))
		if err != nil {
			return err
		}
	}
	return nil
}

// SetTypeEscaped sets the type property value. Web site base domain visited during the session.
func (m *Endpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilter) SetTypeEscaped(value []Endpoint_Test_Results_API_NetworkTopologyType) {
	m.typeEscaped = value
}

type Endpoint_Test_Results_API_EndpointNetworkTopologyResultRequestFilterable interface {
	Endpoint_Test_Results_API_EndpointResultRequestFilterable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetTypeEscaped() []Endpoint_Test_Results_API_NetworkTopologyType
	SetTypeEscaped(value []Endpoint_Test_Results_API_NetworkTopologyType)
}
