// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Administrative_API_ErrorDetail struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Code for the agent error.
	code *Administrative_API_ErrorDetailCode
	// Description for the agent error.
	description *string
}

// NewAdministrative_API_ErrorDetail instantiates a new Administrative_API_ErrorDetail and sets the default values.
func NewAdministrative_API_ErrorDetail() *Administrative_API_ErrorDetail {
	m := &Administrative_API_ErrorDetail{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateAdministrative_API_ErrorDetailFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdministrative_API_ErrorDetailFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewAdministrative_API_ErrorDetail(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Administrative_API_ErrorDetail) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCode gets the code property value. Code for the agent error.
// returns a *Administrative_API_ErrorDetailCode when successful
func (m *Administrative_API_ErrorDetail) GetCode() *Administrative_API_ErrorDetailCode {
	return m.code
}

// GetDescription gets the description property value. Description for the agent error.
// returns a *string when successful
func (m *Administrative_API_ErrorDetail) GetDescription() *string {
	return m.description
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Administrative_API_ErrorDetail) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["code"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseAdministrative_API_ErrorDetailCode)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCode(val.(*Administrative_API_ErrorDetailCode))
		}
		return nil
	}
	res["description"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDescription(val)
		}
		return nil
	}
	return res
}

// Serialize serializes information the current object
func (m *Administrative_API_ErrorDetail) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Administrative_API_ErrorDetail) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCode sets the code property value. Code for the agent error.
func (m *Administrative_API_ErrorDetail) SetCode(value *Administrative_API_ErrorDetailCode) {
	m.code = value
}

// SetDescription sets the description property value. Description for the agent error.
func (m *Administrative_API_ErrorDetail) SetDescription(value *string) {
	m.description = value
}

type Administrative_API_ErrorDetailable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCode() *Administrative_API_ErrorDetailCode
	GetDescription() *string
	SetCode(value *Administrative_API_ErrorDetailCode)
	SetDescription(value *string)
}
