// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"

	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Administrative_API_ClusterMember struct {
	Administrative_API_AgentBase
	// State of the agent.
	agentState *Administrative_API_EnterpriseAgentState
	// If an enterprise agent or a cluster member presents at least one error, the errors will be shown as an array of entries in the errorDetails field (Enterprise Agents and Enterprise Cluster members only)
	errorDetails []Administrative_API_ErrorDetailable
	// UTC last seen date (ISO date-time format).
	lastSeen *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// Unique ID of the cluster member
	memberId *string
	// Name of the cluster member
	name *string
	// Serial number of an enterprise agent or cluster member device. This field is not available for Cloud Agents.
	serialNumber *string
	// Test target IP address.
	targetForTests *string
	// Shows overall utilization percentage (online Enterprise Agents and Enterprise Clusters only).
	utilization *int32
}

// NewAdministrative_API_ClusterMember instantiates a new Administrative_API_ClusterMember and sets the default values.
func NewAdministrative_API_ClusterMember() *Administrative_API_ClusterMember {
	m := &Administrative_API_ClusterMember{
		Administrative_API_AgentBase: *NewAdministrative_API_AgentBase(),
	}
	return m
}

// CreateAdministrative_API_ClusterMemberFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdministrative_API_ClusterMemberFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewAdministrative_API_ClusterMember(), nil
}

// GetAgentState gets the agentState property value. State of the agent.
// returns a *Administrative_API_EnterpriseAgentState when successful
func (m *Administrative_API_ClusterMember) GetAgentState() *Administrative_API_EnterpriseAgentState {
	return m.agentState
}

// GetErrorDetails gets the errorDetails property value. If an enterprise agent or a cluster member presents at least one error, the errors will be shown as an array of entries in the errorDetails field (Enterprise Agents and Enterprise Cluster members only)
// returns a []Administrative_API_ErrorDetailable when successful
func (m *Administrative_API_ClusterMember) GetErrorDetails() []Administrative_API_ErrorDetailable {
	return m.errorDetails
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Administrative_API_ClusterMember) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.Administrative_API_AgentBase.GetFieldDeserializers()
	res["agentState"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseAdministrative_API_EnterpriseAgentState)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAgentState(val.(*Administrative_API_EnterpriseAgentState))
		}
		return nil
	}
	res["errorDetails"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateAdministrative_API_ErrorDetailFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Administrative_API_ErrorDetailable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Administrative_API_ErrorDetailable)
				}
			}
			m.SetErrorDetails(res)
		}
		return nil
	}
	res["lastSeen"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLastSeen(val)
		}
		return nil
	}
	res["memberId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMemberId(val)
		}
		return nil
	}
	res["name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetName(val)
		}
		return nil
	}
	res["serialNumber"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSerialNumber(val)
		}
		return nil
	}
	res["targetForTests"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTargetForTests(val)
		}
		return nil
	}
	res["utilization"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUtilization(val)
		}
		return nil
	}
	return res
}

// GetLastSeen gets the lastSeen property value. UTC last seen date (ISO date-time format).
// returns a *Time when successful
func (m *Administrative_API_ClusterMember) GetLastSeen() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.lastSeen
}

// GetMemberId gets the memberId property value. Unique ID of the cluster member
// returns a *string when successful
func (m *Administrative_API_ClusterMember) GetMemberId() *string {
	return m.memberId
}

// GetName gets the name property value. Name of the cluster member
// returns a *string when successful
func (m *Administrative_API_ClusterMember) GetName() *string {
	return m.name
}

// GetSerialNumber gets the serialNumber property value. Serial number of an enterprise agent or cluster member device. This field is not available for Cloud Agents.
// returns a *string when successful
func (m *Administrative_API_ClusterMember) GetSerialNumber() *string {
	return m.serialNumber
}

// GetTargetForTests gets the targetForTests property value. Test target IP address.
// returns a *string when successful
func (m *Administrative_API_ClusterMember) GetTargetForTests() *string {
	return m.targetForTests
}

// GetUtilization gets the utilization property value. Shows overall utilization percentage (online Enterprise Agents and Enterprise Clusters only).
// returns a *int32 when successful
func (m *Administrative_API_ClusterMember) GetUtilization() *int32 {
	return m.utilization
}

// Serialize serializes information the current object
func (m *Administrative_API_ClusterMember) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.Administrative_API_AgentBase.Serialize(writer)
	if err != nil {
		return err
	}
	{
		err = writer.WriteStringValue("targetForTests", m.GetTargetForTests())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAgentState sets the agentState property value. State of the agent.
func (m *Administrative_API_ClusterMember) SetAgentState(value *Administrative_API_EnterpriseAgentState) {
	m.agentState = value
}

// SetErrorDetails sets the errorDetails property value. If an enterprise agent or a cluster member presents at least one error, the errors will be shown as an array of entries in the errorDetails field (Enterprise Agents and Enterprise Cluster members only)
func (m *Administrative_API_ClusterMember) SetErrorDetails(value []Administrative_API_ErrorDetailable) {
	m.errorDetails = value
}

// SetLastSeen sets the lastSeen property value. UTC last seen date (ISO date-time format).
func (m *Administrative_API_ClusterMember) SetLastSeen(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.lastSeen = value
}

// SetMemberId sets the memberId property value. Unique ID of the cluster member
func (m *Administrative_API_ClusterMember) SetMemberId(value *string) {
	m.memberId = value
}

// SetName sets the name property value. Name of the cluster member
func (m *Administrative_API_ClusterMember) SetName(value *string) {
	m.name = value
}

// SetSerialNumber sets the serialNumber property value. Serial number of an enterprise agent or cluster member device. This field is not available for Cloud Agents.
func (m *Administrative_API_ClusterMember) SetSerialNumber(value *string) {
	m.serialNumber = value
}

// SetTargetForTests sets the targetForTests property value. Test target IP address.
func (m *Administrative_API_ClusterMember) SetTargetForTests(value *string) {
	m.targetForTests = value
}

// SetUtilization sets the utilization property value. Shows overall utilization percentage (online Enterprise Agents and Enterprise Clusters only).
func (m *Administrative_API_ClusterMember) SetUtilization(value *int32) {
	m.utilization = value
}

type Administrative_API_ClusterMemberable interface {
	Administrative_API_AgentBaseable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAgentState() *Administrative_API_EnterpriseAgentState
	GetErrorDetails() []Administrative_API_ErrorDetailable
	GetLastSeen() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetMemberId() *string
	GetName() *string
	GetSerialNumber() *string
	GetTargetForTests() *string
	GetUtilization() *int32
	SetAgentState(value *Administrative_API_EnterpriseAgentState)
	SetErrorDetails(value []Administrative_API_ErrorDetailable)
	SetLastSeen(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetMemberId(value *string)
	SetName(value *string)
	SetSerialNumber(value *string)
	SetTargetForTests(value *string)
	SetUtilization(value *int32)
}
