// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// State of the agent.
type Agents_API_EnterpriseAgentState int

const (
	ONLINE_AGENTS_API_ENTERPRISEAGENTSTATE Agents_API_EnterpriseAgentState = iota
	OFFLINE_AGENTS_API_ENTERPRISEAGENTSTATE
	DISABLED_AGENTS_API_ENTERPRISEAGENTSTATE
)

func (i Agents_API_EnterpriseAgentState) String() string {
	return []string{"online", "offline", "disabled"}[i]
}

func ParseAgents_API_EnterpriseAgentState(v string) (any, error) {
	result := ONLINE_AGENTS_API_ENTERPRISEAGENTSTATE
	switch v {
	case "online":
		result = ONLINE_AGENTS_API_ENTERPRISEAGENTSTATE
	case "offline":
		result = OFFLINE_AGENTS_API_ENTERPRISEAGENTSTATE
	case "disabled":
		result = DISABLED_AGENTS_API_ENTERPRISEAGENTSTATE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeAgents_API_EnterpriseAgentState(values []Agents_API_EnterpriseAgentState) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Agents_API_EnterpriseAgentState) isMultiValue() bool {
	return false
}
