// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type Agents_API_AgentListExpand int

const (
	CLUSTERMEMBER_AGENTS_API_AGENTLISTEXPAND Agents_API_AgentListExpand = iota
	TEST_AGENTS_API_AGENTLISTEXPAND
	TESTIDS_AGENTS_API_AGENTLISTEXPAND
)

func (i Agents_API_AgentListExpand) String() string {
	return []string{"cluster-member", "test", "test-ids"}[i]
}

func ParseAgents_API_AgentListExpand(v string) (any, error) {
	result := CLUSTERMEMBER_AGENTS_API_AGENTLISTEXPAND
	switch v {
	case "cluster-member":
		result = CLUSTERMEMBER_AGENTS_API_AGENTLISTEXPAND
	case "test":
		result = TEST_AGENTS_API_AGENTLISTEXPAND
	case "test-ids":
		result = TESTIDS_AGENTS_API_AGENTLISTEXPAND
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeAgents_API_AgentListExpand(values []Agents_API_AgentListExpand) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Agents_API_AgentListExpand) isMultiValue() bool {
	return false
}
