// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// The severity of the alert.
// Deprecated:
type Alerts_API_Alert_severity int

const (
	INFO_ALERTS_API_ALERT_SEVERITY Alerts_API_Alert_severity = iota
	MAJOR_ALERTS_API_ALERT_SEVERITY
	MINOR_ALERTS_API_ALERT_SEVERITY
	CRITICAL_ALERTS_API_ALERT_SEVERITY
	UNKNOWN_ALERTS_API_ALERT_SEVERITY
)

func (i Alerts_API_Alert_severity) String() string {
	return []string{"INFO", "MAJOR", "MINOR", "CRITICAL", "UNKNOWN"}[i]
}

func ParseAlerts_API_Alert_severity(v string) (any, error) {
	result := INFO_ALERTS_API_ALERT_SEVERITY
	switch v {
	case "INFO":
		result = INFO_ALERTS_API_ALERT_SEVERITY
	case "MAJOR":
		result = MAJOR_ALERTS_API_ALERT_SEVERITY
	case "MINOR":
		result = MINOR_ALERTS_API_ALERT_SEVERITY
	case "CRITICAL":
		result = CRITICAL_ALERTS_API_ALERT_SEVERITY
	case "UNKNOWN":
		result = UNKNOWN_ALERTS_API_ALERT_SEVERITY
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeAlerts_API_Alert_severity(values []Alerts_API_Alert_severity) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Alerts_API_Alert_severity) isMultiValue() bool {
	return false
}
