// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Alerts_API_NotificationThirdParty webhook notification.
type Alerts_API_NotificationThirdParty struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Integration ID.
	integrationId *string
	// Integration type.
	integrationType *Alerts_API_ThirdPartyIntegrationType
}

// NewAlerts_API_NotificationThirdParty instantiates a new Alerts_API_NotificationThirdParty and sets the default values.
func NewAlerts_API_NotificationThirdParty() *Alerts_API_NotificationThirdParty {
	m := &Alerts_API_NotificationThirdParty{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateAlerts_API_NotificationThirdPartyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAlerts_API_NotificationThirdPartyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewAlerts_API_NotificationThirdParty(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Alerts_API_NotificationThirdParty) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Alerts_API_NotificationThirdParty) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["integrationId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIntegrationId(val)
		}
		return nil
	}
	res["integrationType"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseAlerts_API_ThirdPartyIntegrationType)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIntegrationType(val.(*Alerts_API_ThirdPartyIntegrationType))
		}
		return nil
	}
	return res
}

// GetIntegrationId gets the integrationId property value. Integration ID.
// returns a *string when successful
func (m *Alerts_API_NotificationThirdParty) GetIntegrationId() *string {
	return m.integrationId
}

// GetIntegrationType gets the integrationType property value. Integration type.
// returns a *Alerts_API_ThirdPartyIntegrationType when successful
func (m *Alerts_API_NotificationThirdParty) GetIntegrationType() *Alerts_API_ThirdPartyIntegrationType {
	return m.integrationType
}

// Serialize serializes information the current object
func (m *Alerts_API_NotificationThirdParty) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("integrationId", m.GetIntegrationId())
		if err != nil {
			return err
		}
	}
	if m.GetIntegrationType() != nil {
		cast := (*m.GetIntegrationType()).String()
		err := writer.WriteStringValue("integrationType", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Alerts_API_NotificationThirdParty) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetIntegrationId sets the integrationId property value. Integration ID.
func (m *Alerts_API_NotificationThirdParty) SetIntegrationId(value *string) {
	m.integrationId = value
}

// SetIntegrationType sets the integrationType property value. Integration type.
func (m *Alerts_API_NotificationThirdParty) SetIntegrationType(value *Alerts_API_ThirdPartyIntegrationType) {
	m.integrationType = value
}

type Alerts_API_NotificationThirdPartyable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetIntegrationId() *string
	GetIntegrationType() *Alerts_API_ThirdPartyIntegrationType
	SetIntegrationId(value *string)
	SetIntegrationType(value *Alerts_API_ThirdPartyIntegrationType)
}
