// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// Integration type.
type Alerts_API_CustomWebhookIntegrationType int

const (
	CUSTOMWEBHOOK_ALERTS_API_CUSTOMWEBHOOKINTEGRATIONTYPE Alerts_API_CustomWebhookIntegrationType = iota
)

func (i Alerts_API_CustomWebhookIntegrationType) String() string {
	return []string{"custom-webhook"}[i]
}

func ParseAlerts_API_CustomWebhookIntegrationType(v string) (any, error) {
	result := CUSTOMWEBHOOK_ALERTS_API_CUSTOMWEBHOOKINTEGRATIONTYPE
	switch v {
	case "custom-webhook":
		result = CUSTOMWEBHOOK_ALERTS_API_CUSTOMWEBHOOKINTEGRATIONTYPE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeAlerts_API_CustomWebhookIntegrationType(values []Alerts_API_CustomWebhookIntegrationType) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Alerts_API_CustomWebhookIntegrationType) isMultiValue() bool {
	return false
}
