// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// Action applied when a subscriptions policy rule matches.
type Cloud_Insights_Integrations_API_SubscriptionsPolicyRuleAction int

const (
	INCLUDE_CLOUD_INSIGHTS_INTEGRATIONS_API_SUBSCRIPTIONSPOLICYRULEACTION Cloud_Insights_Integrations_API_SubscriptionsPolicyRuleAction = iota
	EXCLUDE_CLOUD_INSIGHTS_INTEGRATIONS_API_SUBSCRIPTIONSPOLICYRULEACTION
)

func (i Cloud_Insights_Integrations_API_SubscriptionsPolicyRuleAction) String() string {
	return []string{"include", "exclude"}[i]
}

func ParseCloud_Insights_Integrations_API_SubscriptionsPolicyRuleAction(v string) (any, error) {
	result := INCLUDE_CLOUD_INSIGHTS_INTEGRATIONS_API_SUBSCRIPTIONSPOLICYRULEACTION
	switch v {
	case "include":
		result = INCLUDE_CLOUD_INSIGHTS_INTEGRATIONS_API_SUBSCRIPTIONSPOLICYRULEACTION
	case "exclude":
		result = EXCLUDE_CLOUD_INSIGHTS_INTEGRATIONS_API_SUBSCRIPTIONSPOLICYRULEACTION
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeCloud_Insights_Integrations_API_SubscriptionsPolicyRuleAction(values []Cloud_Insights_Integrations_API_SubscriptionsPolicyRuleAction) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Cloud_Insights_Integrations_API_SubscriptionsPolicyRuleAction) isMultiValue() bool {
	return false
}
