// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"

	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Dashboards_API_Dashboard dashboard upon which this dashboard snapshot is based upon.
type Dashboards_API_Dashboard struct {
	Dashboards_API_DashboardGlobalFilterId
	// Identifier for the account group associated with a dashboard.
	aid *string
	// Identifier for the user that created a dashboard.
	createdBy *string
	// Identifier of a dashboard.
	dashboardId *string
	// The defaultTimespan property
	defaultTimespan Dashboards_API_DefaultTimespanable
	// A text description of the dashboard's purpose and functionality. This information assists users in understanding the dashboard but isn't displayed when viewing a dashboard.
	description *string
	// Indicates if a dashboard is built-in. True for built-in dashboards, false for user-created dashboards.
	isBuiltIn *bool
	// Indicates whether this dashboard is the account group's default. True for default, false if not.
	isDefaultForAccount *bool
	// Indicates whether this dashboard is the user's default. True for default, false if not.
	isDefaultForUser *bool
	// When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If set to `false`, the the widget's timespan is used.
	isGlobalOverride *bool
	// True if this dashboard was previously a report.
	isMigratedReport *bool
	// A dashboard can be viewed by other users in the account. If true, only the creator of the dashboard may view it. If false, all users in the same account may view it.
	isPrivate *bool
	// Dashboard layout configuration for arranging widgets.
	layout Dashboards_API_DashboardLayoutable
	// A links object containing the self and the snapshots links.
	links Dashboards_API_DashboardLinksable
	// Identifier for the user that last modified a dashboard.
	modifiedBy *string
	// UTC date/time when a dashboard was last modified (ISO date-time format).
	modifiedDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// Auto-refresh interval for a dashboard. Use `off` to disable auto-refresh.
	refreshRate *Dashboards_API_RefreshRate
	// Title of a dashboard.
	title *string
	// The widgets property
	widgets []Dashboards_API_ApiWidgetable
}

// NewDashboards_API_Dashboard instantiates a new Dashboards_API_Dashboard and sets the default values.
func NewDashboards_API_Dashboard() *Dashboards_API_Dashboard {
	m := &Dashboards_API_Dashboard{
		Dashboards_API_DashboardGlobalFilterId: *NewDashboards_API_DashboardGlobalFilterId(),
	}
	return m
}

// CreateDashboards_API_DashboardFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDashboards_API_DashboardFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDashboards_API_Dashboard(), nil
}

// GetAid gets the aid property value. Identifier for the account group associated with a dashboard.
// returns a *string when successful
func (m *Dashboards_API_Dashboard) GetAid() *string {
	return m.aid
}

// GetCreatedBy gets the createdBy property value. Identifier for the user that created a dashboard.
// returns a *string when successful
func (m *Dashboards_API_Dashboard) GetCreatedBy() *string {
	return m.createdBy
}

// GetDashboardId gets the dashboardId property value. Identifier of a dashboard.
// returns a *string when successful
func (m *Dashboards_API_Dashboard) GetDashboardId() *string {
	return m.dashboardId
}

// GetDefaultTimespan gets the defaultTimespan property value. The defaultTimespan property
// returns a Dashboards_API_DefaultTimespanable when successful
func (m *Dashboards_API_Dashboard) GetDefaultTimespan() Dashboards_API_DefaultTimespanable {
	return m.defaultTimespan
}

// GetDescription gets the description property value. A text description of the dashboard's purpose and functionality. This information assists users in understanding the dashboard but isn't displayed when viewing a dashboard.
// returns a *string when successful
func (m *Dashboards_API_Dashboard) GetDescription() *string {
	return m.description
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Dashboards_API_Dashboard) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.Dashboards_API_DashboardGlobalFilterId.GetFieldDeserializers()
	res["aid"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAid(val)
		}
		return nil
	}
	res["createdBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedBy(val)
		}
		return nil
	}
	res["dashboardId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDashboardId(val)
		}
		return nil
	}
	res["defaultTimespan"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_DefaultTimespanFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDefaultTimespan(val.(Dashboards_API_DefaultTimespanable))
		}
		return nil
	}
	res["description"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDescription(val)
		}
		return nil
	}
	res["isBuiltIn"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsBuiltIn(val)
		}
		return nil
	}
	res["isDefaultForAccount"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsDefaultForAccount(val)
		}
		return nil
	}
	res["isDefaultForUser"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsDefaultForUser(val)
		}
		return nil
	}
	res["isGlobalOverride"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsGlobalOverride(val)
		}
		return nil
	}
	res["isMigratedReport"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsMigratedReport(val)
		}
		return nil
	}
	res["isPrivate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsPrivate(val)
		}
		return nil
	}
	res["layout"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_DashboardLayoutFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLayout(val.(Dashboards_API_DashboardLayoutable))
		}
		return nil
	}
	res["_links"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_DashboardLinksFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLinks(val.(Dashboards_API_DashboardLinksable))
		}
		return nil
	}
	res["modifiedBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedBy(val)
		}
		return nil
	}
	res["modifiedDate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedDate(val)
		}
		return nil
	}
	res["refreshRate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_RefreshRate)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRefreshRate(val.(*Dashboards_API_RefreshRate))
		}
		return nil
	}
	res["title"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTitle(val)
		}
		return nil
	}
	res["widgets"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateDashboards_API_ApiWidgetFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Dashboards_API_ApiWidgetable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Dashboards_API_ApiWidgetable)
				}
			}
			m.SetWidgets(res)
		}
		return nil
	}
	return res
}

// GetIsBuiltIn gets the isBuiltIn property value. Indicates if a dashboard is built-in. True for built-in dashboards, false for user-created dashboards.
// returns a *bool when successful
func (m *Dashboards_API_Dashboard) GetIsBuiltIn() *bool {
	return m.isBuiltIn
}

// GetIsDefaultForAccount gets the isDefaultForAccount property value. Indicates whether this dashboard is the account group's default. True for default, false if not.
// returns a *bool when successful
func (m *Dashboards_API_Dashboard) GetIsDefaultForAccount() *bool {
	return m.isDefaultForAccount
}

// GetIsDefaultForUser gets the isDefaultForUser property value. Indicates whether this dashboard is the user's default. True for default, false if not.
// returns a *bool when successful
func (m *Dashboards_API_Dashboard) GetIsDefaultForUser() *bool {
	return m.isDefaultForUser
}

// GetIsGlobalOverride gets the isGlobalOverride property value. When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If set to `false`, the the widget's timespan is used.
// returns a *bool when successful
func (m *Dashboards_API_Dashboard) GetIsGlobalOverride() *bool {
	return m.isGlobalOverride
}

// GetIsMigratedReport gets the isMigratedReport property value. True if this dashboard was previously a report.
// returns a *bool when successful
func (m *Dashboards_API_Dashboard) GetIsMigratedReport() *bool {
	return m.isMigratedReport
}

// GetIsPrivate gets the isPrivate property value. A dashboard can be viewed by other users in the account. If true, only the creator of the dashboard may view it. If false, all users in the same account may view it.
// returns a *bool when successful
func (m *Dashboards_API_Dashboard) GetIsPrivate() *bool {
	return m.isPrivate
}

// GetLayout gets the layout property value. Dashboard layout configuration for arranging widgets.
// returns a Dashboards_API_DashboardLayoutable when successful
func (m *Dashboards_API_Dashboard) GetLayout() Dashboards_API_DashboardLayoutable {
	return m.layout
}

// GetLinks gets the _links property value. A links object containing the self and the snapshots links.
// returns a Dashboards_API_DashboardLinksable when successful
func (m *Dashboards_API_Dashboard) GetLinks() Dashboards_API_DashboardLinksable {
	return m.links
}

// GetModifiedBy gets the modifiedBy property value. Identifier for the user that last modified a dashboard.
// returns a *string when successful
func (m *Dashboards_API_Dashboard) GetModifiedBy() *string {
	return m.modifiedBy
}

// GetModifiedDate gets the modifiedDate property value. UTC date/time when a dashboard was last modified (ISO date-time format).
// returns a *Time when successful
func (m *Dashboards_API_Dashboard) GetModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.modifiedDate
}

// GetRefreshRate gets the refreshRate property value. Auto-refresh interval for a dashboard. Use `off` to disable auto-refresh.
// returns a *Dashboards_API_RefreshRate when successful
func (m *Dashboards_API_Dashboard) GetRefreshRate() *Dashboards_API_RefreshRate {
	return m.refreshRate
}

// GetTitle gets the title property value. Title of a dashboard.
// returns a *string when successful
func (m *Dashboards_API_Dashboard) GetTitle() *string {
	return m.title
}

// GetWidgets gets the widgets property value. The widgets property
// returns a []Dashboards_API_ApiWidgetable when successful
func (m *Dashboards_API_Dashboard) GetWidgets() []Dashboards_API_ApiWidgetable {
	return m.widgets
}

// Serialize serializes information the current object
func (m *Dashboards_API_Dashboard) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.Dashboards_API_DashboardGlobalFilterId.Serialize(writer)
	if err != nil {
		return err
	}
	{
		err = writer.WriteObjectValue("defaultTimespan", m.GetDefaultTimespan())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("description", m.GetDescription())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteBoolValue("isGlobalOverride", m.GetIsGlobalOverride())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteBoolValue("isPrivate", m.GetIsPrivate())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteObjectValue("layout", m.GetLayout())
		if err != nil {
			return err
		}
	}
	if m.GetRefreshRate() != nil {
		cast := (*m.GetRefreshRate()).String()
		err = writer.WriteStringValue("refreshRate", &cast)
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("title", m.GetTitle())
		if err != nil {
			return err
		}
	}
	if m.GetWidgets() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetWidgets()))
		for i, v := range m.GetWidgets() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err = writer.WriteCollectionOfObjectValues("widgets", cast)
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAid sets the aid property value. Identifier for the account group associated with a dashboard.
func (m *Dashboards_API_Dashboard) SetAid(value *string) {
	m.aid = value
}

// SetCreatedBy sets the createdBy property value. Identifier for the user that created a dashboard.
func (m *Dashboards_API_Dashboard) SetCreatedBy(value *string) {
	m.createdBy = value
}

// SetDashboardId sets the dashboardId property value. Identifier of a dashboard.
func (m *Dashboards_API_Dashboard) SetDashboardId(value *string) {
	m.dashboardId = value
}

// SetDefaultTimespan sets the defaultTimespan property value. The defaultTimespan property
func (m *Dashboards_API_Dashboard) SetDefaultTimespan(value Dashboards_API_DefaultTimespanable) {
	m.defaultTimespan = value
}

// SetDescription sets the description property value. A text description of the dashboard's purpose and functionality. This information assists users in understanding the dashboard but isn't displayed when viewing a dashboard.
func (m *Dashboards_API_Dashboard) SetDescription(value *string) {
	m.description = value
}

// SetIsBuiltIn sets the isBuiltIn property value. Indicates if a dashboard is built-in. True for built-in dashboards, false for user-created dashboards.
func (m *Dashboards_API_Dashboard) SetIsBuiltIn(value *bool) {
	m.isBuiltIn = value
}

// SetIsDefaultForAccount sets the isDefaultForAccount property value. Indicates whether this dashboard is the account group's default. True for default, false if not.
func (m *Dashboards_API_Dashboard) SetIsDefaultForAccount(value *bool) {
	m.isDefaultForAccount = value
}

// SetIsDefaultForUser sets the isDefaultForUser property value. Indicates whether this dashboard is the user's default. True for default, false if not.
func (m *Dashboards_API_Dashboard) SetIsDefaultForUser(value *bool) {
	m.isDefaultForUser = value
}

// SetIsGlobalOverride sets the isGlobalOverride property value. When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If set to `false`, the the widget's timespan is used.
func (m *Dashboards_API_Dashboard) SetIsGlobalOverride(value *bool) {
	m.isGlobalOverride = value
}

// SetIsMigratedReport sets the isMigratedReport property value. True if this dashboard was previously a report.
func (m *Dashboards_API_Dashboard) SetIsMigratedReport(value *bool) {
	m.isMigratedReport = value
}

// SetIsPrivate sets the isPrivate property value. A dashboard can be viewed by other users in the account. If true, only the creator of the dashboard may view it. If false, all users in the same account may view it.
func (m *Dashboards_API_Dashboard) SetIsPrivate(value *bool) {
	m.isPrivate = value
}

// SetLayout sets the layout property value. Dashboard layout configuration for arranging widgets.
func (m *Dashboards_API_Dashboard) SetLayout(value Dashboards_API_DashboardLayoutable) {
	m.layout = value
}

// SetLinks sets the _links property value. A links object containing the self and the snapshots links.
func (m *Dashboards_API_Dashboard) SetLinks(value Dashboards_API_DashboardLinksable) {
	m.links = value
}

// SetModifiedBy sets the modifiedBy property value. Identifier for the user that last modified a dashboard.
func (m *Dashboards_API_Dashboard) SetModifiedBy(value *string) {
	m.modifiedBy = value
}

// SetModifiedDate sets the modifiedDate property value. UTC date/time when a dashboard was last modified (ISO date-time format).
func (m *Dashboards_API_Dashboard) SetModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.modifiedDate = value
}

// SetRefreshRate sets the refreshRate property value. Auto-refresh interval for a dashboard. Use `off` to disable auto-refresh.
func (m *Dashboards_API_Dashboard) SetRefreshRate(value *Dashboards_API_RefreshRate) {
	m.refreshRate = value
}

// SetTitle sets the title property value. Title of a dashboard.
func (m *Dashboards_API_Dashboard) SetTitle(value *string) {
	m.title = value
}

// SetWidgets sets the widgets property value. The widgets property
func (m *Dashboards_API_Dashboard) SetWidgets(value []Dashboards_API_ApiWidgetable) {
	m.widgets = value
}

type Dashboards_API_Dashboardable interface {
	Dashboards_API_DashboardGlobalFilterIdable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAid() *string
	GetCreatedBy() *string
	GetDashboardId() *string
	GetDefaultTimespan() Dashboards_API_DefaultTimespanable
	GetDescription() *string
	GetIsBuiltIn() *bool
	GetIsDefaultForAccount() *bool
	GetIsDefaultForUser() *bool
	GetIsGlobalOverride() *bool
	GetIsMigratedReport() *bool
	GetIsPrivate() *bool
	GetLayout() Dashboards_API_DashboardLayoutable
	GetLinks() Dashboards_API_DashboardLinksable
	GetModifiedBy() *string
	GetModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetRefreshRate() *Dashboards_API_RefreshRate
	GetTitle() *string
	GetWidgets() []Dashboards_API_ApiWidgetable
	SetAid(value *string)
	SetCreatedBy(value *string)
	SetDashboardId(value *string)
	SetDefaultTimespan(value Dashboards_API_DefaultTimespanable)
	SetDescription(value *string)
	SetIsBuiltIn(value *bool)
	SetIsDefaultForAccount(value *bool)
	SetIsDefaultForUser(value *bool)
	SetIsGlobalOverride(value *bool)
	SetIsMigratedReport(value *bool)
	SetIsPrivate(value *bool)
	SetLayout(value Dashboards_API_DashboardLayoutable)
	SetLinks(value Dashboards_API_DashboardLinksable)
	SetModifiedBy(value *string)
	SetModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetRefreshRate(value *Dashboards_API_RefreshRate)
	SetTitle(value *string)
	SetWidgets(value []Dashboards_API_ApiWidgetable)
}
