// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Dashboards_API_ApiGeoMapWidget displays data on a geographic map, highlighting information across different regions.
type Dashboards_API_ApiGeoMapWidget struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The apiLink property
	// Deprecated:
	apiLink *string
	// Datasource of the geo map widget.
	dataSource *Dashboards_API_GeoMapDatasource
	// Direction of agent to agent metric.
	direction *Dashboards_API_DashboardMetricDirection
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	embedUrl *string
	// (Optional) Specifies the filters applied to the widget. When present, the `filters` property displays. Each filter object has two properties: `filterProperty` and `filterValue`. The `filterProperty` can be values like `AGENT`, `ENDPOINT_MACHINE_ID`, `TEST`, `MONITOR`, etc.  The `filterValue` represents an identifier array of the selected property.
	filters Dashboards_API_WidgetFiltersable
	// Specifies a fixed timespan for data aggregation.
	fixedTimespan Dashboards_API_ApiDurationable
	// Defines the property by which to aggregate the metric. Metrics are grouped based on unique values of the chosen property. Selecting `ALL` aggregates the data into a single group.
	groupBy *Dashboards_API_ApiAggregateProperty
	// Identifier of the widget.
	id *string
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	isEmbedded *bool
	// Indicates whether a separate map is displayed for each test within the widget. When set to true, individual maps are generated.
	isGeoMapPerTest *bool
	// A links object containing the self link.
	links Dashboards_API_SelfLinksable
	// Maximum scale configured in the widget.
	maxScale *float32
	// Determines how to aggregate the the metric.
	measure Dashboards_API_ApiWidgetMeasureable
	// Indicates the specific metric in the report, determined by the layer, test type, and metric values.
	metric *Dashboards_API_DashboardMetric
	// Metric group of widget as it appears in the UI. Note: may not be required in some cases.
	metricGroup *Dashboards_API_MetricGroup
	// Minimum scale configured in the widget.
	minScale *float32
	// Excludes alert suppression window data if set to `true`.
	shouldExcludeAlertSuppressionWindows *bool
	// Determines the card sorting criterion.
	// Deprecated:
	sortBy *Dashboards_API_WidgetSortProperty
	// Specifies the order in which cards are sorted.
	// Deprecated:
	sortDirection *Dashboards_API_WidgetSortDirection
	// Title of the widget
	title *string
	// Map widget type.
	typeEscaped *string
	// Prefix denoting the unit of measurement for the fixed Y-axis scale.
	unit *Dashboards_API_ApiWidgetFixedYScalePrefix
	// Visual mode in the UI. Either full or half the width of the window.
	visualMode *Dashboards_API_VisualMode
}

// NewDashboards_API_ApiGeoMapWidget instantiates a new Dashboards_API_ApiGeoMapWidget and sets the default values.
func NewDashboards_API_ApiGeoMapWidget() *Dashboards_API_ApiGeoMapWidget {
	m := &Dashboards_API_ApiGeoMapWidget{}
	m.SetAdditionalData(make(map[string]any))
	visualModeValue := FULL_DASHBOARDS_API_VISUALMODE
	m.SetVisualMode(&visualModeValue)
	return m
}

// CreateDashboards_API_ApiGeoMapWidgetFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDashboards_API_ApiGeoMapWidgetFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDashboards_API_ApiGeoMapWidget(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetApiLink gets the apiLink property value. The apiLink property
// Deprecated:
// returns a *string when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetApiLink() *string {
	return m.apiLink
}

// GetDataSource gets the dataSource property value. Datasource of the geo map widget.
// returns a *Dashboards_API_GeoMapDatasource when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetDataSource() *Dashboards_API_GeoMapDatasource {
	return m.dataSource
}

// GetDirection gets the direction property value. Direction of agent to agent metric.
// returns a *Dashboards_API_DashboardMetricDirection when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetDirection() *Dashboards_API_DashboardMetricDirection {
	return m.direction
}

// GetEmbedUrl gets the embedUrl property value. When `isEmbedded` is set to `true`, an `embedUrl` is provided.
// returns a *string when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetEmbedUrl() *string {
	return m.embedUrl
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["apiLink"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetApiLink(val)
		}
		return nil
	}
	res["dataSource"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_GeoMapDatasource)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDataSource(val.(*Dashboards_API_GeoMapDatasource))
		}
		return nil
	}
	res["direction"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_DashboardMetricDirection)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDirection(val.(*Dashboards_API_DashboardMetricDirection))
		}
		return nil
	}
	res["embedUrl"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEmbedUrl(val)
		}
		return nil
	}
	res["filters"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_WidgetFiltersFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFilters(val.(Dashboards_API_WidgetFiltersable))
		}
		return nil
	}
	res["fixedTimespan"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_ApiDurationFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFixedTimespan(val.(Dashboards_API_ApiDurationable))
		}
		return nil
	}
	res["groupBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_ApiAggregateProperty)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGroupBy(val.(*Dashboards_API_ApiAggregateProperty))
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["isEmbedded"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsEmbedded(val)
		}
		return nil
	}
	res["isGeoMapPerTest"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsGeoMapPerTest(val)
		}
		return nil
	}
	res["_links"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_SelfLinksFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLinks(val.(Dashboards_API_SelfLinksable))
		}
		return nil
	}
	res["maxScale"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMaxScale(val)
		}
		return nil
	}
	res["measure"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_ApiWidgetMeasureFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMeasure(val.(Dashboards_API_ApiWidgetMeasureable))
		}
		return nil
	}
	res["metric"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_DashboardMetric)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMetric(val.(*Dashboards_API_DashboardMetric))
		}
		return nil
	}
	res["metricGroup"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_MetricGroup)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMetricGroup(val.(*Dashboards_API_MetricGroup))
		}
		return nil
	}
	res["minScale"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMinScale(val)
		}
		return nil
	}
	res["shouldExcludeAlertSuppressionWindows"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetShouldExcludeAlertSuppressionWindows(val)
		}
		return nil
	}
	res["sortBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_WidgetSortProperty)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSortBy(val.(*Dashboards_API_WidgetSortProperty))
		}
		return nil
	}
	res["sortDirection"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_WidgetSortDirection)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSortDirection(val.(*Dashboards_API_WidgetSortDirection))
		}
		return nil
	}
	res["title"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTitle(val)
		}
		return nil
	}
	res["type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTypeEscaped(val)
		}
		return nil
	}
	res["unit"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_ApiWidgetFixedYScalePrefix)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUnit(val.(*Dashboards_API_ApiWidgetFixedYScalePrefix))
		}
		return nil
	}
	res["visualMode"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_VisualMode)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetVisualMode(val.(*Dashboards_API_VisualMode))
		}
		return nil
	}
	return res
}

// GetFilters gets the filters property value. (Optional) Specifies the filters applied to the widget. When present, the `filters` property displays. Each filter object has two properties: `filterProperty` and `filterValue`. The `filterProperty` can be values like `AGENT`, `ENDPOINT_MACHINE_ID`, `TEST`, `MONITOR`, etc.  The `filterValue` represents an identifier array of the selected property.
// returns a Dashboards_API_WidgetFiltersable when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetFilters() Dashboards_API_WidgetFiltersable {
	return m.filters
}

// GetFixedTimespan gets the fixedTimespan property value. Specifies a fixed timespan for data aggregation.
// returns a Dashboards_API_ApiDurationable when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetFixedTimespan() Dashboards_API_ApiDurationable {
	return m.fixedTimespan
}

// GetGroupBy gets the groupBy property value. Defines the property by which to aggregate the metric. Metrics are grouped based on unique values of the chosen property. Selecting `ALL` aggregates the data into a single group.
// returns a *Dashboards_API_ApiAggregateProperty when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetGroupBy() *Dashboards_API_ApiAggregateProperty {
	return m.groupBy
}

// GetId gets the id property value. Identifier of the widget.
// returns a *string when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetId() *string {
	return m.id
}

// GetIsEmbedded gets the isEmbedded property value. Set to `true` if widget is marked as embedded; otherwise, set to `false`.
// returns a *bool when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetIsEmbedded() *bool {
	return m.isEmbedded
}

// GetIsGeoMapPerTest gets the isGeoMapPerTest property value. Indicates whether a separate map is displayed for each test within the widget. When set to true, individual maps are generated.
// returns a *bool when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetIsGeoMapPerTest() *bool {
	return m.isGeoMapPerTest
}

// GetLinks gets the _links property value. A links object containing the self link.
// returns a Dashboards_API_SelfLinksable when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetLinks() Dashboards_API_SelfLinksable {
	return m.links
}

// GetMaxScale gets the maxScale property value. Maximum scale configured in the widget.
// returns a *float32 when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetMaxScale() *float32 {
	return m.maxScale
}

// GetMeasure gets the measure property value. Determines how to aggregate the the metric.
// returns a Dashboards_API_ApiWidgetMeasureable when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetMeasure() Dashboards_API_ApiWidgetMeasureable {
	return m.measure
}

// GetMetric gets the metric property value. Indicates the specific metric in the report, determined by the layer, test type, and metric values.
// returns a *Dashboards_API_DashboardMetric when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetMetric() *Dashboards_API_DashboardMetric {
	return m.metric
}

// GetMetricGroup gets the metricGroup property value. Metric group of widget as it appears in the UI. Note: may not be required in some cases.
// returns a *Dashboards_API_MetricGroup when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetMetricGroup() *Dashboards_API_MetricGroup {
	return m.metricGroup
}

// GetMinScale gets the minScale property value. Minimum scale configured in the widget.
// returns a *float32 when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetMinScale() *float32 {
	return m.minScale
}

// GetShouldExcludeAlertSuppressionWindows gets the shouldExcludeAlertSuppressionWindows property value. Excludes alert suppression window data if set to `true`.
// returns a *bool when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetShouldExcludeAlertSuppressionWindows() *bool {
	return m.shouldExcludeAlertSuppressionWindows
}

// GetSortBy gets the sortBy property value. Determines the card sorting criterion.
// Deprecated:
// returns a *Dashboards_API_WidgetSortProperty when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetSortBy() *Dashboards_API_WidgetSortProperty {
	return m.sortBy
}

// GetSortDirection gets the sortDirection property value. Specifies the order in which cards are sorted.
// Deprecated:
// returns a *Dashboards_API_WidgetSortDirection when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetSortDirection() *Dashboards_API_WidgetSortDirection {
	return m.sortDirection
}

// GetTitle gets the title property value. Title of the widget
// returns a *string when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetTitle() *string {
	return m.title
}

// GetTypeEscaped gets the type property value. Map widget type.
// returns a *string when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetTypeEscaped() *string {
	return m.typeEscaped
}

// GetUnit gets the unit property value. Prefix denoting the unit of measurement for the fixed Y-axis scale.
// returns a *Dashboards_API_ApiWidgetFixedYScalePrefix when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetUnit() *Dashboards_API_ApiWidgetFixedYScalePrefix {
	return m.unit
}

// GetVisualMode gets the visualMode property value. Visual mode in the UI. Either full or half the width of the window.
// returns a *Dashboards_API_VisualMode when successful
func (m *Dashboards_API_ApiGeoMapWidget) GetVisualMode() *Dashboards_API_VisualMode {
	return m.visualMode
}

// Serialize serializes information the current object
func (m *Dashboards_API_ApiGeoMapWidget) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetDataSource() != nil {
		cast := (*m.GetDataSource()).String()
		err := writer.WriteStringValue("dataSource", &cast)
		if err != nil {
			return err
		}
	}
	if m.GetDirection() != nil {
		cast := (*m.GetDirection()).String()
		err := writer.WriteStringValue("direction", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("filters", m.GetFilters())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("fixedTimespan", m.GetFixedTimespan())
		if err != nil {
			return err
		}
	}
	if m.GetGroupBy() != nil {
		cast := (*m.GetGroupBy()).String()
		err := writer.WriteStringValue("groupBy", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("isEmbedded", m.GetIsEmbedded())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("isGeoMapPerTest", m.GetIsGeoMapPerTest())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat32Value("maxScale", m.GetMaxScale())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("measure", m.GetMeasure())
		if err != nil {
			return err
		}
	}
	if m.GetMetric() != nil {
		cast := (*m.GetMetric()).String()
		err := writer.WriteStringValue("metric", &cast)
		if err != nil {
			return err
		}
	}
	if m.GetMetricGroup() != nil {
		cast := (*m.GetMetricGroup()).String()
		err := writer.WriteStringValue("metricGroup", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat32Value("minScale", m.GetMinScale())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("shouldExcludeAlertSuppressionWindows", m.GetShouldExcludeAlertSuppressionWindows())
		if err != nil {
			return err
		}
	}
	if m.GetSortBy() != nil {
		cast := (*m.GetSortBy()).String()
		err := writer.WriteStringValue("sortBy", &cast)
		if err != nil {
			return err
		}
	}
	if m.GetSortDirection() != nil {
		cast := (*m.GetSortDirection()).String()
		err := writer.WriteStringValue("sortDirection", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("title", m.GetTitle())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("type", m.GetTypeEscaped())
		if err != nil {
			return err
		}
	}
	if m.GetUnit() != nil {
		cast := (*m.GetUnit()).String()
		err := writer.WriteStringValue("unit", &cast)
		if err != nil {
			return err
		}
	}
	if m.GetVisualMode() != nil {
		cast := (*m.GetVisualMode()).String()
		err := writer.WriteStringValue("visualMode", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Dashboards_API_ApiGeoMapWidget) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetApiLink sets the apiLink property value. The apiLink property
// Deprecated:
func (m *Dashboards_API_ApiGeoMapWidget) SetApiLink(value *string) {
	m.apiLink = value
}

// SetDataSource sets the dataSource property value. Datasource of the geo map widget.
func (m *Dashboards_API_ApiGeoMapWidget) SetDataSource(value *Dashboards_API_GeoMapDatasource) {
	m.dataSource = value
}

// SetDirection sets the direction property value. Direction of agent to agent metric.
func (m *Dashboards_API_ApiGeoMapWidget) SetDirection(value *Dashboards_API_DashboardMetricDirection) {
	m.direction = value
}

// SetEmbedUrl sets the embedUrl property value. When `isEmbedded` is set to `true`, an `embedUrl` is provided.
func (m *Dashboards_API_ApiGeoMapWidget) SetEmbedUrl(value *string) {
	m.embedUrl = value
}

// SetFilters sets the filters property value. (Optional) Specifies the filters applied to the widget. When present, the `filters` property displays. Each filter object has two properties: `filterProperty` and `filterValue`. The `filterProperty` can be values like `AGENT`, `ENDPOINT_MACHINE_ID`, `TEST`, `MONITOR`, etc.  The `filterValue` represents an identifier array of the selected property.
func (m *Dashboards_API_ApiGeoMapWidget) SetFilters(value Dashboards_API_WidgetFiltersable) {
	m.filters = value
}

// SetFixedTimespan sets the fixedTimespan property value. Specifies a fixed timespan for data aggregation.
func (m *Dashboards_API_ApiGeoMapWidget) SetFixedTimespan(value Dashboards_API_ApiDurationable) {
	m.fixedTimespan = value
}

// SetGroupBy sets the groupBy property value. Defines the property by which to aggregate the metric. Metrics are grouped based on unique values of the chosen property. Selecting `ALL` aggregates the data into a single group.
func (m *Dashboards_API_ApiGeoMapWidget) SetGroupBy(value *Dashboards_API_ApiAggregateProperty) {
	m.groupBy = value
}

// SetId sets the id property value. Identifier of the widget.
func (m *Dashboards_API_ApiGeoMapWidget) SetId(value *string) {
	m.id = value
}

// SetIsEmbedded sets the isEmbedded property value. Set to `true` if widget is marked as embedded; otherwise, set to `false`.
func (m *Dashboards_API_ApiGeoMapWidget) SetIsEmbedded(value *bool) {
	m.isEmbedded = value
}

// SetIsGeoMapPerTest sets the isGeoMapPerTest property value. Indicates whether a separate map is displayed for each test within the widget. When set to true, individual maps are generated.
func (m *Dashboards_API_ApiGeoMapWidget) SetIsGeoMapPerTest(value *bool) {
	m.isGeoMapPerTest = value
}

// SetLinks sets the _links property value. A links object containing the self link.
func (m *Dashboards_API_ApiGeoMapWidget) SetLinks(value Dashboards_API_SelfLinksable) {
	m.links = value
}

// SetMaxScale sets the maxScale property value. Maximum scale configured in the widget.
func (m *Dashboards_API_ApiGeoMapWidget) SetMaxScale(value *float32) {
	m.maxScale = value
}

// SetMeasure sets the measure property value. Determines how to aggregate the the metric.
func (m *Dashboards_API_ApiGeoMapWidget) SetMeasure(value Dashboards_API_ApiWidgetMeasureable) {
	m.measure = value
}

// SetMetric sets the metric property value. Indicates the specific metric in the report, determined by the layer, test type, and metric values.
func (m *Dashboards_API_ApiGeoMapWidget) SetMetric(value *Dashboards_API_DashboardMetric) {
	m.metric = value
}

// SetMetricGroup sets the metricGroup property value. Metric group of widget as it appears in the UI. Note: may not be required in some cases.
func (m *Dashboards_API_ApiGeoMapWidget) SetMetricGroup(value *Dashboards_API_MetricGroup) {
	m.metricGroup = value
}

// SetMinScale sets the minScale property value. Minimum scale configured in the widget.
func (m *Dashboards_API_ApiGeoMapWidget) SetMinScale(value *float32) {
	m.minScale = value
}

// SetShouldExcludeAlertSuppressionWindows sets the shouldExcludeAlertSuppressionWindows property value. Excludes alert suppression window data if set to `true`.
func (m *Dashboards_API_ApiGeoMapWidget) SetShouldExcludeAlertSuppressionWindows(value *bool) {
	m.shouldExcludeAlertSuppressionWindows = value
}

// SetSortBy sets the sortBy property value. Determines the card sorting criterion.
// Deprecated:
func (m *Dashboards_API_ApiGeoMapWidget) SetSortBy(value *Dashboards_API_WidgetSortProperty) {
	m.sortBy = value
}

// SetSortDirection sets the sortDirection property value. Specifies the order in which cards are sorted.
// Deprecated:
func (m *Dashboards_API_ApiGeoMapWidget) SetSortDirection(value *Dashboards_API_WidgetSortDirection) {
	m.sortDirection = value
}

// SetTitle sets the title property value. Title of the widget
func (m *Dashboards_API_ApiGeoMapWidget) SetTitle(value *string) {
	m.title = value
}

// SetTypeEscaped sets the type property value. Map widget type.
func (m *Dashboards_API_ApiGeoMapWidget) SetTypeEscaped(value *string) {
	m.typeEscaped = value
}

// SetUnit sets the unit property value. Prefix denoting the unit of measurement for the fixed Y-axis scale.
func (m *Dashboards_API_ApiGeoMapWidget) SetUnit(value *Dashboards_API_ApiWidgetFixedYScalePrefix) {
	m.unit = value
}

// SetVisualMode sets the visualMode property value. Visual mode in the UI. Either full or half the width of the window.
func (m *Dashboards_API_ApiGeoMapWidget) SetVisualMode(value *Dashboards_API_VisualMode) {
	m.visualMode = value
}

type Dashboards_API_ApiGeoMapWidgetable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetApiLink() *string
	GetDataSource() *Dashboards_API_GeoMapDatasource
	GetDirection() *Dashboards_API_DashboardMetricDirection
	GetEmbedUrl() *string
	GetFilters() Dashboards_API_WidgetFiltersable
	GetFixedTimespan() Dashboards_API_ApiDurationable
	GetGroupBy() *Dashboards_API_ApiAggregateProperty
	GetId() *string
	GetIsEmbedded() *bool
	GetIsGeoMapPerTest() *bool
	GetLinks() Dashboards_API_SelfLinksable
	GetMaxScale() *float32
	GetMeasure() Dashboards_API_ApiWidgetMeasureable
	GetMetric() *Dashboards_API_DashboardMetric
	GetMetricGroup() *Dashboards_API_MetricGroup
	GetMinScale() *float32
	GetShouldExcludeAlertSuppressionWindows() *bool
	GetSortBy() *Dashboards_API_WidgetSortProperty
	GetSortDirection() *Dashboards_API_WidgetSortDirection
	GetTitle() *string
	GetTypeEscaped() *string
	GetUnit() *Dashboards_API_ApiWidgetFixedYScalePrefix
	GetVisualMode() *Dashboards_API_VisualMode
	SetApiLink(value *string)
	SetDataSource(value *Dashboards_API_GeoMapDatasource)
	SetDirection(value *Dashboards_API_DashboardMetricDirection)
	SetEmbedUrl(value *string)
	SetFilters(value Dashboards_API_WidgetFiltersable)
	SetFixedTimespan(value Dashboards_API_ApiDurationable)
	SetGroupBy(value *Dashboards_API_ApiAggregateProperty)
	SetId(value *string)
	SetIsEmbedded(value *bool)
	SetIsGeoMapPerTest(value *bool)
	SetLinks(value Dashboards_API_SelfLinksable)
	SetMaxScale(value *float32)
	SetMeasure(value Dashboards_API_ApiWidgetMeasureable)
	SetMetric(value *Dashboards_API_DashboardMetric)
	SetMetricGroup(value *Dashboards_API_MetricGroup)
	SetMinScale(value *float32)
	SetShouldExcludeAlertSuppressionWindows(value *bool)
	SetSortBy(value *Dashboards_API_WidgetSortProperty)
	SetSortDirection(value *Dashboards_API_WidgetSortDirection)
	SetTitle(value *string)
	SetTypeEscaped(value *string)
	SetUnit(value *Dashboards_API_ApiWidgetFixedYScalePrefix)
	SetVisualMode(value *Dashboards_API_VisualMode)
}
