// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Dashboards_API_ApiAgentStatusSummary summary of the agent status.
type Dashboards_API_ApiAgentStatusSummary struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Shows the number of agents with disabled status.
	disabled *int32
	// Shows the number of agents with an offline status.
	offline *int32
	// Shows the number of agents with an online status.
	online *int32
}

// NewDashboards_API_ApiAgentStatusSummary instantiates a new Dashboards_API_ApiAgentStatusSummary and sets the default values.
func NewDashboards_API_ApiAgentStatusSummary() *Dashboards_API_ApiAgentStatusSummary {
	m := &Dashboards_API_ApiAgentStatusSummary{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateDashboards_API_ApiAgentStatusSummaryFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDashboards_API_ApiAgentStatusSummaryFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDashboards_API_ApiAgentStatusSummary(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Dashboards_API_ApiAgentStatusSummary) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDisabled gets the disabled property value. Shows the number of agents with disabled status.
// returns a *int32 when successful
func (m *Dashboards_API_ApiAgentStatusSummary) GetDisabled() *int32 {
	return m.disabled
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Dashboards_API_ApiAgentStatusSummary) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["disabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDisabled(val)
		}
		return nil
	}
	res["offline"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetOffline(val)
		}
		return nil
	}
	res["online"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetOnline(val)
		}
		return nil
	}
	return res
}

// GetOffline gets the offline property value. Shows the number of agents with an offline status.
// returns a *int32 when successful
func (m *Dashboards_API_ApiAgentStatusSummary) GetOffline() *int32 {
	return m.offline
}

// GetOnline gets the online property value. Shows the number of agents with an online status.
// returns a *int32 when successful
func (m *Dashboards_API_ApiAgentStatusSummary) GetOnline() *int32 {
	return m.online
}

// Serialize serializes information the current object
func (m *Dashboards_API_ApiAgentStatusSummary) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt32Value("disabled", m.GetDisabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("offline", m.GetOffline())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("online", m.GetOnline())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Dashboards_API_ApiAgentStatusSummary) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDisabled sets the disabled property value. Shows the number of agents with disabled status.
func (m *Dashboards_API_ApiAgentStatusSummary) SetDisabled(value *int32) {
	m.disabled = value
}

// SetOffline sets the offline property value. Shows the number of agents with an offline status.
func (m *Dashboards_API_ApiAgentStatusSummary) SetOffline(value *int32) {
	m.offline = value
}

// SetOnline sets the online property value. Shows the number of agents with an online status.
func (m *Dashboards_API_ApiAgentStatusSummary) SetOnline(value *int32) {
	m.online = value
}

type Dashboards_API_ApiAgentStatusSummaryable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetDisabled() *int32
	GetOffline() *int32
	GetOnline() *int32
	SetDisabled(value *int32)
	SetOffline(value *int32)
	SetOnline(value *int32)
}
