// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"

	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Dashboards_API_ApiDashboard dashboard upon which this dashboard snapshot is based upon.
type Dashboards_API_ApiDashboard struct {
	// Identifier for the account group associated with a dashboard.
	// Deprecated:
	accountId *int64
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Identifier for the account group associated with a dashboard.
	aid *string
	// A links array containing the self and the snapshots links.
	// Deprecated:
	apiLink []Dashboards_API_ApiDashboard_apiLinkable
	// Identifier for the user that created a dashboard.
	// Deprecated:
	createdBy *int64
	// Identifier for the user that created a dashboard.
	dashboardCreatedBy *string
	// Identifier of a dashboard.
	dashboardId *string
	// Identifier for the user that last modified a dashboard.
	dashboardModifiedBy *string
	// UTC date/time when a dashboard was last modified (ISO date-time format).
	dashboardModifiedDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// The defaultTimespan property
	defaultTimespan Dashboards_API_DefaultTimespanable
	// A text description of the dashboard's purpose and functionality. This information assists users in understanding the dashboard but isn't displayed when viewing a dashboard.
	description *string
	// Default global dashboard filter ID (obtained from `/dashboards/filters` endpoint).
	globalFilterId *string
	// When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If set to `false`, the the widget's timespan is used.
	// Deprecated:
	globalOverride *bool
	// Indicates if a dashboard is built-in. True for built-in dashboards, false for user-created dashboards.
	isBuiltIn *bool
	// Indicates whether this dashboard is the account group's default. True for default, false if not.
	isDefaultForAccount *bool
	// Indicates whether this dashboard is the user's default. True for default, false if not.
	isDefaultForUser *bool
	// When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If set to `false`, the the widget's timespan is used.
	isGlobalOverride *bool
	// True if this dashboard was previously a report.
	isMigratedReport *bool
	// A dashboard can be viewed by other users in the account. If true, only the creator of the dashboard may view it. If false, all users in the same account may view it.
	isPrivate *bool
	// Dashboard layout configuration for arranging widgets.
	layout Dashboards_API_DashboardLayoutable
	// A links object containing the self and the snapshots links.
	links Dashboards_API_DashboardLinksable
	// True if this dashboard was previously a report.
	// Deprecated:
	migratedReport *bool
	// Identifier for the user that last modified a dashboard.
	// Deprecated:
	modifiedBy *int64
	// UTC date/time when a dashboard was last modified.
	// Deprecated:
	modifiedDate *string
	// Auto-refresh interval for a dashboard. Use `off` to disable auto-refresh.
	refreshRate *Dashboards_API_RefreshRate
	// Title of a dashboard.
	title *string
	// The widgets property
	widgets []Dashboards_API_ApiWidgetable
}

// NewDashboards_API_ApiDashboard instantiates a new Dashboards_API_ApiDashboard and sets the default values.
func NewDashboards_API_ApiDashboard() *Dashboards_API_ApiDashboard {
	m := &Dashboards_API_ApiDashboard{}
	m.SetAdditionalData(make(map[string]any))
	refreshRateValue := OFF_DASHBOARDS_API_REFRESHRATE
	m.SetRefreshRate(&refreshRateValue)
	return m
}

// CreateDashboards_API_ApiDashboardFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDashboards_API_ApiDashboardFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDashboards_API_ApiDashboard(), nil
}

// GetAccountId gets the accountId property value. Identifier for the account group associated with a dashboard.
// Deprecated:
// returns a *int64 when successful
func (m *Dashboards_API_ApiDashboard) GetAccountId() *int64 {
	return m.accountId
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Dashboards_API_ApiDashboard) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAid gets the aid property value. Identifier for the account group associated with a dashboard.
// returns a *string when successful
func (m *Dashboards_API_ApiDashboard) GetAid() *string {
	return m.aid
}

// GetApiLink gets the apiLink property value. A links array containing the self and the snapshots links.
// Deprecated:
// returns a []Dashboards_API_ApiDashboard_apiLinkable when successful
func (m *Dashboards_API_ApiDashboard) GetApiLink() []Dashboards_API_ApiDashboard_apiLinkable {
	return m.apiLink
}

// GetCreatedBy gets the createdBy property value. Identifier for the user that created a dashboard.
// Deprecated:
// returns a *int64 when successful
func (m *Dashboards_API_ApiDashboard) GetCreatedBy() *int64 {
	return m.createdBy
}

// GetDashboardCreatedBy gets the dashboardCreatedBy property value. Identifier for the user that created a dashboard.
// returns a *string when successful
func (m *Dashboards_API_ApiDashboard) GetDashboardCreatedBy() *string {
	return m.dashboardCreatedBy
}

// GetDashboardId gets the dashboardId property value. Identifier of a dashboard.
// returns a *string when successful
func (m *Dashboards_API_ApiDashboard) GetDashboardId() *string {
	return m.dashboardId
}

// GetDashboardModifiedBy gets the dashboardModifiedBy property value. Identifier for the user that last modified a dashboard.
// returns a *string when successful
func (m *Dashboards_API_ApiDashboard) GetDashboardModifiedBy() *string {
	return m.dashboardModifiedBy
}

// GetDashboardModifiedDate gets the dashboardModifiedDate property value. UTC date/time when a dashboard was last modified (ISO date-time format).
// returns a *Time when successful
func (m *Dashboards_API_ApiDashboard) GetDashboardModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.dashboardModifiedDate
}

// GetDefaultTimespan gets the defaultTimespan property value. The defaultTimespan property
// returns a Dashboards_API_DefaultTimespanable when successful
func (m *Dashboards_API_ApiDashboard) GetDefaultTimespan() Dashboards_API_DefaultTimespanable {
	return m.defaultTimespan
}

// GetDescription gets the description property value. A text description of the dashboard's purpose and functionality. This information assists users in understanding the dashboard but isn't displayed when viewing a dashboard.
// returns a *string when successful
func (m *Dashboards_API_ApiDashboard) GetDescription() *string {
	return m.description
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Dashboards_API_ApiDashboard) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["accountId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAccountId(val)
		}
		return nil
	}
	res["aid"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAid(val)
		}
		return nil
	}
	res["apiLink"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateDashboards_API_ApiDashboard_apiLinkFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Dashboards_API_ApiDashboard_apiLinkable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Dashboards_API_ApiDashboard_apiLinkable)
				}
			}
			m.SetApiLink(res)
		}
		return nil
	}
	res["createdBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedBy(val)
		}
		return nil
	}
	res["dashboardCreatedBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDashboardCreatedBy(val)
		}
		return nil
	}
	res["dashboardId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDashboardId(val)
		}
		return nil
	}
	res["dashboardModifiedBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDashboardModifiedBy(val)
		}
		return nil
	}
	res["dashboardModifiedDate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDashboardModifiedDate(val)
		}
		return nil
	}
	res["defaultTimespan"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_DefaultTimespanFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDefaultTimespan(val.(Dashboards_API_DefaultTimespanable))
		}
		return nil
	}
	res["description"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDescription(val)
		}
		return nil
	}
	res["globalFilterId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGlobalFilterId(val)
		}
		return nil
	}
	res["globalOverride"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGlobalOverride(val)
		}
		return nil
	}
	res["isBuiltIn"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsBuiltIn(val)
		}
		return nil
	}
	res["isDefaultForAccount"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsDefaultForAccount(val)
		}
		return nil
	}
	res["isDefaultForUser"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsDefaultForUser(val)
		}
		return nil
	}
	res["isGlobalOverride"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsGlobalOverride(val)
		}
		return nil
	}
	res["isMigratedReport"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsMigratedReport(val)
		}
		return nil
	}
	res["isPrivate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsPrivate(val)
		}
		return nil
	}
	res["layout"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_DashboardLayoutFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLayout(val.(Dashboards_API_DashboardLayoutable))
		}
		return nil
	}
	res["_links"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDashboards_API_DashboardLinksFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLinks(val.(Dashboards_API_DashboardLinksable))
		}
		return nil
	}
	res["migratedReport"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMigratedReport(val)
		}
		return nil
	}
	res["modifiedBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedBy(val)
		}
		return nil
	}
	res["modifiedDate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedDate(val)
		}
		return nil
	}
	res["refreshRate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseDashboards_API_RefreshRate)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRefreshRate(val.(*Dashboards_API_RefreshRate))
		}
		return nil
	}
	res["title"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTitle(val)
		}
		return nil
	}
	res["widgets"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateDashboards_API_ApiWidgetFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Dashboards_API_ApiWidgetable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Dashboards_API_ApiWidgetable)
				}
			}
			m.SetWidgets(res)
		}
		return nil
	}
	return res
}

// GetGlobalFilterId gets the globalFilterId property value. Default global dashboard filter ID (obtained from `/dashboards/filters` endpoint).
// returns a *string when successful
func (m *Dashboards_API_ApiDashboard) GetGlobalFilterId() *string {
	return m.globalFilterId
}

// GetGlobalOverride gets the globalOverride property value. When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If set to `false`, the the widget's timespan is used.
// Deprecated:
// returns a *bool when successful
func (m *Dashboards_API_ApiDashboard) GetGlobalOverride() *bool {
	return m.globalOverride
}

// GetIsBuiltIn gets the isBuiltIn property value. Indicates if a dashboard is built-in. True for built-in dashboards, false for user-created dashboards.
// returns a *bool when successful
func (m *Dashboards_API_ApiDashboard) GetIsBuiltIn() *bool {
	return m.isBuiltIn
}

// GetIsDefaultForAccount gets the isDefaultForAccount property value. Indicates whether this dashboard is the account group's default. True for default, false if not.
// returns a *bool when successful
func (m *Dashboards_API_ApiDashboard) GetIsDefaultForAccount() *bool {
	return m.isDefaultForAccount
}

// GetIsDefaultForUser gets the isDefaultForUser property value. Indicates whether this dashboard is the user's default. True for default, false if not.
// returns a *bool when successful
func (m *Dashboards_API_ApiDashboard) GetIsDefaultForUser() *bool {
	return m.isDefaultForUser
}

// GetIsGlobalOverride gets the isGlobalOverride property value. When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If set to `false`, the the widget's timespan is used.
// returns a *bool when successful
func (m *Dashboards_API_ApiDashboard) GetIsGlobalOverride() *bool {
	return m.isGlobalOverride
}

// GetIsMigratedReport gets the isMigratedReport property value. True if this dashboard was previously a report.
// returns a *bool when successful
func (m *Dashboards_API_ApiDashboard) GetIsMigratedReport() *bool {
	return m.isMigratedReport
}

// GetIsPrivate gets the isPrivate property value. A dashboard can be viewed by other users in the account. If true, only the creator of the dashboard may view it. If false, all users in the same account may view it.
// returns a *bool when successful
func (m *Dashboards_API_ApiDashboard) GetIsPrivate() *bool {
	return m.isPrivate
}

// GetLayout gets the layout property value. Dashboard layout configuration for arranging widgets.
// returns a Dashboards_API_DashboardLayoutable when successful
func (m *Dashboards_API_ApiDashboard) GetLayout() Dashboards_API_DashboardLayoutable {
	return m.layout
}

// GetLinks gets the _links property value. A links object containing the self and the snapshots links.
// returns a Dashboards_API_DashboardLinksable when successful
func (m *Dashboards_API_ApiDashboard) GetLinks() Dashboards_API_DashboardLinksable {
	return m.links
}

// GetMigratedReport gets the migratedReport property value. True if this dashboard was previously a report.
// Deprecated:
// returns a *bool when successful
func (m *Dashboards_API_ApiDashboard) GetMigratedReport() *bool {
	return m.migratedReport
}

// GetModifiedBy gets the modifiedBy property value. Identifier for the user that last modified a dashboard.
// Deprecated:
// returns a *int64 when successful
func (m *Dashboards_API_ApiDashboard) GetModifiedBy() *int64 {
	return m.modifiedBy
}

// GetModifiedDate gets the modifiedDate property value. UTC date/time when a dashboard was last modified.
// Deprecated:
// returns a *string when successful
func (m *Dashboards_API_ApiDashboard) GetModifiedDate() *string {
	return m.modifiedDate
}

// GetRefreshRate gets the refreshRate property value. Auto-refresh interval for a dashboard. Use `off` to disable auto-refresh.
// returns a *Dashboards_API_RefreshRate when successful
func (m *Dashboards_API_ApiDashboard) GetRefreshRate() *Dashboards_API_RefreshRate {
	return m.refreshRate
}

// GetTitle gets the title property value. Title of a dashboard.
// returns a *string when successful
func (m *Dashboards_API_ApiDashboard) GetTitle() *string {
	return m.title
}

// GetWidgets gets the widgets property value. The widgets property
// returns a []Dashboards_API_ApiWidgetable when successful
func (m *Dashboards_API_ApiDashboard) GetWidgets() []Dashboards_API_ApiWidgetable {
	return m.widgets
}

// Serialize serializes information the current object
func (m *Dashboards_API_ApiDashboard) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetApiLink() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetApiLink()))
		for i, v := range m.GetApiLink() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("apiLink", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("defaultTimespan", m.GetDefaultTimespan())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("description", m.GetDescription())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("globalFilterId", m.GetGlobalFilterId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("globalOverride", m.GetGlobalOverride())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("isGlobalOverride", m.GetIsGlobalOverride())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("isPrivate", m.GetIsPrivate())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("layout", m.GetLayout())
		if err != nil {
			return err
		}
	}
	if m.GetRefreshRate() != nil {
		cast := (*m.GetRefreshRate()).String()
		err := writer.WriteStringValue("refreshRate", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("title", m.GetTitle())
		if err != nil {
			return err
		}
	}
	if m.GetWidgets() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetWidgets()))
		for i, v := range m.GetWidgets() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("widgets", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAccountId sets the accountId property value. Identifier for the account group associated with a dashboard.
// Deprecated:
func (m *Dashboards_API_ApiDashboard) SetAccountId(value *int64) {
	m.accountId = value
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Dashboards_API_ApiDashboard) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAid sets the aid property value. Identifier for the account group associated with a dashboard.
func (m *Dashboards_API_ApiDashboard) SetAid(value *string) {
	m.aid = value
}

// SetApiLink sets the apiLink property value. A links array containing the self and the snapshots links.
// Deprecated:
func (m *Dashboards_API_ApiDashboard) SetApiLink(value []Dashboards_API_ApiDashboard_apiLinkable) {
	m.apiLink = value
}

// SetCreatedBy sets the createdBy property value. Identifier for the user that created a dashboard.
// Deprecated:
func (m *Dashboards_API_ApiDashboard) SetCreatedBy(value *int64) {
	m.createdBy = value
}

// SetDashboardCreatedBy sets the dashboardCreatedBy property value. Identifier for the user that created a dashboard.
func (m *Dashboards_API_ApiDashboard) SetDashboardCreatedBy(value *string) {
	m.dashboardCreatedBy = value
}

// SetDashboardId sets the dashboardId property value. Identifier of a dashboard.
func (m *Dashboards_API_ApiDashboard) SetDashboardId(value *string) {
	m.dashboardId = value
}

// SetDashboardModifiedBy sets the dashboardModifiedBy property value. Identifier for the user that last modified a dashboard.
func (m *Dashboards_API_ApiDashboard) SetDashboardModifiedBy(value *string) {
	m.dashboardModifiedBy = value
}

// SetDashboardModifiedDate sets the dashboardModifiedDate property value. UTC date/time when a dashboard was last modified (ISO date-time format).
func (m *Dashboards_API_ApiDashboard) SetDashboardModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.dashboardModifiedDate = value
}

// SetDefaultTimespan sets the defaultTimespan property value. The defaultTimespan property
func (m *Dashboards_API_ApiDashboard) SetDefaultTimespan(value Dashboards_API_DefaultTimespanable) {
	m.defaultTimespan = value
}

// SetDescription sets the description property value. A text description of the dashboard's purpose and functionality. This information assists users in understanding the dashboard but isn't displayed when viewing a dashboard.
func (m *Dashboards_API_ApiDashboard) SetDescription(value *string) {
	m.description = value
}

// SetGlobalFilterId sets the globalFilterId property value. Default global dashboard filter ID (obtained from `/dashboards/filters` endpoint).
func (m *Dashboards_API_ApiDashboard) SetGlobalFilterId(value *string) {
	m.globalFilterId = value
}

// SetGlobalOverride sets the globalOverride property value. When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If set to `false`, the the widget's timespan is used.
// Deprecated:
func (m *Dashboards_API_ApiDashboard) SetGlobalOverride(value *bool) {
	m.globalOverride = value
}

// SetIsBuiltIn sets the isBuiltIn property value. Indicates if a dashboard is built-in. True for built-in dashboards, false for user-created dashboards.
func (m *Dashboards_API_ApiDashboard) SetIsBuiltIn(value *bool) {
	m.isBuiltIn = value
}

// SetIsDefaultForAccount sets the isDefaultForAccount property value. Indicates whether this dashboard is the account group's default. True for default, false if not.
func (m *Dashboards_API_ApiDashboard) SetIsDefaultForAccount(value *bool) {
	m.isDefaultForAccount = value
}

// SetIsDefaultForUser sets the isDefaultForUser property value. Indicates whether this dashboard is the user's default. True for default, false if not.
func (m *Dashboards_API_ApiDashboard) SetIsDefaultForUser(value *bool) {
	m.isDefaultForUser = value
}

// SetIsGlobalOverride sets the isGlobalOverride property value. When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If set to `false`, the the widget's timespan is used.
func (m *Dashboards_API_ApiDashboard) SetIsGlobalOverride(value *bool) {
	m.isGlobalOverride = value
}

// SetIsMigratedReport sets the isMigratedReport property value. True if this dashboard was previously a report.
func (m *Dashboards_API_ApiDashboard) SetIsMigratedReport(value *bool) {
	m.isMigratedReport = value
}

// SetIsPrivate sets the isPrivate property value. A dashboard can be viewed by other users in the account. If true, only the creator of the dashboard may view it. If false, all users in the same account may view it.
func (m *Dashboards_API_ApiDashboard) SetIsPrivate(value *bool) {
	m.isPrivate = value
}

// SetLayout sets the layout property value. Dashboard layout configuration for arranging widgets.
func (m *Dashboards_API_ApiDashboard) SetLayout(value Dashboards_API_DashboardLayoutable) {
	m.layout = value
}

// SetLinks sets the _links property value. A links object containing the self and the snapshots links.
func (m *Dashboards_API_ApiDashboard) SetLinks(value Dashboards_API_DashboardLinksable) {
	m.links = value
}

// SetMigratedReport sets the migratedReport property value. True if this dashboard was previously a report.
// Deprecated:
func (m *Dashboards_API_ApiDashboard) SetMigratedReport(value *bool) {
	m.migratedReport = value
}

// SetModifiedBy sets the modifiedBy property value. Identifier for the user that last modified a dashboard.
// Deprecated:
func (m *Dashboards_API_ApiDashboard) SetModifiedBy(value *int64) {
	m.modifiedBy = value
}

// SetModifiedDate sets the modifiedDate property value. UTC date/time when a dashboard was last modified.
// Deprecated:
func (m *Dashboards_API_ApiDashboard) SetModifiedDate(value *string) {
	m.modifiedDate = value
}

// SetRefreshRate sets the refreshRate property value. Auto-refresh interval for a dashboard. Use `off` to disable auto-refresh.
func (m *Dashboards_API_ApiDashboard) SetRefreshRate(value *Dashboards_API_RefreshRate) {
	m.refreshRate = value
}

// SetTitle sets the title property value. Title of a dashboard.
func (m *Dashboards_API_ApiDashboard) SetTitle(value *string) {
	m.title = value
}

// SetWidgets sets the widgets property value. The widgets property
func (m *Dashboards_API_ApiDashboard) SetWidgets(value []Dashboards_API_ApiWidgetable) {
	m.widgets = value
}

type Dashboards_API_ApiDashboardable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAccountId() *int64
	GetAid() *string
	GetApiLink() []Dashboards_API_ApiDashboard_apiLinkable
	GetCreatedBy() *int64
	GetDashboardCreatedBy() *string
	GetDashboardId() *string
	GetDashboardModifiedBy() *string
	GetDashboardModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetDefaultTimespan() Dashboards_API_DefaultTimespanable
	GetDescription() *string
	GetGlobalFilterId() *string
	GetGlobalOverride() *bool
	GetIsBuiltIn() *bool
	GetIsDefaultForAccount() *bool
	GetIsDefaultForUser() *bool
	GetIsGlobalOverride() *bool
	GetIsMigratedReport() *bool
	GetIsPrivate() *bool
	GetLayout() Dashboards_API_DashboardLayoutable
	GetLinks() Dashboards_API_DashboardLinksable
	GetMigratedReport() *bool
	GetModifiedBy() *int64
	GetModifiedDate() *string
	GetRefreshRate() *Dashboards_API_RefreshRate
	GetTitle() *string
	GetWidgets() []Dashboards_API_ApiWidgetable
	SetAccountId(value *int64)
	SetAid(value *string)
	SetApiLink(value []Dashboards_API_ApiDashboard_apiLinkable)
	SetCreatedBy(value *int64)
	SetDashboardCreatedBy(value *string)
	SetDashboardId(value *string)
	SetDashboardModifiedBy(value *string)
	SetDashboardModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetDefaultTimespan(value Dashboards_API_DefaultTimespanable)
	SetDescription(value *string)
	SetGlobalFilterId(value *string)
	SetGlobalOverride(value *bool)
	SetIsBuiltIn(value *bool)
	SetIsDefaultForAccount(value *bool)
	SetIsDefaultForUser(value *bool)
	SetIsGlobalOverride(value *bool)
	SetIsMigratedReport(value *bool)
	SetIsPrivate(value *bool)
	SetLayout(value Dashboards_API_DashboardLayoutable)
	SetLinks(value Dashboards_API_DashboardLinksable)
	SetMigratedReport(value *bool)
	SetModifiedBy(value *int64)
	SetModifiedDate(value *string)
	SetRefreshRate(value *Dashboards_API_RefreshRate)
	SetTitle(value *string)
	SetWidgets(value []Dashboards_API_ApiWidgetable)
}
