// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// Data source for the list widget.
type Dashboards_API_ListDatasource int

const (
	EVENT_DETECTION_DASHBOARDS_API_LISTDATASOURCE Dashboards_API_ListDatasource = iota
)

func (i Dashboards_API_ListDatasource) String() string {
	return []string{"EVENT_DETECTION"}[i]
}

func ParseDashboards_API_ListDatasource(v string) (any, error) {
	result := EVENT_DETECTION_DASHBOARDS_API_LISTDATASOURCE
	switch v {
	case "EVENT_DETECTION":
		result = EVENT_DETECTION_DASHBOARDS_API_LISTDATASOURCE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeDashboards_API_ListDatasource(values []Dashboards_API_ListDatasource) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Dashboards_API_ListDatasource) isMultiValue() bool {
	return false
}
