// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest dNS server test details. This object is only available when the topology `type` is `dns`.
type Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// How long it took to resolve the DNS query in milliseconds.
	resolutionTime *int32
}

// NewEndpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest instantiates a new Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest and sets the default values.
func NewEndpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest() *Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest {
	m := &Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateEndpoint_Test_Results_API_LocalNetworkTopologyDnsServerTestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEndpoint_Test_Results_API_LocalNetworkTopologyDnsServerTestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewEndpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["resolutionTime"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetResolutionTime(val)
		}
		return nil
	}
	return res
}

// GetResolutionTime gets the resolutionTime property value. How long it took to resolve the DNS query in milliseconds.
// returns a *int32 when successful
func (m *Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest) GetResolutionTime() *int32 {
	return m.resolutionTime
}

// Serialize serializes information the current object
func (m *Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetResolutionTime sets the resolutionTime property value. How long it took to resolve the DNS query in milliseconds.
func (m *Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTest) SetResolutionTime(value *int32) {
	m.resolutionTime = value
}

type Endpoint_Test_Results_API_LocalNetworkTopologyDnsServerTestable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetResolutionTime() *int32
	SetResolutionTime(value *int32)
}
