// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// A links object containing the self link.
	links Endpoint_Test_Results_API_SelfLinksable
	// The results property
	results []Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultable
	// The test property
	test Endpoint_Test_Results_API_DynamicTestable
}

// NewEndpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults instantiates a new Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults and sets the default values.
func NewEndpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults() *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults {
	m := &Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateEndpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEndpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewEndpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["_links"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateEndpoint_Test_Results_API_SelfLinksFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLinks(val.(Endpoint_Test_Results_API_SelfLinksable))
		}
		return nil
	}
	res["results"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateEndpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultable)
				}
			}
			m.SetResults(res)
		}
		return nil
	}
	res["test"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateEndpoint_Test_Results_API_DynamicTestFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTest(val.(Endpoint_Test_Results_API_DynamicTestable))
		}
		return nil
	}
	return res
}

// GetLinks gets the _links property value. A links object containing the self link.
// returns a Endpoint_Test_Results_API_SelfLinksable when successful
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) GetLinks() Endpoint_Test_Results_API_SelfLinksable {
	return m.links
}

// GetResults gets the results property value. The results property
// returns a []Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultable when successful
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) GetResults() []Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultable {
	return m.results
}

// GetTest gets the test property value. The test property
// returns a Endpoint_Test_Results_API_DynamicTestable when successful
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) GetTest() Endpoint_Test_Results_API_DynamicTestable {
	return m.test
}

// Serialize serializes information the current object
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetResults() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetResults()))
		for i, v := range m.GetResults() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("results", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("test", m.GetTest())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetLinks sets the _links property value. A links object containing the self link.
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) SetLinks(value Endpoint_Test_Results_API_SelfLinksable) {
	m.links = value
}

// SetResults sets the results property value. The results property
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) SetResults(value []Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultable) {
	m.results = value
}

// SetTest sets the test property value. The test property
func (m *Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResults) SetTest(value Endpoint_Test_Results_API_DynamicTestable) {
	m.test = value
}

type Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultsable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetLinks() Endpoint_Test_Results_API_SelfLinksable
	GetResults() []Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultable
	GetTest() Endpoint_Test_Results_API_DynamicTestable
	SetLinks(value Endpoint_Test_Results_API_SelfLinksable)
	SetResults(value []Endpoint_Test_Results_API_PathVisDetailDynamicEndpointTestResultable)
	SetTest(value Endpoint_Test_Results_API_DynamicTestable)
}
