// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// Type of filter - the data that will be used to filter.
type Endpoint_Agent_Labels_API_FilterType int

const (
	AGENTID_ENDPOINT_AGENT_LABELS_API_FILTERTYPE Endpoint_Agent_Labels_API_FilterType = iota
	PUBLICNETWORK_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	LOCALNETWORK_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	CONNECTION_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	GATEWAY_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	PLATFORM_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	AGENTTYPE_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	VPNVENDOR_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	VPNGATEWAYADDRESS_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	VPNCLIENTNETWORK_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	VPNCLIENTADDRESS_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	IPADDRESSFAMILY_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	SSID_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	BSSID_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	HOSTNAME_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	USERNAME_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	ASN_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
)

func (i Endpoint_Agent_Labels_API_FilterType) String() string {
	return []string{"agent-id", "public-network", "local-network", "connection", "gateway", "platform", "agent-type", "vpn-vendor", "vpn-gateway-address", "vpn-client-network", "vpn-client-address", "ip-address-family", "ssid", "bssid", "hostname", "username", "asn"}[i]
}

func ParseEndpoint_Agent_Labels_API_FilterType(v string) (any, error) {
	result := AGENTID_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	switch v {
	case "agent-id":
		result = AGENTID_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "public-network":
		result = PUBLICNETWORK_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "local-network":
		result = LOCALNETWORK_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "connection":
		result = CONNECTION_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "gateway":
		result = GATEWAY_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "platform":
		result = PLATFORM_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "agent-type":
		result = AGENTTYPE_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "vpn-vendor":
		result = VPNVENDOR_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "vpn-gateway-address":
		result = VPNGATEWAYADDRESS_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "vpn-client-network":
		result = VPNCLIENTNETWORK_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "vpn-client-address":
		result = VPNCLIENTADDRESS_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "ip-address-family":
		result = IPADDRESSFAMILY_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "ssid":
		result = SSID_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "bssid":
		result = BSSID_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "hostname":
		result = HOSTNAME_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "username":
		result = USERNAME_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	case "asn":
		result = ASN_ENDPOINT_AGENT_LABELS_API_FILTERTYPE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeEndpoint_Agent_Labels_API_FilterType(values []Endpoint_Agent_Labels_API_FilterType) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Endpoint_Agent_Labels_API_FilterType) isMultiValue() bool {
	return false
}
