// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Endpoint_Agents_API_EndpointAgentLogItemsResponse struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// A links object containing a related link for forward pagination.
	links Endpoint_Agents_API_PaginationNextAndSelfLinkable
	// Log items for the endpoint agent.
	logs []Endpoint_Agents_API_EndpointAgentLogItemable
}

// NewEndpoint_Agents_API_EndpointAgentLogItemsResponse instantiates a new Endpoint_Agents_API_EndpointAgentLogItemsResponse and sets the default values.
func NewEndpoint_Agents_API_EndpointAgentLogItemsResponse() *Endpoint_Agents_API_EndpointAgentLogItemsResponse {
	m := &Endpoint_Agents_API_EndpointAgentLogItemsResponse{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateEndpoint_Agents_API_EndpointAgentLogItemsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEndpoint_Agents_API_EndpointAgentLogItemsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewEndpoint_Agents_API_EndpointAgentLogItemsResponse(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Endpoint_Agents_API_EndpointAgentLogItemsResponse) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Endpoint_Agents_API_EndpointAgentLogItemsResponse) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["_links"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateEndpoint_Agents_API_PaginationNextAndSelfLinkFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLinks(val.(Endpoint_Agents_API_PaginationNextAndSelfLinkable))
		}
		return nil
	}
	res["logs"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateEndpoint_Agents_API_EndpointAgentLogItemFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Endpoint_Agents_API_EndpointAgentLogItemable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Endpoint_Agents_API_EndpointAgentLogItemable)
				}
			}
			m.SetLogs(res)
		}
		return nil
	}
	return res
}

// GetLinks gets the _links property value. A links object containing a related link for forward pagination.
// returns a Endpoint_Agents_API_PaginationNextAndSelfLinkable when successful
func (m *Endpoint_Agents_API_EndpointAgentLogItemsResponse) GetLinks() Endpoint_Agents_API_PaginationNextAndSelfLinkable {
	return m.links
}

// GetLogs gets the logs property value. Log items for the endpoint agent.
// returns a []Endpoint_Agents_API_EndpointAgentLogItemable when successful
func (m *Endpoint_Agents_API_EndpointAgentLogItemsResponse) GetLogs() []Endpoint_Agents_API_EndpointAgentLogItemable {
	return m.logs
}

// Serialize serializes information the current object
func (m *Endpoint_Agents_API_EndpointAgentLogItemsResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteObjectValue("_links", m.GetLinks())
		if err != nil {
			return err
		}
	}
	if m.GetLogs() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetLogs()))
		for i, v := range m.GetLogs() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("logs", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Endpoint_Agents_API_EndpointAgentLogItemsResponse) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetLinks sets the _links property value. A links object containing a related link for forward pagination.
func (m *Endpoint_Agents_API_EndpointAgentLogItemsResponse) SetLinks(value Endpoint_Agents_API_PaginationNextAndSelfLinkable) {
	m.links = value
}

// SetLogs sets the logs property value. Log items for the endpoint agent.
func (m *Endpoint_Agents_API_EndpointAgentLogItemsResponse) SetLogs(value []Endpoint_Agents_API_EndpointAgentLogItemable) {
	m.logs = value
}

type Endpoint_Agents_API_EndpointAgentLogItemsResponseable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetLinks() Endpoint_Agents_API_PaginationNextAndSelfLinkable
	GetLogs() []Endpoint_Agents_API_EndpointAgentLogItemable
	SetLinks(value Endpoint_Agents_API_PaginationNextAndSelfLinkable)
	SetLogs(value []Endpoint_Agents_API_EndpointAgentLogItemable)
}
