// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// Status of the endpoint agent in ThousandEyes. Disabled agents don't report data.
type Endpoint_Agents_API_Status int

const (
	ENABLED_ENDPOINT_AGENTS_API_STATUS Endpoint_Agents_API_Status = iota
	DISABLED_ENDPOINT_AGENTS_API_STATUS
)

func (i Endpoint_Agents_API_Status) String() string {
	return []string{"enabled", "disabled"}[i]
}

func ParseEndpoint_Agents_API_Status(v string) (any, error) {
	result := ENABLED_ENDPOINT_AGENTS_API_STATUS
	switch v {
	case "enabled":
		result = ENABLED_ENDPOINT_AGENTS_API_STATUS
	case "disabled":
		result = DISABLED_ENDPOINT_AGENTS_API_STATUS
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeEndpoint_Agents_API_Status(values []Endpoint_Agents_API_Status) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Endpoint_Agents_API_Status) isMultiValue() bool {
	return false
}
