// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Event_Detection_API_AffectedTests struct {
	Event_Detection_API_AffectedCount
	// List of affected tests.
	tests []Event_Detection_API_EventApiAffectedTestable
}

// NewEvent_Detection_API_AffectedTests instantiates a new Event_Detection_API_AffectedTests and sets the default values.
func NewEvent_Detection_API_AffectedTests() *Event_Detection_API_AffectedTests {
	m := &Event_Detection_API_AffectedTests{
		Event_Detection_API_AffectedCount: *NewEvent_Detection_API_AffectedCount(),
	}
	return m
}

// CreateEvent_Detection_API_AffectedTestsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEvent_Detection_API_AffectedTestsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewEvent_Detection_API_AffectedTests(), nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Event_Detection_API_AffectedTests) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.Event_Detection_API_AffectedCount.GetFieldDeserializers()
	res["tests"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateEvent_Detection_API_EventApiAffectedTestFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Event_Detection_API_EventApiAffectedTestable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Event_Detection_API_EventApiAffectedTestable)
				}
			}
			m.SetTests(res)
		}
		return nil
	}
	return res
}

// GetTests gets the tests property value. List of affected tests.
// returns a []Event_Detection_API_EventApiAffectedTestable when successful
func (m *Event_Detection_API_AffectedTests) GetTests() []Event_Detection_API_EventApiAffectedTestable {
	return m.tests
}

// Serialize serializes information the current object
func (m *Event_Detection_API_AffectedTests) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.Event_Detection_API_AffectedCount.Serialize(writer)
	if err != nil {
		return err
	}
	if m.GetTests() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetTests()))
		for i, v := range m.GetTests() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err = writer.WriteCollectionOfObjectValues("tests", cast)
		if err != nil {
			return err
		}
	}
	return nil
}

// SetTests sets the tests property value. List of affected tests.
func (m *Event_Detection_API_AffectedTests) SetTests(value []Event_Detection_API_EventApiAffectedTestable) {
	m.tests = value
}

type Event_Detection_API_AffectedTestsable interface {
	Event_Detection_API_AffectedCountable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetTests() []Event_Detection_API_EventApiAffectedTestable
	SetTests(value []Event_Detection_API_EventApiAffectedTestable)
}
