// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// Domain class used by this test. 'in' stands for Internet, while 'ch' stands for Chaos.
type Instant_Tests_API_DnsQueryClass int

const (
	IN_INSTANT_TESTS_API_DNSQUERYCLASS Instant_Tests_API_DnsQueryClass = iota
	CH_INSTANT_TESTS_API_DNSQUERYCLASS
)

func (i Instant_Tests_API_DnsQueryClass) String() string {
	return []string{"in", "ch"}[i]
}

func ParseInstant_Tests_API_DnsQueryClass(v string) (any, error) {
	result := IN_INSTANT_TESTS_API_DNSQUERYCLASS
	switch v {
	case "in":
		result = IN_INSTANT_TESTS_API_DNSQUERYCLASS
	case "ch":
		result = CH_INSTANT_TESTS_API_DNSQUERYCLASS
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeInstant_Tests_API_DnsQueryClass(values []Instant_Tests_API_DnsQueryClass) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Instant_Tests_API_DnsQueryClass) isMultiValue() bool {
	return false
}
