// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// The target setting that the credential should be used for.
type Instant_Tests_API_TestVaultCredentialTarget int

const (
	USERNAME_INSTANT_TESTS_API_TESTVAULTCREDENTIALTARGET Instant_Tests_API_TestVaultCredentialTarget = iota
	PASSWORD_INSTANT_TESTS_API_TESTVAULTCREDENTIALTARGET
	SCRIPT_INSTANT_TESTS_API_TESTVAULTCREDENTIALTARGET
)

func (i Instant_Tests_API_TestVaultCredentialTarget) String() string {
	return []string{"username", "password", "script"}[i]
}

func ParseInstant_Tests_API_TestVaultCredentialTarget(v string) (any, error) {
	result := USERNAME_INSTANT_TESTS_API_TESTVAULTCREDENTIALTARGET
	switch v {
	case "username":
		result = USERNAME_INSTANT_TESTS_API_TESTVAULTCREDENTIALTARGET
	case "password":
		result = PASSWORD_INSTANT_TESTS_API_TESTVAULTCREDENTIALTARGET
	case "script":
		result = SCRIPT_INSTANT_TESTS_API_TESTVAULTCREDENTIALTARGET
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeInstant_Tests_API_TestVaultCredentialTarget(values []Instant_Tests_API_TestVaultCredentialTarget) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i Instant_Tests_API_TestVaultCredentialTarget) isMultiValue() bool {
	return false
}
