// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Tags_API_BulkTagAssignments struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// A links object containing the self link.
	links Tags_API_SelfLinksable
	// The tags property
	tags []Tags_API_BulkTagAssignmentable
}

// NewTags_API_BulkTagAssignments instantiates a new Tags_API_BulkTagAssignments and sets the default values.
func NewTags_API_BulkTagAssignments() *Tags_API_BulkTagAssignments {
	m := &Tags_API_BulkTagAssignments{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateTags_API_BulkTagAssignmentsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTags_API_BulkTagAssignmentsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewTags_API_BulkTagAssignments(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Tags_API_BulkTagAssignments) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Tags_API_BulkTagAssignments) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["_links"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateTags_API_SelfLinksFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLinks(val.(Tags_API_SelfLinksable))
		}
		return nil
	}
	res["tags"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTags_API_BulkTagAssignmentFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tags_API_BulkTagAssignmentable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tags_API_BulkTagAssignmentable)
				}
			}
			m.SetTags(res)
		}
		return nil
	}
	return res
}

// GetLinks gets the _links property value. A links object containing the self link.
// returns a Tags_API_SelfLinksable when successful
func (m *Tags_API_BulkTagAssignments) GetLinks() Tags_API_SelfLinksable {
	return m.links
}

// GetTags gets the tags property value. The tags property
// returns a []Tags_API_BulkTagAssignmentable when successful
func (m *Tags_API_BulkTagAssignments) GetTags() []Tags_API_BulkTagAssignmentable {
	return m.tags
}

// Serialize serializes information the current object
func (m *Tags_API_BulkTagAssignments) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetTags() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetTags()))
		for i, v := range m.GetTags() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("tags", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Tags_API_BulkTagAssignments) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetLinks sets the _links property value. A links object containing the self link.
func (m *Tags_API_BulkTagAssignments) SetLinks(value Tags_API_SelfLinksable) {
	m.links = value
}

// SetTags sets the tags property value. The tags property
func (m *Tags_API_BulkTagAssignments) SetTags(value []Tags_API_BulkTagAssignmentable) {
	m.tags = value
}

type Tags_API_BulkTagAssignmentsable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetLinks() Tags_API_SelfLinksable
	GetTags() []Tags_API_BulkTagAssignmentable
	SetLinks(value Tags_API_SelfLinksable)
	SetTags(value []Tags_API_BulkTagAssignmentable)
}
