// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Tags_API_Assignment struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Object Id
	id *string
	// The type property
	typeEscaped *Tags_API_AssignmentType
}

// NewTags_API_Assignment instantiates a new Tags_API_Assignment and sets the default values.
func NewTags_API_Assignment() *Tags_API_Assignment {
	m := &Tags_API_Assignment{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateTags_API_AssignmentFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTags_API_AssignmentFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewTags_API_Assignment(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Tags_API_Assignment) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Tags_API_Assignment) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTags_API_AssignmentType)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTypeEscaped(val.(*Tags_API_AssignmentType))
		}
		return nil
	}
	return res
}

// GetId gets the id property value. Object Id
// returns a *string when successful
func (m *Tags_API_Assignment) GetId() *string {
	return m.id
}

// GetTypeEscaped gets the type property value. The type property
// returns a *Tags_API_AssignmentType when successful
func (m *Tags_API_Assignment) GetTypeEscaped() *Tags_API_AssignmentType {
	return m.typeEscaped
}

// Serialize serializes information the current object
func (m *Tags_API_Assignment) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	if m.GetTypeEscaped() != nil {
		cast := (*m.GetTypeEscaped()).String()
		err := writer.WriteStringValue("type", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Tags_API_Assignment) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetId sets the id property value. Object Id
func (m *Tags_API_Assignment) SetId(value *string) {
	m.id = value
}

// SetTypeEscaped sets the type property value. The type property
func (m *Tags_API_Assignment) SetTypeEscaped(value *Tags_API_AssignmentType) {
	m.typeEscaped = value
}

type Tags_API_Assignmentable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetId() *string
	GetTypeEscaped() *Tags_API_AssignmentType
	SetId(value *string)
	SetTypeEscaped(value *Tags_API_AssignmentType)
}
