// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Templates_API_Template_resourceInclusion a map of `<assetKey, ResourceInclusion>` pairs. The `resourceInclusion` field specifies whether an asset (such as a test, endpoint test, label, tag, dashboard, or alert rule) should be included in a deployment.The `assetKey` identifies the specific asset to which the inclusion rule applies.Possible resource inclusion values for each asset:  * `included` - The system will always create the asset.  * `skipped` - The system will not create the asset.If an `assetKey` is not present in the `resourceInclusion` map, it defaults to `included`.**Note**: The deployment payload can override the `resourceInclusion` value defined in a template.
type Templates_API_Template_resourceInclusion struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
}

// NewTemplates_API_Template_resourceInclusion instantiates a new Templates_API_Template_resourceInclusion and sets the default values.
func NewTemplates_API_Template_resourceInclusion() *Templates_API_Template_resourceInclusion {
	m := &Templates_API_Template_resourceInclusion{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateTemplates_API_Template_resourceInclusionFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTemplates_API_Template_resourceInclusionFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewTemplates_API_Template_resourceInclusion(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Templates_API_Template_resourceInclusion) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Templates_API_Template_resourceInclusion) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	return res
}

// Serialize serializes information the current object
func (m *Templates_API_Template_resourceInclusion) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Templates_API_Template_resourceInclusion) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

type Templates_API_Template_resourceInclusionable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
