// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Templates_API_TemplateResponse_dashboardFilters a map of <key, DashboardFilter> objects. These will be the dashboard filters created when the template is deployed.
type Templates_API_TemplateResponse_dashboardFilters struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
}

// NewTemplates_API_TemplateResponse_dashboardFilters instantiates a new Templates_API_TemplateResponse_dashboardFilters and sets the default values.
func NewTemplates_API_TemplateResponse_dashboardFilters() *Templates_API_TemplateResponse_dashboardFilters {
	m := &Templates_API_TemplateResponse_dashboardFilters{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateTemplates_API_TemplateResponse_dashboardFiltersFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTemplates_API_TemplateResponse_dashboardFiltersFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewTemplates_API_TemplateResponse_dashboardFilters(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Templates_API_TemplateResponse_dashboardFilters) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Templates_API_TemplateResponse_dashboardFilters) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	return res
}

// Serialize serializes information the current object
func (m *Templates_API_TemplateResponse_dashboardFilters) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Templates_API_TemplateResponse_dashboardFilters) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

type Templates_API_TemplateResponse_dashboardFiltersable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
