// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"

	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Tests_API_ApiTest struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Contains list of enabled alert rule objects.
	alertRules []Tests_API_AlertRuleable
	// Indicates if alerts are enabled.
	alertsEnabled *bool
	// Set to `true` to enable bgp measurements.
	bgpMeasurements *bool
	// Comma separated list of domains to send the client certificate.
	clientCertDomainsAllowList *string
	// String representation (containing newline characters) of client certificate, the private key must be placed first, then the certificate.
	clientCertificate *string
	// Indicates whether network data to the proxy should be collected.
	collectProxyNetworkData *bool
	// User that created the test.
	createdBy *string
	// UTC created date (ISO date-time format).
	createdDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// Contains a list of credential IDs (get `credentialId` from `/credentials` endpoint).
	credentials []string
	// A description of the test.
	description *string
	// Adds distributed tracing headers to API requests using B3 and W3C standards.
	distributedTracing *bool
	// Test is enabled.
	enabled *bool
	// To disable following HTTP/301 or HTTP/302 redirect directives, set this parameter to `false`.
	followRedirects *bool
	// Interval between test runs in seconds.
	interval *int32
	// Labels to which the test is assigned. This field is not returned for Instant Tests.
	labels []Tests_API_TestLabelable
	// A list of links that can be accessed to get more information
	links Tests_API_TestLinksable
	// Indicates if the test is shared with the account group.
	liveShare *bool
	// User that modified the test.
	modifiedBy *string
	// UTC last modification date (ISO date-time format).
	modifiedDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// Contains list of enabled BGP monitors.
	monitors []Tests_API_Monitorable
	// Set `true` to measure MTU sizes on network from agents to the target.
	mtuMeasurements *bool
	// Enable or disable network measurements. Set to true to enable or false to disable network measurements.
	networkMeasurements *bool
	// Number of path traces executed by the agent.
	numPathTraces *int32
	// Flag indicating if a proxy other than the default should be used. To override the default proxy for agents, set to `true` and specify a value for `overrideProxyId`.
	overrideAgentProxy *bool
	// ID of the proxy to be used if the default proxy is overridden.
	overrideProxyId *string
	// Select `inSession` to perform the path trace within a TCP session.
	pathTraceMode *Tests_API_TestPathTraceMode
	// The predefinedVariables property
	predefinedVariables []Tests_API_ApiPredefinedVariableable
	// Probe mode used by network test, only valid when the protocol is set to TCP.
	probeMode *Tests_API_TestProbeMode
	// Protocol used by dependent network tests (end-to-end, path trace, PMTUD).
	protocol *Tests_API_TestProtocol
	// Indicates whether agents should randomize the start time in each test round.
	randomizedStartTime *bool
	// The requests property
	requests []Tests_API_ApiRequestable
	// Indicates if the test is a saved event.**Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API.
	savedEvent *bool
	// The sharedWithAccounts property
	sharedWithAccounts []Tests_API_SharedWithAccountable
	// SSL version options:* Use '0' for automatic selection.* Use '3' for SSLv3.* Use '4' for TLS v1.0.* Use '5' for TLS v1.1.* Use '6' for TLS v1.2.* Use '7' for TLS v1.3.
	sslVersionId *Tests_API_TestSslVersionId
	// Tags assigned to the test. Returned only when `expand=tag` is specified. This field is not returned for Instant Tests. For more information, see `/tags`.
	tags []Tests_API_TestTagable
	// Target time for completion metric, defaults to 50% of time limit specified in seconds. (0 means default behavior)
	targetTime *int32
	// Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
	testId *string
	// The name of the test. Test name must be unique.
	testName *string
	// Time limit for transaction in seconds. Exceeding this limit will result in a Timeout error.
	timeLimit *int32
	// This is a read only value, as test type is implicit in the test creation url.
	typeEscaped *Tests_API_TestType
	// Target for the test.
	url *string
	// Indicate if all available public BGP monitors should be used, when ommited defaults to `bgpMeasurements` value.
	usePublicBgp *bool
	// List of credential IDs that are stored in an external vault.
	vaultCredentials []Tests_API_TestVaultCredentialable
}

// NewTests_API_ApiTest instantiates a new Tests_API_ApiTest and sets the default values.
func NewTests_API_ApiTest() *Tests_API_ApiTest {
	m := &Tests_API_ApiTest{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateTests_API_ApiTestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTests_API_ApiTestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewTests_API_ApiTest(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Tests_API_ApiTest) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAlertRules gets the alertRules property value. Contains list of enabled alert rule objects.
// returns a []Tests_API_AlertRuleable when successful
func (m *Tests_API_ApiTest) GetAlertRules() []Tests_API_AlertRuleable {
	return m.alertRules
}

// GetAlertsEnabled gets the alertsEnabled property value. Indicates if alerts are enabled.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetAlertsEnabled() *bool {
	return m.alertsEnabled
}

// GetBgpMeasurements gets the bgpMeasurements property value. Set to `true` to enable bgp measurements.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetBgpMeasurements() *bool {
	return m.bgpMeasurements
}

// GetClientCertDomainsAllowList gets the clientCertDomainsAllowList property value. Comma separated list of domains to send the client certificate.
// returns a *string when successful
func (m *Tests_API_ApiTest) GetClientCertDomainsAllowList() *string {
	return m.clientCertDomainsAllowList
}

// GetClientCertificate gets the clientCertificate property value. String representation (containing newline characters) of client certificate, the private key must be placed first, then the certificate.
// returns a *string when successful
func (m *Tests_API_ApiTest) GetClientCertificate() *string {
	return m.clientCertificate
}

// GetCollectProxyNetworkData gets the collectProxyNetworkData property value. Indicates whether network data to the proxy should be collected.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetCollectProxyNetworkData() *bool {
	return m.collectProxyNetworkData
}

// GetCreatedBy gets the createdBy property value. User that created the test.
// returns a *string when successful
func (m *Tests_API_ApiTest) GetCreatedBy() *string {
	return m.createdBy
}

// GetCreatedDate gets the createdDate property value. UTC created date (ISO date-time format).
// returns a *Time when successful
func (m *Tests_API_ApiTest) GetCreatedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.createdDate
}

// GetCredentials gets the credentials property value. Contains a list of credential IDs (get `credentialId` from `/credentials` endpoint).
// returns a []string when successful
func (m *Tests_API_ApiTest) GetCredentials() []string {
	return m.credentials
}

// GetDescription gets the description property value. A description of the test.
// returns a *string when successful
func (m *Tests_API_ApiTest) GetDescription() *string {
	return m.description
}

// GetDistributedTracing gets the distributedTracing property value. Adds distributed tracing headers to API requests using B3 and W3C standards.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetDistributedTracing() *bool {
	return m.distributedTracing
}

// GetEnabled gets the enabled property value. Test is enabled.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetEnabled() *bool {
	return m.enabled
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Tests_API_ApiTest) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["alertRules"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTests_API_AlertRuleFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tests_API_AlertRuleable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tests_API_AlertRuleable)
				}
			}
			m.SetAlertRules(res)
		}
		return nil
	}
	res["alertsEnabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAlertsEnabled(val)
		}
		return nil
	}
	res["bgpMeasurements"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetBgpMeasurements(val)
		}
		return nil
	}
	res["clientCertDomainsAllowList"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetClientCertDomainsAllowList(val)
		}
		return nil
	}
	res["clientCertificate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetClientCertificate(val)
		}
		return nil
	}
	res["collectProxyNetworkData"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCollectProxyNetworkData(val)
		}
		return nil
	}
	res["createdBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedBy(val)
		}
		return nil
	}
	res["createdDate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedDate(val)
		}
		return nil
	}
	res["credentials"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetCredentials(res)
		}
		return nil
	}
	res["description"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDescription(val)
		}
		return nil
	}
	res["distributedTracing"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDistributedTracing(val)
		}
		return nil
	}
	res["enabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEnabled(val)
		}
		return nil
	}
	res["followRedirects"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFollowRedirects(val)
		}
		return nil
	}
	res["interval"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetInterval(val)
		}
		return nil
	}
	res["labels"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTests_API_TestLabelFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tests_API_TestLabelable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tests_API_TestLabelable)
				}
			}
			m.SetLabels(res)
		}
		return nil
	}
	res["_links"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateTests_API_TestLinksFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLinks(val.(Tests_API_TestLinksable))
		}
		return nil
	}
	res["liveShare"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLiveShare(val)
		}
		return nil
	}
	res["modifiedBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedBy(val)
		}
		return nil
	}
	res["modifiedDate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedDate(val)
		}
		return nil
	}
	res["monitors"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTests_API_MonitorFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tests_API_Monitorable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tests_API_Monitorable)
				}
			}
			m.SetMonitors(res)
		}
		return nil
	}
	res["mtuMeasurements"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMtuMeasurements(val)
		}
		return nil
	}
	res["networkMeasurements"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNetworkMeasurements(val)
		}
		return nil
	}
	res["numPathTraces"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNumPathTraces(val)
		}
		return nil
	}
	res["overrideAgentProxy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetOverrideAgentProxy(val)
		}
		return nil
	}
	res["overrideProxyId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetOverrideProxyId(val)
		}
		return nil
	}
	res["pathTraceMode"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_TestPathTraceMode)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPathTraceMode(val.(*Tests_API_TestPathTraceMode))
		}
		return nil
	}
	res["predefinedVariables"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTests_API_ApiPredefinedVariableFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tests_API_ApiPredefinedVariableable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tests_API_ApiPredefinedVariableable)
				}
			}
			m.SetPredefinedVariables(res)
		}
		return nil
	}
	res["probeMode"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_TestProbeMode)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProbeMode(val.(*Tests_API_TestProbeMode))
		}
		return nil
	}
	res["protocol"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_TestProtocol)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProtocol(val.(*Tests_API_TestProtocol))
		}
		return nil
	}
	res["randomizedStartTime"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRandomizedStartTime(val)
		}
		return nil
	}
	res["requests"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTests_API_ApiRequestFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tests_API_ApiRequestable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tests_API_ApiRequestable)
				}
			}
			m.SetRequests(res)
		}
		return nil
	}
	res["savedEvent"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSavedEvent(val)
		}
		return nil
	}
	res["sharedWithAccounts"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTests_API_SharedWithAccountFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tests_API_SharedWithAccountable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tests_API_SharedWithAccountable)
				}
			}
			m.SetSharedWithAccounts(res)
		}
		return nil
	}
	res["sslVersionId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_TestSslVersionId)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSslVersionId(val.(*Tests_API_TestSslVersionId))
		}
		return nil
	}
	res["tags"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTests_API_TestTagFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tests_API_TestTagable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tests_API_TestTagable)
				}
			}
			m.SetTags(res)
		}
		return nil
	}
	res["targetTime"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTargetTime(val)
		}
		return nil
	}
	res["testId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTestId(val)
		}
		return nil
	}
	res["testName"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTestName(val)
		}
		return nil
	}
	res["timeLimit"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTimeLimit(val)
		}
		return nil
	}
	res["type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_TestType)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTypeEscaped(val.(*Tests_API_TestType))
		}
		return nil
	}
	res["url"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUrl(val)
		}
		return nil
	}
	res["usePublicBgp"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUsePublicBgp(val)
		}
		return nil
	}
	res["vaultCredentials"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTests_API_TestVaultCredentialFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tests_API_TestVaultCredentialable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tests_API_TestVaultCredentialable)
				}
			}
			m.SetVaultCredentials(res)
		}
		return nil
	}
	return res
}

// GetFollowRedirects gets the followRedirects property value. To disable following HTTP/301 or HTTP/302 redirect directives, set this parameter to `false`.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetFollowRedirects() *bool {
	return m.followRedirects
}

// GetInterval gets the interval property value. Interval between test runs in seconds.
// returns a *int32 when successful
func (m *Tests_API_ApiTest) GetInterval() *int32 {
	return m.interval
}

// GetLabels gets the labels property value. Labels to which the test is assigned. This field is not returned for Instant Tests.
// returns a []Tests_API_TestLabelable when successful
func (m *Tests_API_ApiTest) GetLabels() []Tests_API_TestLabelable {
	return m.labels
}

// GetLinks gets the _links property value. A list of links that can be accessed to get more information
// returns a Tests_API_TestLinksable when successful
func (m *Tests_API_ApiTest) GetLinks() Tests_API_TestLinksable {
	return m.links
}

// GetLiveShare gets the liveShare property value. Indicates if the test is shared with the account group.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetLiveShare() *bool {
	return m.liveShare
}

// GetModifiedBy gets the modifiedBy property value. User that modified the test.
// returns a *string when successful
func (m *Tests_API_ApiTest) GetModifiedBy() *string {
	return m.modifiedBy
}

// GetModifiedDate gets the modifiedDate property value. UTC last modification date (ISO date-time format).
// returns a *Time when successful
func (m *Tests_API_ApiTest) GetModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.modifiedDate
}

// GetMonitors gets the monitors property value. Contains list of enabled BGP monitors.
// returns a []Tests_API_Monitorable when successful
func (m *Tests_API_ApiTest) GetMonitors() []Tests_API_Monitorable {
	return m.monitors
}

// GetMtuMeasurements gets the mtuMeasurements property value. Set `true` to measure MTU sizes on network from agents to the target.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetMtuMeasurements() *bool {
	return m.mtuMeasurements
}

// GetNetworkMeasurements gets the networkMeasurements property value. Enable or disable network measurements. Set to true to enable or false to disable network measurements.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetNetworkMeasurements() *bool {
	return m.networkMeasurements
}

// GetNumPathTraces gets the numPathTraces property value. Number of path traces executed by the agent.
// returns a *int32 when successful
func (m *Tests_API_ApiTest) GetNumPathTraces() *int32 {
	return m.numPathTraces
}

// GetOverrideAgentProxy gets the overrideAgentProxy property value. Flag indicating if a proxy other than the default should be used. To override the default proxy for agents, set to `true` and specify a value for `overrideProxyId`.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetOverrideAgentProxy() *bool {
	return m.overrideAgentProxy
}

// GetOverrideProxyId gets the overrideProxyId property value. ID of the proxy to be used if the default proxy is overridden.
// returns a *string when successful
func (m *Tests_API_ApiTest) GetOverrideProxyId() *string {
	return m.overrideProxyId
}

// GetPathTraceMode gets the pathTraceMode property value. Select `inSession` to perform the path trace within a TCP session.
// returns a *Tests_API_TestPathTraceMode when successful
func (m *Tests_API_ApiTest) GetPathTraceMode() *Tests_API_TestPathTraceMode {
	return m.pathTraceMode
}

// GetPredefinedVariables gets the predefinedVariables property value. The predefinedVariables property
// returns a []Tests_API_ApiPredefinedVariableable when successful
func (m *Tests_API_ApiTest) GetPredefinedVariables() []Tests_API_ApiPredefinedVariableable {
	return m.predefinedVariables
}

// GetProbeMode gets the probeMode property value. Probe mode used by network test, only valid when the protocol is set to TCP.
// returns a *Tests_API_TestProbeMode when successful
func (m *Tests_API_ApiTest) GetProbeMode() *Tests_API_TestProbeMode {
	return m.probeMode
}

// GetProtocol gets the protocol property value. Protocol used by dependent network tests (end-to-end, path trace, PMTUD).
// returns a *Tests_API_TestProtocol when successful
func (m *Tests_API_ApiTest) GetProtocol() *Tests_API_TestProtocol {
	return m.protocol
}

// GetRandomizedStartTime gets the randomizedStartTime property value. Indicates whether agents should randomize the start time in each test round.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetRandomizedStartTime() *bool {
	return m.randomizedStartTime
}

// GetRequests gets the requests property value. The requests property
// returns a []Tests_API_ApiRequestable when successful
func (m *Tests_API_ApiTest) GetRequests() []Tests_API_ApiRequestable {
	return m.requests
}

// GetSavedEvent gets the savedEvent property value. Indicates if the test is a saved event.**Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetSavedEvent() *bool {
	return m.savedEvent
}

// GetSharedWithAccounts gets the sharedWithAccounts property value. The sharedWithAccounts property
// returns a []Tests_API_SharedWithAccountable when successful
func (m *Tests_API_ApiTest) GetSharedWithAccounts() []Tests_API_SharedWithAccountable {
	return m.sharedWithAccounts
}

// GetSslVersionId gets the sslVersionId property value. SSL version options:* Use '0' for automatic selection.* Use '3' for SSLv3.* Use '4' for TLS v1.0.* Use '5' for TLS v1.1.* Use '6' for TLS v1.2.* Use '7' for TLS v1.3.
// returns a *Tests_API_TestSslVersionId when successful
func (m *Tests_API_ApiTest) GetSslVersionId() *Tests_API_TestSslVersionId {
	return m.sslVersionId
}

// GetTags gets the tags property value. Tags assigned to the test. Returned only when `expand=tag` is specified. This field is not returned for Instant Tests. For more information, see `/tags`.
// returns a []Tests_API_TestTagable when successful
func (m *Tests_API_ApiTest) GetTags() []Tests_API_TestTagable {
	return m.tags
}

// GetTargetTime gets the targetTime property value. Target time for completion metric, defaults to 50% of time limit specified in seconds. (0 means default behavior)
// returns a *int32 when successful
func (m *Tests_API_ApiTest) GetTargetTime() *int32 {
	return m.targetTime
}

// GetTestId gets the testId property value. Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
// returns a *string when successful
func (m *Tests_API_ApiTest) GetTestId() *string {
	return m.testId
}

// GetTestName gets the testName property value. The name of the test. Test name must be unique.
// returns a *string when successful
func (m *Tests_API_ApiTest) GetTestName() *string {
	return m.testName
}

// GetTimeLimit gets the timeLimit property value. Time limit for transaction in seconds. Exceeding this limit will result in a Timeout error.
// returns a *int32 when successful
func (m *Tests_API_ApiTest) GetTimeLimit() *int32 {
	return m.timeLimit
}

// GetTypeEscaped gets the type property value. This is a read only value, as test type is implicit in the test creation url.
// returns a *Tests_API_TestType when successful
func (m *Tests_API_ApiTest) GetTypeEscaped() *Tests_API_TestType {
	return m.typeEscaped
}

// GetUrl gets the url property value. Target for the test.
// returns a *string when successful
func (m *Tests_API_ApiTest) GetUrl() *string {
	return m.url
}

// GetUsePublicBgp gets the usePublicBgp property value. Indicate if all available public BGP monitors should be used, when ommited defaults to `bgpMeasurements` value.
// returns a *bool when successful
func (m *Tests_API_ApiTest) GetUsePublicBgp() *bool {
	return m.usePublicBgp
}

// GetVaultCredentials gets the vaultCredentials property value. List of credential IDs that are stored in an external vault.
// returns a []Tests_API_TestVaultCredentialable when successful
func (m *Tests_API_ApiTest) GetVaultCredentials() []Tests_API_TestVaultCredentialable {
	return m.vaultCredentials
}

// Serialize serializes information the current object
func (m *Tests_API_ApiTest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetAlertRules() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetAlertRules()))
		for i, v := range m.GetAlertRules() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("alertRules", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("alertsEnabled", m.GetAlertsEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("bgpMeasurements", m.GetBgpMeasurements())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("clientCertDomainsAllowList", m.GetClientCertDomainsAllowList())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("clientCertificate", m.GetClientCertificate())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("collectProxyNetworkData", m.GetCollectProxyNetworkData())
		if err != nil {
			return err
		}
	}
	if m.GetCredentials() != nil {
		err := writer.WriteCollectionOfStringValues("credentials", m.GetCredentials())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("description", m.GetDescription())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("distributedTracing", m.GetDistributedTracing())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("enabled", m.GetEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("followRedirects", m.GetFollowRedirects())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("interval", m.GetInterval())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("mtuMeasurements", m.GetMtuMeasurements())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("networkMeasurements", m.GetNetworkMeasurements())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("numPathTraces", m.GetNumPathTraces())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("overrideAgentProxy", m.GetOverrideAgentProxy())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("overrideProxyId", m.GetOverrideProxyId())
		if err != nil {
			return err
		}
	}
	if m.GetPathTraceMode() != nil {
		cast := (*m.GetPathTraceMode()).String()
		err := writer.WriteStringValue("pathTraceMode", &cast)
		if err != nil {
			return err
		}
	}
	if m.GetPredefinedVariables() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetPredefinedVariables()))
		for i, v := range m.GetPredefinedVariables() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("predefinedVariables", cast)
		if err != nil {
			return err
		}
	}
	if m.GetProbeMode() != nil {
		cast := (*m.GetProbeMode()).String()
		err := writer.WriteStringValue("probeMode", &cast)
		if err != nil {
			return err
		}
	}
	if m.GetProtocol() != nil {
		cast := (*m.GetProtocol()).String()
		err := writer.WriteStringValue("protocol", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("randomizedStartTime", m.GetRandomizedStartTime())
		if err != nil {
			return err
		}
	}
	if m.GetRequests() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetRequests()))
		for i, v := range m.GetRequests() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("requests", cast)
		if err != nil {
			return err
		}
	}
	if m.GetSslVersionId() != nil {
		cast := (*m.GetSslVersionId()).String()
		err := writer.WriteStringValue("sslVersionId", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("targetTime", m.GetTargetTime())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("testName", m.GetTestName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("timeLimit", m.GetTimeLimit())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("url", m.GetUrl())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("usePublicBgp", m.GetUsePublicBgp())
		if err != nil {
			return err
		}
	}
	if m.GetVaultCredentials() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetVaultCredentials()))
		for i, v := range m.GetVaultCredentials() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("vaultCredentials", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Tests_API_ApiTest) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAlertRules sets the alertRules property value. Contains list of enabled alert rule objects.
func (m *Tests_API_ApiTest) SetAlertRules(value []Tests_API_AlertRuleable) {
	m.alertRules = value
}

// SetAlertsEnabled sets the alertsEnabled property value. Indicates if alerts are enabled.
func (m *Tests_API_ApiTest) SetAlertsEnabled(value *bool) {
	m.alertsEnabled = value
}

// SetBgpMeasurements sets the bgpMeasurements property value. Set to `true` to enable bgp measurements.
func (m *Tests_API_ApiTest) SetBgpMeasurements(value *bool) {
	m.bgpMeasurements = value
}

// SetClientCertDomainsAllowList sets the clientCertDomainsAllowList property value. Comma separated list of domains to send the client certificate.
func (m *Tests_API_ApiTest) SetClientCertDomainsAllowList(value *string) {
	m.clientCertDomainsAllowList = value
}

// SetClientCertificate sets the clientCertificate property value. String representation (containing newline characters) of client certificate, the private key must be placed first, then the certificate.
func (m *Tests_API_ApiTest) SetClientCertificate(value *string) {
	m.clientCertificate = value
}

// SetCollectProxyNetworkData sets the collectProxyNetworkData property value. Indicates whether network data to the proxy should be collected.
func (m *Tests_API_ApiTest) SetCollectProxyNetworkData(value *bool) {
	m.collectProxyNetworkData = value
}

// SetCreatedBy sets the createdBy property value. User that created the test.
func (m *Tests_API_ApiTest) SetCreatedBy(value *string) {
	m.createdBy = value
}

// SetCreatedDate sets the createdDate property value. UTC created date (ISO date-time format).
func (m *Tests_API_ApiTest) SetCreatedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.createdDate = value
}

// SetCredentials sets the credentials property value. Contains a list of credential IDs (get `credentialId` from `/credentials` endpoint).
func (m *Tests_API_ApiTest) SetCredentials(value []string) {
	m.credentials = value
}

// SetDescription sets the description property value. A description of the test.
func (m *Tests_API_ApiTest) SetDescription(value *string) {
	m.description = value
}

// SetDistributedTracing sets the distributedTracing property value. Adds distributed tracing headers to API requests using B3 and W3C standards.
func (m *Tests_API_ApiTest) SetDistributedTracing(value *bool) {
	m.distributedTracing = value
}

// SetEnabled sets the enabled property value. Test is enabled.
func (m *Tests_API_ApiTest) SetEnabled(value *bool) {
	m.enabled = value
}

// SetFollowRedirects sets the followRedirects property value. To disable following HTTP/301 or HTTP/302 redirect directives, set this parameter to `false`.
func (m *Tests_API_ApiTest) SetFollowRedirects(value *bool) {
	m.followRedirects = value
}

// SetInterval sets the interval property value. Interval between test runs in seconds.
func (m *Tests_API_ApiTest) SetInterval(value *int32) {
	m.interval = value
}

// SetLabels sets the labels property value. Labels to which the test is assigned. This field is not returned for Instant Tests.
func (m *Tests_API_ApiTest) SetLabels(value []Tests_API_TestLabelable) {
	m.labels = value
}

// SetLinks sets the _links property value. A list of links that can be accessed to get more information
func (m *Tests_API_ApiTest) SetLinks(value Tests_API_TestLinksable) {
	m.links = value
}

// SetLiveShare sets the liveShare property value. Indicates if the test is shared with the account group.
func (m *Tests_API_ApiTest) SetLiveShare(value *bool) {
	m.liveShare = value
}

// SetModifiedBy sets the modifiedBy property value. User that modified the test.
func (m *Tests_API_ApiTest) SetModifiedBy(value *string) {
	m.modifiedBy = value
}

// SetModifiedDate sets the modifiedDate property value. UTC last modification date (ISO date-time format).
func (m *Tests_API_ApiTest) SetModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.modifiedDate = value
}

// SetMonitors sets the monitors property value. Contains list of enabled BGP monitors.
func (m *Tests_API_ApiTest) SetMonitors(value []Tests_API_Monitorable) {
	m.monitors = value
}

// SetMtuMeasurements sets the mtuMeasurements property value. Set `true` to measure MTU sizes on network from agents to the target.
func (m *Tests_API_ApiTest) SetMtuMeasurements(value *bool) {
	m.mtuMeasurements = value
}

// SetNetworkMeasurements sets the networkMeasurements property value. Enable or disable network measurements. Set to true to enable or false to disable network measurements.
func (m *Tests_API_ApiTest) SetNetworkMeasurements(value *bool) {
	m.networkMeasurements = value
}

// SetNumPathTraces sets the numPathTraces property value. Number of path traces executed by the agent.
func (m *Tests_API_ApiTest) SetNumPathTraces(value *int32) {
	m.numPathTraces = value
}

// SetOverrideAgentProxy sets the overrideAgentProxy property value. Flag indicating if a proxy other than the default should be used. To override the default proxy for agents, set to `true` and specify a value for `overrideProxyId`.
func (m *Tests_API_ApiTest) SetOverrideAgentProxy(value *bool) {
	m.overrideAgentProxy = value
}

// SetOverrideProxyId sets the overrideProxyId property value. ID of the proxy to be used if the default proxy is overridden.
func (m *Tests_API_ApiTest) SetOverrideProxyId(value *string) {
	m.overrideProxyId = value
}

// SetPathTraceMode sets the pathTraceMode property value. Select `inSession` to perform the path trace within a TCP session.
func (m *Tests_API_ApiTest) SetPathTraceMode(value *Tests_API_TestPathTraceMode) {
	m.pathTraceMode = value
}

// SetPredefinedVariables sets the predefinedVariables property value. The predefinedVariables property
func (m *Tests_API_ApiTest) SetPredefinedVariables(value []Tests_API_ApiPredefinedVariableable) {
	m.predefinedVariables = value
}

// SetProbeMode sets the probeMode property value. Probe mode used by network test, only valid when the protocol is set to TCP.
func (m *Tests_API_ApiTest) SetProbeMode(value *Tests_API_TestProbeMode) {
	m.probeMode = value
}

// SetProtocol sets the protocol property value. Protocol used by dependent network tests (end-to-end, path trace, PMTUD).
func (m *Tests_API_ApiTest) SetProtocol(value *Tests_API_TestProtocol) {
	m.protocol = value
}

// SetRandomizedStartTime sets the randomizedStartTime property value. Indicates whether agents should randomize the start time in each test round.
func (m *Tests_API_ApiTest) SetRandomizedStartTime(value *bool) {
	m.randomizedStartTime = value
}

// SetRequests sets the requests property value. The requests property
func (m *Tests_API_ApiTest) SetRequests(value []Tests_API_ApiRequestable) {
	m.requests = value
}

// SetSavedEvent sets the savedEvent property value. Indicates if the test is a saved event.**Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API.
func (m *Tests_API_ApiTest) SetSavedEvent(value *bool) {
	m.savedEvent = value
}

// SetSharedWithAccounts sets the sharedWithAccounts property value. The sharedWithAccounts property
func (m *Tests_API_ApiTest) SetSharedWithAccounts(value []Tests_API_SharedWithAccountable) {
	m.sharedWithAccounts = value
}

// SetSslVersionId sets the sslVersionId property value. SSL version options:* Use '0' for automatic selection.* Use '3' for SSLv3.* Use '4' for TLS v1.0.* Use '5' for TLS v1.1.* Use '6' for TLS v1.2.* Use '7' for TLS v1.3.
func (m *Tests_API_ApiTest) SetSslVersionId(value *Tests_API_TestSslVersionId) {
	m.sslVersionId = value
}

// SetTags sets the tags property value. Tags assigned to the test. Returned only when `expand=tag` is specified. This field is not returned for Instant Tests. For more information, see `/tags`.
func (m *Tests_API_ApiTest) SetTags(value []Tests_API_TestTagable) {
	m.tags = value
}

// SetTargetTime sets the targetTime property value. Target time for completion metric, defaults to 50% of time limit specified in seconds. (0 means default behavior)
func (m *Tests_API_ApiTest) SetTargetTime(value *int32) {
	m.targetTime = value
}

// SetTestId sets the testId property value. Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
func (m *Tests_API_ApiTest) SetTestId(value *string) {
	m.testId = value
}

// SetTestName sets the testName property value. The name of the test. Test name must be unique.
func (m *Tests_API_ApiTest) SetTestName(value *string) {
	m.testName = value
}

// SetTimeLimit sets the timeLimit property value. Time limit for transaction in seconds. Exceeding this limit will result in a Timeout error.
func (m *Tests_API_ApiTest) SetTimeLimit(value *int32) {
	m.timeLimit = value
}

// SetTypeEscaped sets the type property value. This is a read only value, as test type is implicit in the test creation url.
func (m *Tests_API_ApiTest) SetTypeEscaped(value *Tests_API_TestType) {
	m.typeEscaped = value
}

// SetUrl sets the url property value. Target for the test.
func (m *Tests_API_ApiTest) SetUrl(value *string) {
	m.url = value
}

// SetUsePublicBgp sets the usePublicBgp property value. Indicate if all available public BGP monitors should be used, when ommited defaults to `bgpMeasurements` value.
func (m *Tests_API_ApiTest) SetUsePublicBgp(value *bool) {
	m.usePublicBgp = value
}

// SetVaultCredentials sets the vaultCredentials property value. List of credential IDs that are stored in an external vault.
func (m *Tests_API_ApiTest) SetVaultCredentials(value []Tests_API_TestVaultCredentialable) {
	m.vaultCredentials = value
}

type Tests_API_ApiTestable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAlertRules() []Tests_API_AlertRuleable
	GetAlertsEnabled() *bool
	GetBgpMeasurements() *bool
	GetClientCertDomainsAllowList() *string
	GetClientCertificate() *string
	GetCollectProxyNetworkData() *bool
	GetCreatedBy() *string
	GetCreatedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetCredentials() []string
	GetDescription() *string
	GetDistributedTracing() *bool
	GetEnabled() *bool
	GetFollowRedirects() *bool
	GetInterval() *int32
	GetLabels() []Tests_API_TestLabelable
	GetLinks() Tests_API_TestLinksable
	GetLiveShare() *bool
	GetModifiedBy() *string
	GetModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetMonitors() []Tests_API_Monitorable
	GetMtuMeasurements() *bool
	GetNetworkMeasurements() *bool
	GetNumPathTraces() *int32
	GetOverrideAgentProxy() *bool
	GetOverrideProxyId() *string
	GetPathTraceMode() *Tests_API_TestPathTraceMode
	GetPredefinedVariables() []Tests_API_ApiPredefinedVariableable
	GetProbeMode() *Tests_API_TestProbeMode
	GetProtocol() *Tests_API_TestProtocol
	GetRandomizedStartTime() *bool
	GetRequests() []Tests_API_ApiRequestable
	GetSavedEvent() *bool
	GetSharedWithAccounts() []Tests_API_SharedWithAccountable
	GetSslVersionId() *Tests_API_TestSslVersionId
	GetTags() []Tests_API_TestTagable
	GetTargetTime() *int32
	GetTestId() *string
	GetTestName() *string
	GetTimeLimit() *int32
	GetTypeEscaped() *Tests_API_TestType
	GetUrl() *string
	GetUsePublicBgp() *bool
	GetVaultCredentials() []Tests_API_TestVaultCredentialable
	SetAlertRules(value []Tests_API_AlertRuleable)
	SetAlertsEnabled(value *bool)
	SetBgpMeasurements(value *bool)
	SetClientCertDomainsAllowList(value *string)
	SetClientCertificate(value *string)
	SetCollectProxyNetworkData(value *bool)
	SetCreatedBy(value *string)
	SetCreatedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetCredentials(value []string)
	SetDescription(value *string)
	SetDistributedTracing(value *bool)
	SetEnabled(value *bool)
	SetFollowRedirects(value *bool)
	SetInterval(value *int32)
	SetLabels(value []Tests_API_TestLabelable)
	SetLinks(value Tests_API_TestLinksable)
	SetLiveShare(value *bool)
	SetModifiedBy(value *string)
	SetModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetMonitors(value []Tests_API_Monitorable)
	SetMtuMeasurements(value *bool)
	SetNetworkMeasurements(value *bool)
	SetNumPathTraces(value *int32)
	SetOverrideAgentProxy(value *bool)
	SetOverrideProxyId(value *string)
	SetPathTraceMode(value *Tests_API_TestPathTraceMode)
	SetPredefinedVariables(value []Tests_API_ApiPredefinedVariableable)
	SetProbeMode(value *Tests_API_TestProbeMode)
	SetProtocol(value *Tests_API_TestProtocol)
	SetRandomizedStartTime(value *bool)
	SetRequests(value []Tests_API_ApiRequestable)
	SetSavedEvent(value *bool)
	SetSharedWithAccounts(value []Tests_API_SharedWithAccountable)
	SetSslVersionId(value *Tests_API_TestSslVersionId)
	SetTags(value []Tests_API_TestTagable)
	SetTargetTime(value *int32)
	SetTestId(value *string)
	SetTestName(value *string)
	SetTimeLimit(value *int32)
	SetTypeEscaped(value *Tests_API_TestType)
	SetUrl(value *string)
	SetUsePublicBgp(value *bool)
	SetVaultCredentials(value []Tests_API_TestVaultCredentialable)
}
