// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"

	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Tests_API_DnsSecTestRequest struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Contains list of Agent IDs (get `agentId` from `/agents` endpoint).
	agents []Tests_API_TestAgentRequestable
	// List of alert rules IDs to apply to the test (get `ruleId` from `/alerts/rules` endpoint. If `alertsEnabled` is set to `true` and `alertRules` is not included on test creation or update, applicable user default alert rules will be used)
	alertRules []string
	// Indicates if alerts are enabled.
	alertsEnabled *bool
	// User that created the test.
	createdBy *string
	// UTC created date (ISO date-time format).
	createdDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// A description of the test.
	description *string
	// Domain class used by this test. 'in' stands for Internet, while 'ch' stands for Chaos.
	dnsQueryClass *Tests_API_DnsQueryClass
	// The target record for the test, with the record type suffixed. If no record type is specified, the test defaults to an ANY record.
	domain *string
	// Test is enabled.
	enabled *bool
	// Interval between test runs in seconds.
	interval *int32
	// Contains list of test label IDs (get `labelId` from `/labels` endpoint)
	labels []string
	// A list of links that can be accessed to get more information
	links Tests_API_TestLinksable
	// Indicates if the test is shared with the account group.
	liveShare *bool
	// User that modified the test.
	modifiedBy *string
	// UTC last modification date (ISO date-time format).
	modifiedDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// Indicates whether agents should randomize the start time in each test round.
	randomizedStartTime *bool
	// Indicates if the test is a saved event.**Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API.
	savedEvent *bool
	// Contains list of account group IDs. Test is shared with the listed account groups (get `aid` from `/account-groups` endpoint)
	sharedWithAccounts []string
	// Contains list of test tag IDs (get `id` from `/tags` endpoint).
	tags []string
	// Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
	testId *string
	// The name of the test. Test name must be unique.
	testName *string
	// This is a read only value, as test type is implicit in the test creation url.
	typeEscaped *Tests_API_TestType
}

// NewTests_API_DnsSecTestRequest instantiates a new Tests_API_DnsSecTestRequest and sets the default values.
func NewTests_API_DnsSecTestRequest() *Tests_API_DnsSecTestRequest {
	m := &Tests_API_DnsSecTestRequest{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateTests_API_DnsSecTestRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTests_API_DnsSecTestRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewTests_API_DnsSecTestRequest(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Tests_API_DnsSecTestRequest) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAgents gets the agents property value. Contains list of Agent IDs (get `agentId` from `/agents` endpoint).
// returns a []Tests_API_TestAgentRequestable when successful
func (m *Tests_API_DnsSecTestRequest) GetAgents() []Tests_API_TestAgentRequestable {
	return m.agents
}

// GetAlertRules gets the alertRules property value. List of alert rules IDs to apply to the test (get `ruleId` from `/alerts/rules` endpoint. If `alertsEnabled` is set to `true` and `alertRules` is not included on test creation or update, applicable user default alert rules will be used)
// returns a []string when successful
func (m *Tests_API_DnsSecTestRequest) GetAlertRules() []string {
	return m.alertRules
}

// GetAlertsEnabled gets the alertsEnabled property value. Indicates if alerts are enabled.
// returns a *bool when successful
func (m *Tests_API_DnsSecTestRequest) GetAlertsEnabled() *bool {
	return m.alertsEnabled
}

// GetCreatedBy gets the createdBy property value. User that created the test.
// returns a *string when successful
func (m *Tests_API_DnsSecTestRequest) GetCreatedBy() *string {
	return m.createdBy
}

// GetCreatedDate gets the createdDate property value. UTC created date (ISO date-time format).
// returns a *Time when successful
func (m *Tests_API_DnsSecTestRequest) GetCreatedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.createdDate
}

// GetDescription gets the description property value. A description of the test.
// returns a *string when successful
func (m *Tests_API_DnsSecTestRequest) GetDescription() *string {
	return m.description
}

// GetDnsQueryClass gets the dnsQueryClass property value. Domain class used by this test. 'in' stands for Internet, while 'ch' stands for Chaos.
// returns a *Tests_API_DnsQueryClass when successful
func (m *Tests_API_DnsSecTestRequest) GetDnsQueryClass() *Tests_API_DnsQueryClass {
	return m.dnsQueryClass
}

// GetDomain gets the domain property value. The target record for the test, with the record type suffixed. If no record type is specified, the test defaults to an ANY record.
// returns a *string when successful
func (m *Tests_API_DnsSecTestRequest) GetDomain() *string {
	return m.domain
}

// GetEnabled gets the enabled property value. Test is enabled.
// returns a *bool when successful
func (m *Tests_API_DnsSecTestRequest) GetEnabled() *bool {
	return m.enabled
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Tests_API_DnsSecTestRequest) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["agents"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateTests_API_TestAgentRequestFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Tests_API_TestAgentRequestable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(Tests_API_TestAgentRequestable)
				}
			}
			m.SetAgents(res)
		}
		return nil
	}
	res["alertRules"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetAlertRules(res)
		}
		return nil
	}
	res["alertsEnabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAlertsEnabled(val)
		}
		return nil
	}
	res["createdBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedBy(val)
		}
		return nil
	}
	res["createdDate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedDate(val)
		}
		return nil
	}
	res["description"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDescription(val)
		}
		return nil
	}
	res["dnsQueryClass"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_DnsQueryClass)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDnsQueryClass(val.(*Tests_API_DnsQueryClass))
		}
		return nil
	}
	res["domain"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDomain(val)
		}
		return nil
	}
	res["enabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEnabled(val)
		}
		return nil
	}
	res["interval"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetInterval(val)
		}
		return nil
	}
	res["labels"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetLabels(res)
		}
		return nil
	}
	res["_links"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateTests_API_TestLinksFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLinks(val.(Tests_API_TestLinksable))
		}
		return nil
	}
	res["liveShare"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLiveShare(val)
		}
		return nil
	}
	res["modifiedBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedBy(val)
		}
		return nil
	}
	res["modifiedDate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedDate(val)
		}
		return nil
	}
	res["randomizedStartTime"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRandomizedStartTime(val)
		}
		return nil
	}
	res["savedEvent"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSavedEvent(val)
		}
		return nil
	}
	res["sharedWithAccounts"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetSharedWithAccounts(res)
		}
		return nil
	}
	res["tags"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetTags(res)
		}
		return nil
	}
	res["testId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTestId(val)
		}
		return nil
	}
	res["testName"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTestName(val)
		}
		return nil
	}
	res["type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_TestType)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTypeEscaped(val.(*Tests_API_TestType))
		}
		return nil
	}
	return res
}

// GetInterval gets the interval property value. Interval between test runs in seconds.
// returns a *int32 when successful
func (m *Tests_API_DnsSecTestRequest) GetInterval() *int32 {
	return m.interval
}

// GetLabels gets the labels property value. Contains list of test label IDs (get `labelId` from `/labels` endpoint)
// returns a []string when successful
func (m *Tests_API_DnsSecTestRequest) GetLabels() []string {
	return m.labels
}

// GetLinks gets the _links property value. A list of links that can be accessed to get more information
// returns a Tests_API_TestLinksable when successful
func (m *Tests_API_DnsSecTestRequest) GetLinks() Tests_API_TestLinksable {
	return m.links
}

// GetLiveShare gets the liveShare property value. Indicates if the test is shared with the account group.
// returns a *bool when successful
func (m *Tests_API_DnsSecTestRequest) GetLiveShare() *bool {
	return m.liveShare
}

// GetModifiedBy gets the modifiedBy property value. User that modified the test.
// returns a *string when successful
func (m *Tests_API_DnsSecTestRequest) GetModifiedBy() *string {
	return m.modifiedBy
}

// GetModifiedDate gets the modifiedDate property value. UTC last modification date (ISO date-time format).
// returns a *Time when successful
func (m *Tests_API_DnsSecTestRequest) GetModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.modifiedDate
}

// GetRandomizedStartTime gets the randomizedStartTime property value. Indicates whether agents should randomize the start time in each test round.
// returns a *bool when successful
func (m *Tests_API_DnsSecTestRequest) GetRandomizedStartTime() *bool {
	return m.randomizedStartTime
}

// GetSavedEvent gets the savedEvent property value. Indicates if the test is a saved event.**Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API.
// returns a *bool when successful
func (m *Tests_API_DnsSecTestRequest) GetSavedEvent() *bool {
	return m.savedEvent
}

// GetSharedWithAccounts gets the sharedWithAccounts property value. Contains list of account group IDs. Test is shared with the listed account groups (get `aid` from `/account-groups` endpoint)
// returns a []string when successful
func (m *Tests_API_DnsSecTestRequest) GetSharedWithAccounts() []string {
	return m.sharedWithAccounts
}

// GetTags gets the tags property value. Contains list of test tag IDs (get `id` from `/tags` endpoint).
// returns a []string when successful
func (m *Tests_API_DnsSecTestRequest) GetTags() []string {
	return m.tags
}

// GetTestId gets the testId property value. Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
// returns a *string when successful
func (m *Tests_API_DnsSecTestRequest) GetTestId() *string {
	return m.testId
}

// GetTestName gets the testName property value. The name of the test. Test name must be unique.
// returns a *string when successful
func (m *Tests_API_DnsSecTestRequest) GetTestName() *string {
	return m.testName
}

// GetTypeEscaped gets the type property value. This is a read only value, as test type is implicit in the test creation url.
// returns a *Tests_API_TestType when successful
func (m *Tests_API_DnsSecTestRequest) GetTypeEscaped() *Tests_API_TestType {
	return m.typeEscaped
}

// Serialize serializes information the current object
func (m *Tests_API_DnsSecTestRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetAgents() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetAgents()))
		for i, v := range m.GetAgents() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("agents", cast)
		if err != nil {
			return err
		}
	}
	if m.GetAlertRules() != nil {
		err := writer.WriteCollectionOfStringValues("alertRules", m.GetAlertRules())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("alertsEnabled", m.GetAlertsEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("description", m.GetDescription())
		if err != nil {
			return err
		}
	}
	if m.GetDnsQueryClass() != nil {
		cast := (*m.GetDnsQueryClass()).String()
		err := writer.WriteStringValue("dnsQueryClass", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("domain", m.GetDomain())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("enabled", m.GetEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("interval", m.GetInterval())
		if err != nil {
			return err
		}
	}
	if m.GetLabels() != nil {
		err := writer.WriteCollectionOfStringValues("labels", m.GetLabels())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("randomizedStartTime", m.GetRandomizedStartTime())
		if err != nil {
			return err
		}
	}
	if m.GetSharedWithAccounts() != nil {
		err := writer.WriteCollectionOfStringValues("sharedWithAccounts", m.GetSharedWithAccounts())
		if err != nil {
			return err
		}
	}
	if m.GetTags() != nil {
		err := writer.WriteCollectionOfStringValues("tags", m.GetTags())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("testName", m.GetTestName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Tests_API_DnsSecTestRequest) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAgents sets the agents property value. Contains list of Agent IDs (get `agentId` from `/agents` endpoint).
func (m *Tests_API_DnsSecTestRequest) SetAgents(value []Tests_API_TestAgentRequestable) {
	m.agents = value
}

// SetAlertRules sets the alertRules property value. List of alert rules IDs to apply to the test (get `ruleId` from `/alerts/rules` endpoint. If `alertsEnabled` is set to `true` and `alertRules` is not included on test creation or update, applicable user default alert rules will be used)
func (m *Tests_API_DnsSecTestRequest) SetAlertRules(value []string) {
	m.alertRules = value
}

// SetAlertsEnabled sets the alertsEnabled property value. Indicates if alerts are enabled.
func (m *Tests_API_DnsSecTestRequest) SetAlertsEnabled(value *bool) {
	m.alertsEnabled = value
}

// SetCreatedBy sets the createdBy property value. User that created the test.
func (m *Tests_API_DnsSecTestRequest) SetCreatedBy(value *string) {
	m.createdBy = value
}

// SetCreatedDate sets the createdDate property value. UTC created date (ISO date-time format).
func (m *Tests_API_DnsSecTestRequest) SetCreatedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.createdDate = value
}

// SetDescription sets the description property value. A description of the test.
func (m *Tests_API_DnsSecTestRequest) SetDescription(value *string) {
	m.description = value
}

// SetDnsQueryClass sets the dnsQueryClass property value. Domain class used by this test. 'in' stands for Internet, while 'ch' stands for Chaos.
func (m *Tests_API_DnsSecTestRequest) SetDnsQueryClass(value *Tests_API_DnsQueryClass) {
	m.dnsQueryClass = value
}

// SetDomain sets the domain property value. The target record for the test, with the record type suffixed. If no record type is specified, the test defaults to an ANY record.
func (m *Tests_API_DnsSecTestRequest) SetDomain(value *string) {
	m.domain = value
}

// SetEnabled sets the enabled property value. Test is enabled.
func (m *Tests_API_DnsSecTestRequest) SetEnabled(value *bool) {
	m.enabled = value
}

// SetInterval sets the interval property value. Interval between test runs in seconds.
func (m *Tests_API_DnsSecTestRequest) SetInterval(value *int32) {
	m.interval = value
}

// SetLabels sets the labels property value. Contains list of test label IDs (get `labelId` from `/labels` endpoint)
func (m *Tests_API_DnsSecTestRequest) SetLabels(value []string) {
	m.labels = value
}

// SetLinks sets the _links property value. A list of links that can be accessed to get more information
func (m *Tests_API_DnsSecTestRequest) SetLinks(value Tests_API_TestLinksable) {
	m.links = value
}

// SetLiveShare sets the liveShare property value. Indicates if the test is shared with the account group.
func (m *Tests_API_DnsSecTestRequest) SetLiveShare(value *bool) {
	m.liveShare = value
}

// SetModifiedBy sets the modifiedBy property value. User that modified the test.
func (m *Tests_API_DnsSecTestRequest) SetModifiedBy(value *string) {
	m.modifiedBy = value
}

// SetModifiedDate sets the modifiedDate property value. UTC last modification date (ISO date-time format).
func (m *Tests_API_DnsSecTestRequest) SetModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.modifiedDate = value
}

// SetRandomizedStartTime sets the randomizedStartTime property value. Indicates whether agents should randomize the start time in each test round.
func (m *Tests_API_DnsSecTestRequest) SetRandomizedStartTime(value *bool) {
	m.randomizedStartTime = value
}

// SetSavedEvent sets the savedEvent property value. Indicates if the test is a saved event.**Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API.
func (m *Tests_API_DnsSecTestRequest) SetSavedEvent(value *bool) {
	m.savedEvent = value
}

// SetSharedWithAccounts sets the sharedWithAccounts property value. Contains list of account group IDs. Test is shared with the listed account groups (get `aid` from `/account-groups` endpoint)
func (m *Tests_API_DnsSecTestRequest) SetSharedWithAccounts(value []string) {
	m.sharedWithAccounts = value
}

// SetTags sets the tags property value. Contains list of test tag IDs (get `id` from `/tags` endpoint).
func (m *Tests_API_DnsSecTestRequest) SetTags(value []string) {
	m.tags = value
}

// SetTestId sets the testId property value. Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
func (m *Tests_API_DnsSecTestRequest) SetTestId(value *string) {
	m.testId = value
}

// SetTestName sets the testName property value. The name of the test. Test name must be unique.
func (m *Tests_API_DnsSecTestRequest) SetTestName(value *string) {
	m.testName = value
}

// SetTypeEscaped sets the type property value. This is a read only value, as test type is implicit in the test creation url.
func (m *Tests_API_DnsSecTestRequest) SetTypeEscaped(value *Tests_API_TestType) {
	m.typeEscaped = value
}

type Tests_API_DnsSecTestRequestable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAgents() []Tests_API_TestAgentRequestable
	GetAlertRules() []string
	GetAlertsEnabled() *bool
	GetCreatedBy() *string
	GetCreatedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetDescription() *string
	GetDnsQueryClass() *Tests_API_DnsQueryClass
	GetDomain() *string
	GetEnabled() *bool
	GetInterval() *int32
	GetLabels() []string
	GetLinks() Tests_API_TestLinksable
	GetLiveShare() *bool
	GetModifiedBy() *string
	GetModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetRandomizedStartTime() *bool
	GetSavedEvent() *bool
	GetSharedWithAccounts() []string
	GetTags() []string
	GetTestId() *string
	GetTestName() *string
	GetTypeEscaped() *Tests_API_TestType
	SetAgents(value []Tests_API_TestAgentRequestable)
	SetAlertRules(value []string)
	SetAlertsEnabled(value *bool)
	SetCreatedBy(value *string)
	SetCreatedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetDescription(value *string)
	SetDnsQueryClass(value *Tests_API_DnsQueryClass)
	SetDomain(value *string)
	SetEnabled(value *bool)
	SetInterval(value *int32)
	SetLabels(value []string)
	SetLinks(value Tests_API_TestLinksable)
	SetLiveShare(value *bool)
	SetModifiedBy(value *string)
	SetModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetRandomizedStartTime(value *bool)
	SetSavedEvent(value *bool)
	SetSharedWithAccounts(value []string)
	SetTags(value []string)
	SetTestId(value *string)
	SetTestName(value *string)
	SetTypeEscaped(value *Tests_API_TestType)
}
