// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"

	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Tests_API_UnexpandedDnsTraceTest struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Indicates if alerts are enabled.
	alertsEnabled *bool
	// User that created the test.
	createdBy *string
	// UTC created date (ISO date-time format).
	createdDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// A description of the test.
	description *string
	// Domain class used by this test. 'in' stands for Internet, while 'ch' stands for Chaos.
	dnsQueryClass *Tests_API_DnsQueryClass
	// Transport protocol used for DNS requests.
	dnsTransportProtocol *Tests_API_TestDnsTransportProtocol
	// The target record for the test, with the record type suffixed. If no record type is specified, the test defaults to an ANY record.
	domain *string
	// Test is enabled.
	enabled *bool
	// Interval between test runs in seconds.
	interval *int32
	// A list of links that can be accessed to get more information
	links Tests_API_TestLinksable
	// Indicates if the test is shared with the account group.
	liveShare *bool
	// User that modified the test.
	modifiedBy *string
	// UTC last modification date (ISO date-time format).
	modifiedDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// Indicates whether agents should randomize the start time in each test round.
	randomizedStartTime *bool
	// Indicates if the test is a saved event.**Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API.
	savedEvent *bool
	// Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
	testId *string
	// The name of the test. Test name must be unique.
	testName *string
	// This is a read only value, as test type is implicit in the test creation url.
	typeEscaped *Tests_API_TestType
}

// NewTests_API_UnexpandedDnsTraceTest instantiates a new Tests_API_UnexpandedDnsTraceTest and sets the default values.
func NewTests_API_UnexpandedDnsTraceTest() *Tests_API_UnexpandedDnsTraceTest {
	m := &Tests_API_UnexpandedDnsTraceTest{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateTests_API_UnexpandedDnsTraceTestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTests_API_UnexpandedDnsTraceTestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewTests_API_UnexpandedDnsTraceTest(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAlertsEnabled gets the alertsEnabled property value. Indicates if alerts are enabled.
// returns a *bool when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetAlertsEnabled() *bool {
	return m.alertsEnabled
}

// GetCreatedBy gets the createdBy property value. User that created the test.
// returns a *string when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetCreatedBy() *string {
	return m.createdBy
}

// GetCreatedDate gets the createdDate property value. UTC created date (ISO date-time format).
// returns a *Time when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetCreatedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.createdDate
}

// GetDescription gets the description property value. A description of the test.
// returns a *string when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetDescription() *string {
	return m.description
}

// GetDnsQueryClass gets the dnsQueryClass property value. Domain class used by this test. 'in' stands for Internet, while 'ch' stands for Chaos.
// returns a *Tests_API_DnsQueryClass when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetDnsQueryClass() *Tests_API_DnsQueryClass {
	return m.dnsQueryClass
}

// GetDnsTransportProtocol gets the dnsTransportProtocol property value. Transport protocol used for DNS requests.
// returns a *Tests_API_TestDnsTransportProtocol when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetDnsTransportProtocol() *Tests_API_TestDnsTransportProtocol {
	return m.dnsTransportProtocol
}

// GetDomain gets the domain property value. The target record for the test, with the record type suffixed. If no record type is specified, the test defaults to an ANY record.
// returns a *string when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetDomain() *string {
	return m.domain
}

// GetEnabled gets the enabled property value. Test is enabled.
// returns a *bool when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetEnabled() *bool {
	return m.enabled
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["alertsEnabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAlertsEnabled(val)
		}
		return nil
	}
	res["createdBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedBy(val)
		}
		return nil
	}
	res["createdDate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedDate(val)
		}
		return nil
	}
	res["description"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDescription(val)
		}
		return nil
	}
	res["dnsQueryClass"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_DnsQueryClass)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDnsQueryClass(val.(*Tests_API_DnsQueryClass))
		}
		return nil
	}
	res["dnsTransportProtocol"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_TestDnsTransportProtocol)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDnsTransportProtocol(val.(*Tests_API_TestDnsTransportProtocol))
		}
		return nil
	}
	res["domain"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDomain(val)
		}
		return nil
	}
	res["enabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEnabled(val)
		}
		return nil
	}
	res["interval"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetInterval(val)
		}
		return nil
	}
	res["_links"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateTests_API_TestLinksFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLinks(val.(Tests_API_TestLinksable))
		}
		return nil
	}
	res["liveShare"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLiveShare(val)
		}
		return nil
	}
	res["modifiedBy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedBy(val)
		}
		return nil
	}
	res["modifiedDate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetModifiedDate(val)
		}
		return nil
	}
	res["randomizedStartTime"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRandomizedStartTime(val)
		}
		return nil
	}
	res["savedEvent"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSavedEvent(val)
		}
		return nil
	}
	res["testId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTestId(val)
		}
		return nil
	}
	res["testName"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTestName(val)
		}
		return nil
	}
	res["type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTests_API_TestType)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTypeEscaped(val.(*Tests_API_TestType))
		}
		return nil
	}
	return res
}

// GetInterval gets the interval property value. Interval between test runs in seconds.
// returns a *int32 when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetInterval() *int32 {
	return m.interval
}

// GetLinks gets the _links property value. A list of links that can be accessed to get more information
// returns a Tests_API_TestLinksable when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetLinks() Tests_API_TestLinksable {
	return m.links
}

// GetLiveShare gets the liveShare property value. Indicates if the test is shared with the account group.
// returns a *bool when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetLiveShare() *bool {
	return m.liveShare
}

// GetModifiedBy gets the modifiedBy property value. User that modified the test.
// returns a *string when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetModifiedBy() *string {
	return m.modifiedBy
}

// GetModifiedDate gets the modifiedDate property value. UTC last modification date (ISO date-time format).
// returns a *Time when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.modifiedDate
}

// GetRandomizedStartTime gets the randomizedStartTime property value. Indicates whether agents should randomize the start time in each test round.
// returns a *bool when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetRandomizedStartTime() *bool {
	return m.randomizedStartTime
}

// GetSavedEvent gets the savedEvent property value. Indicates if the test is a saved event.**Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API.
// returns a *bool when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetSavedEvent() *bool {
	return m.savedEvent
}

// GetTestId gets the testId property value. Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
// returns a *string when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetTestId() *string {
	return m.testId
}

// GetTestName gets the testName property value. The name of the test. Test name must be unique.
// returns a *string when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetTestName() *string {
	return m.testName
}

// GetTypeEscaped gets the type property value. This is a read only value, as test type is implicit in the test creation url.
// returns a *Tests_API_TestType when successful
func (m *Tests_API_UnexpandedDnsTraceTest) GetTypeEscaped() *Tests_API_TestType {
	return m.typeEscaped
}

// Serialize serializes information the current object
func (m *Tests_API_UnexpandedDnsTraceTest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteBoolValue("alertsEnabled", m.GetAlertsEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("description", m.GetDescription())
		if err != nil {
			return err
		}
	}
	if m.GetDnsQueryClass() != nil {
		cast := (*m.GetDnsQueryClass()).String()
		err := writer.WriteStringValue("dnsQueryClass", &cast)
		if err != nil {
			return err
		}
	}
	if m.GetDnsTransportProtocol() != nil {
		cast := (*m.GetDnsTransportProtocol()).String()
		err := writer.WriteStringValue("dnsTransportProtocol", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("domain", m.GetDomain())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("enabled", m.GetEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("interval", m.GetInterval())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("randomizedStartTime", m.GetRandomizedStartTime())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("testName", m.GetTestName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Tests_API_UnexpandedDnsTraceTest) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAlertsEnabled sets the alertsEnabled property value. Indicates if alerts are enabled.
func (m *Tests_API_UnexpandedDnsTraceTest) SetAlertsEnabled(value *bool) {
	m.alertsEnabled = value
}

// SetCreatedBy sets the createdBy property value. User that created the test.
func (m *Tests_API_UnexpandedDnsTraceTest) SetCreatedBy(value *string) {
	m.createdBy = value
}

// SetCreatedDate sets the createdDate property value. UTC created date (ISO date-time format).
func (m *Tests_API_UnexpandedDnsTraceTest) SetCreatedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.createdDate = value
}

// SetDescription sets the description property value. A description of the test.
func (m *Tests_API_UnexpandedDnsTraceTest) SetDescription(value *string) {
	m.description = value
}

// SetDnsQueryClass sets the dnsQueryClass property value. Domain class used by this test. 'in' stands for Internet, while 'ch' stands for Chaos.
func (m *Tests_API_UnexpandedDnsTraceTest) SetDnsQueryClass(value *Tests_API_DnsQueryClass) {
	m.dnsQueryClass = value
}

// SetDnsTransportProtocol sets the dnsTransportProtocol property value. Transport protocol used for DNS requests.
func (m *Tests_API_UnexpandedDnsTraceTest) SetDnsTransportProtocol(value *Tests_API_TestDnsTransportProtocol) {
	m.dnsTransportProtocol = value
}

// SetDomain sets the domain property value. The target record for the test, with the record type suffixed. If no record type is specified, the test defaults to an ANY record.
func (m *Tests_API_UnexpandedDnsTraceTest) SetDomain(value *string) {
	m.domain = value
}

// SetEnabled sets the enabled property value. Test is enabled.
func (m *Tests_API_UnexpandedDnsTraceTest) SetEnabled(value *bool) {
	m.enabled = value
}

// SetInterval sets the interval property value. Interval between test runs in seconds.
func (m *Tests_API_UnexpandedDnsTraceTest) SetInterval(value *int32) {
	m.interval = value
}

// SetLinks sets the _links property value. A list of links that can be accessed to get more information
func (m *Tests_API_UnexpandedDnsTraceTest) SetLinks(value Tests_API_TestLinksable) {
	m.links = value
}

// SetLiveShare sets the liveShare property value. Indicates if the test is shared with the account group.
func (m *Tests_API_UnexpandedDnsTraceTest) SetLiveShare(value *bool) {
	m.liveShare = value
}

// SetModifiedBy sets the modifiedBy property value. User that modified the test.
func (m *Tests_API_UnexpandedDnsTraceTest) SetModifiedBy(value *string) {
	m.modifiedBy = value
}

// SetModifiedDate sets the modifiedDate property value. UTC last modification date (ISO date-time format).
func (m *Tests_API_UnexpandedDnsTraceTest) SetModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.modifiedDate = value
}

// SetRandomizedStartTime sets the randomizedStartTime property value. Indicates whether agents should randomize the start time in each test round.
func (m *Tests_API_UnexpandedDnsTraceTest) SetRandomizedStartTime(value *bool) {
	m.randomizedStartTime = value
}

// SetSavedEvent sets the savedEvent property value. Indicates if the test is a saved event.**Note**: **Saved Events** are now called **Private Snapshots** in the user interface. This change does not affect API.
func (m *Tests_API_UnexpandedDnsTraceTest) SetSavedEvent(value *bool) {
	m.savedEvent = value
}

// SetTestId sets the testId property value. Each test is assigned an unique ID; this is used to access test information and results from other endpoints.
func (m *Tests_API_UnexpandedDnsTraceTest) SetTestId(value *string) {
	m.testId = value
}

// SetTestName sets the testName property value. The name of the test. Test name must be unique.
func (m *Tests_API_UnexpandedDnsTraceTest) SetTestName(value *string) {
	m.testName = value
}

// SetTypeEscaped sets the type property value. This is a read only value, as test type is implicit in the test creation url.
func (m *Tests_API_UnexpandedDnsTraceTest) SetTypeEscaped(value *Tests_API_TestType) {
	m.typeEscaped = value
}

type Tests_API_UnexpandedDnsTraceTestable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAlertsEnabled() *bool
	GetCreatedBy() *string
	GetCreatedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetDescription() *string
	GetDnsQueryClass() *Tests_API_DnsQueryClass
	GetDnsTransportProtocol() *Tests_API_TestDnsTransportProtocol
	GetDomain() *string
	GetEnabled() *bool
	GetInterval() *int32
	GetLinks() Tests_API_TestLinksable
	GetLiveShare() *bool
	GetModifiedBy() *string
	GetModifiedDate() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetRandomizedStartTime() *bool
	GetSavedEvent() *bool
	GetTestId() *string
	GetTestName() *string
	GetTypeEscaped() *Tests_API_TestType
	SetAlertsEnabled(value *bool)
	SetCreatedBy(value *string)
	SetCreatedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetDescription(value *string)
	SetDnsQueryClass(value *Tests_API_DnsQueryClass)
	SetDnsTransportProtocol(value *Tests_API_TestDnsTransportProtocol)
	SetDomain(value *string)
	SetEnabled(value *bool)
	SetInterval(value *int32)
	SetLinks(value Tests_API_TestLinksable)
	SetLiveShare(value *bool)
	SetModifiedBy(value *string)
	SetModifiedDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetRandomizedStartTime(value *bool)
	SetSavedEvent(value *bool)
	SetTestId(value *string)
	SetTestName(value *string)
	SetTypeEscaped(value *Tests_API_TestType)
}
