// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// The status of the stream integration. pending: No data is currently being sent to the stream endpoint. failing: Data is being sent but not successfully reaching the stream endpoint. connected: Data is being sent successfully to the stream endpoint.
type ThousandEyes_for_OpenTelemetry_API_StreamStatusType int

const (
	CONNECTED_THOUSANDEYES_FOR_OPENTELEMETRY_API_STREAMSTATUSTYPE ThousandEyes_for_OpenTelemetry_API_StreamStatusType = iota
	PENDING_THOUSANDEYES_FOR_OPENTELEMETRY_API_STREAMSTATUSTYPE
	FAILING_THOUSANDEYES_FOR_OPENTELEMETRY_API_STREAMSTATUSTYPE
)

func (i ThousandEyes_for_OpenTelemetry_API_StreamStatusType) String() string {
	return []string{"connected", "pending", "failing"}[i]
}

func ParseThousandEyes_for_OpenTelemetry_API_StreamStatusType(v string) (any, error) {
	result := CONNECTED_THOUSANDEYES_FOR_OPENTELEMETRY_API_STREAMSTATUSTYPE
	switch v {
	case "connected":
		result = CONNECTED_THOUSANDEYES_FOR_OPENTELEMETRY_API_STREAMSTATUSTYPE
	case "pending":
		result = PENDING_THOUSANDEYES_FOR_OPENTELEMETRY_API_STREAMSTATUSTYPE
	case "failing":
		result = FAILING_THOUSANDEYES_FOR_OPENTELEMETRY_API_STREAMSTATUSTYPE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeThousandEyes_for_OpenTelemetry_API_StreamStatusType(values []ThousandEyes_for_OpenTelemetry_API_StreamStatusType) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i ThousandEyes_for_OpenTelemetry_API_StreamStatusType) isMultiValue() bool {
	return false
}
