// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:5bb9a56c6d082987640c8d4049827cbb3511cd53115e02b95bc05bd352cf8a1b). DO NOT EDIT.

package monitor

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// MonitorDataSourceModel is the Terraform state for a thousandeyes_monitor.
//
// Field order follows the schema, and the timeouts value is last.
type MonitorDataSourceModel struct {
	CountryID   types.String   `tfsdk:"country_id"`
	IPAddress   types.String   `tfsdk:"ip_address"`
	MonitorID   types.String   `tfsdk:"monitor_id"`
	MonitorName types.String   `tfsdk:"monitor_name"`
	MonitorType types.String   `tfsdk:"monitor_type"`
	Network     types.String   `tfsdk:"network"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
}
