// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:5bb9a56c6d082987640c8d4049827cbb3511cd53115e02b95bc05bd352cf8a1b). DO NOT EDIT.

package endpoint_label

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/convert"
)

// constructResource maps Terraform configuration onto the API's request body.
//
// Only writable attributes appear here. A computed attribute has no expand
// conversion, so it cannot be sent by construction rather than by discipline.
func constructResource(ctx context.Context, data *EndpointLabelResourceModel) (*models.Endpoint_Agent_Labels_API_LabelRequest, diag.Diagnostics) {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)
	tflog.Debug(ctx, "constructing request body", map[string]any{"resource": TypeName})

	body := models.NewEndpoint_Agent_Labels_API_LabelRequest()

	body.SetColor(convert.FrameworkToPtrString(data.Color))
	filtersRaw, d := expandEndpointLabelFilters(ctx, data.Filters)
	diags.Append(d...)
	body.SetFilters(filtersRaw)
	matchTypeRaw, d := convert.FrameworkToKiotaEnum[models.Endpoint_Agent_Labels_API_MatchType](data.MatchType, models.ParseEndpoint_Agent_Labels_API_MatchType)
	diags.Append(d...)
	body.SetMatchType(matchTypeRaw)
	body.SetName(convert.FrameworkToPtrString(data.Name))

	return body, diags
}

// constructResourceUpdate builds the update request body.
//
// A separate function because this SDK gives update its own request type. The
// assignment list is create's except where an attribute declares updateExpand --
// an SDK whose update type spells a field differently from create's -- and the
// bindings check has proven every assigned field exists on its own type.
func constructResourceUpdate(ctx context.Context, data *EndpointLabelResourceModel) (*models.Endpoint_Agent_Labels_API_Label, diag.Diagnostics) {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)
	tflog.Debug(ctx, "constructing update request body", map[string]any{"resource": TypeName})

	body := models.NewEndpoint_Agent_Labels_API_Label()

	body.SetColor(convert.FrameworkToPtrString(data.Color))
	filtersRaw, d := expandEndpointLabelFilters(ctx, data.Filters)
	diags.Append(d...)
	body.SetFilters(filtersRaw)
	matchTypeRaw, d := convert.FrameworkToKiotaEnum[models.Endpoint_Agent_Labels_API_MatchType](data.MatchType, models.ParseEndpoint_Agent_Labels_API_MatchType)
	diags.Append(d...)
	body.SetMatchType(matchTypeRaw)
	body.SetName(convert.FrameworkToPtrString(data.Name))

	return body, diags
}

// expandEndpointLabelFilters converts the configured EndpointLabelFilterModel values into SDK structs.
func expandEndpointLabelFilters(ctx context.Context, v types.Set) ([]models.Endpoint_Agent_Labels_API_Filterable, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []EndpointLabelFilterModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]models.Endpoint_Agent_Labels_API_Filterable, 0, len(elements))
	for _, m := range elements {
		item := models.NewEndpoint_Agent_Labels_API_Filter()

		keyRaw, d := convert.FrameworkToKiotaEnum[models.Endpoint_Agent_Labels_API_FilterType](m.Key, models.ParseEndpoint_Agent_Labels_API_FilterType)
		diags.Append(d...)
		item.SetKey(keyRaw)
		modeRaw, d := convert.FrameworkToKiotaEnum[models.Endpoint_Agent_Labels_API_LabelFilterMode](m.Mode, models.ParseEndpoint_Agent_Labels_API_LabelFilterMode)
		diags.Append(d...)
		item.SetMode(modeRaw)
		valuesRaw, d := convert.FrameworkSetToStringSlice(ctx, m.Values)
		diags.Append(d...)
		item.SetValues(valuesRaw)
		out = append(out, item)
	}

	return out, diags
}
