// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:17ccadd9f04833a0c47aa480004eff43ce664c1e4202c4da5c92d766e70cb2c7). DO NOT EDIT.

package tag

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// TagResourceModel is the Terraform state for a thousandeyes_tag.
//
// Field order follows the schema, and the timeouts value is last.
type TagResourceModel struct {
	AccessType   types.String   `tfsdk:"access_type"`
	AID          types.Int64    `tfsdk:"aid"`
	Assignments  types.Set      `tfsdk:"assignments"`
	BuiltIn      types.Bool     `tfsdk:"built_in"`
	Color        types.String   `tfsdk:"color"`
	CreateDate   types.String   `tfsdk:"create_date"`
	Description  types.String   `tfsdk:"description"`
	Filters      types.Set      `tfsdk:"filters"`
	Icon         types.String   `tfsdk:"icon"`
	ID           types.String   `tfsdk:"id"`
	Key          types.String   `tfsdk:"key"`
	LegacyID     types.Float64  `tfsdk:"legacy_id"`
	MatchType    types.String   `tfsdk:"match_type"`
	ModifiedDate types.String   `tfsdk:"modified_date"`
	ObjectType   types.String   `tfsdk:"object_type"`
	Type         types.String   `tfsdk:"type"`
	Value        types.String   `tfsdk:"value"`
	Timeouts     timeouts.Value `tfsdk:"timeouts"`
}

// TagAssignmentModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type TagAssignmentModel struct {
	ID   types.String `tfsdk:"id"`
	Type types.String `tfsdk:"type"`
}

// tagAssignmentAttrTypes describes TagAssignmentModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var tagAssignmentAttrTypes = map[string]attr.Type{
	"id":   types.StringType,
	"type": types.StringType,
}

var tagAssignmentObjectType = types.ObjectType{AttrTypes: tagAssignmentAttrTypes}

// TagFilterModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type TagFilterModel struct {
	Key    types.String `tfsdk:"key"`
	Mode   types.String `tfsdk:"mode"`
	Scope  types.String `tfsdk:"scope"`
	Values types.Set    `tfsdk:"values"`
}

// tagFilterAttrTypes describes TagFilterModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var tagFilterAttrTypes = map[string]attr.Type{
	"key":    types.StringType,
	"mode":   types.StringType,
	"scope":  types.StringType,
	"values": types.SetType{ElemType: types.StringType},
}

var tagFilterObjectType = types.ObjectType{AttrTypes: tagFilterAttrTypes}
