# Code generated by tfpfgen from blueprints/thousandeyes
# (sha256:5bb9a56c6d082987640c8d4049827cbb3511cd53115e02b95bc05bd352cf8a1b). DO NOT EDIT.

# The widest configuration the evidence supports: every writable attribute with a derivable
# value, chosen by the same derivation the rehearsal probe sends to the live API.
#
# Regenerated and policed, deliberately. This file used to be a hand-owned scaffold, and
# hand edits are how its values drifted from the generated assertions -- the checks derive
# from the blueprint, so the blueprint is where a value is corrected: an accFixture hint for
# something only a human knows, recorded behaviour for everything the probe observed. What
# could not be derived is listed inside the block, each with the reason.

resource "thousandeyes_tests_bgp" "test" {
  # Where a value came from.
  #
  # alerts_enabled: the API's own default, so a value it is known to accept
  #
  # enabled: the API's own default, so a value it is known to accept
  #
  # include_covered_prefixes: the API's own default, so a value it is known to accept
  #
  # use_public_bgp: the API's own default, so a value it is known to accept
  alerts_enabled           = true
  description              = "tfacc-description"
  enabled                  = true
  include_covered_prefixes = false
  test_name                = "tfacc-test-name"
  use_public_bgp           = true
}
