// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package testresults

import (
	"context"

	ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3 "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder builds and executes requests for operations under \test-results\{testId}\web-transactions\agent\{agentId}\round\{roundId}\page\{pageId}
type ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilderGetQueryParameters returns a page of web transaction test results for an agent and round.
type ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilderGetQueryParameters struct {
	// A unique identifier associated with your account group. You can retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note that you must be assigned to the target account group. Specifying this parameter without being assigned to the target account group will result in an error response.
	Aid *string "uriparametername:\"aid\""
}

// NewItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilderInternal instantiates a new ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder and sets the default values.
func NewItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder {
	m := &ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/test-results/{testId}/web-transactions/agent/{agentId}/round/{roundId}/page/{pageId}{?aid*}", pathParameters),
	}
	return m
}

// NewItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder instantiates a new ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder and sets the default values.
func NewItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilderInternal(urlParams, requestAdapter)
}

// Get returns a page of web transaction test results for an agent and round.
// returns a Test_Results_API_WebTransactionPageDetailTestResultsable when successful
// returns a Test_Results_API_ValidationError error when the service returns a 400 status code
// returns a Test_Results_API_UnauthorizedError error when the service returns a 401 status code
// returns a Test_Results_API_Error error when the service returns a 403 status code
// returns a Test_Results_API_Error error when the service returns a 404 status code
// returns a Test_Results_API_Error error when the service returns a 429 status code
// returns a Test_Results_API_Error error when the service returns a 500 status code
// returns a Test_Results_API_Error error when the service returns a 502 status code
func (m *ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilderGetQueryParameters]) (ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Test_Results_API_WebTransactionPageDetailTestResultsable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateTest_Results_API_ValidationErrorFromDiscriminatorValue,
		"401": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateTest_Results_API_UnauthorizedErrorFromDiscriminatorValue,
		"403": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateTest_Results_API_ErrorFromDiscriminatorValue,
		"404": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateTest_Results_API_ErrorFromDiscriminatorValue,
		"429": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateTest_Results_API_ErrorFromDiscriminatorValue,
		"500": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateTest_Results_API_ErrorFromDiscriminatorValue,
		"502": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateTest_Results_API_ErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateTest_Results_API_WebTransactionPageDetailTestResultsFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Test_Results_API_WebTransactionPageDetailTestResultsable), nil
}

// ToGetRequestInformation returns a page of web transaction test results for an agent and round.
// returns a *RequestInformation when successful
func (m *ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/hal+json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder when successful
func (m *ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder) WithUrl(rawUrl string) *ItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder {
	return NewItemWebTransactionsAgentItemRoundItemPageWithPageItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
