// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:17ccadd9f04833a0c47aa480004eff43ce664c1e4202c4da5c92d766e70cb2c7). DO NOT EDIT.

package operations_credential_vault

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// OperationsCredentialVaultDataSourceModel is the Terraform state for a thousandeyes_operations_credential_vault.
//
// Field order follows the schema, and the timeouts value is last.
type OperationsCredentialVaultDataSourceModel struct {
	ID       types.String   `tfsdk:"id"`
	Name     types.String   `tfsdk:"name"`
	Secrets  types.Set      `tfsdk:"secrets"`
	Status   types.String   `tfsdk:"status"`
	Type     types.String   `tfsdk:"type"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

// OperationsCredentialVaultCredentialVaultSecretModel is one element of a nested attribute.
//
// It is a sibling of the data source model rather than an inner type, because the
// framework decodes collection elements into a named type.
type OperationsCredentialVaultCredentialVaultSecretModel struct {
	ID        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	SecretKey types.String `tfsdk:"secret_key"`
}

// operationsCredentialVaultCredentialVaultSecretAttrTypes describes OperationsCredentialVaultCredentialVaultSecretModel to the framework.
//
// It is declared once and referenced by the conversion helper, so the shape cannot
// drift between the declaration and the code that populates it.
var operationsCredentialVaultCredentialVaultSecretAttrTypes = map[string]attr.Type{
	"id":         types.StringType,
	"name":       types.StringType,
	"secret_key": types.StringType,
}

var operationsCredentialVaultCredentialVaultSecretObjectType = types.ObjectType{AttrTypes: operationsCredentialVaultCredentialVaultSecretAttrTypes}
