// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package events

import (
	"context"

	ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3 "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// EventsItemRequestBuilder builds and executes requests for operations under \events\{id}
type EventsItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// EventsItemRequestBuilderGetQueryParameters returns detailed information about an event using its ID.
type EventsItemRequestBuilderGetQueryParameters struct {
	// A unique identifier associated with your account group. You can retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note that you must be assigned to the target account group. Specifying this parameter without being assigned to the target account group will result in an error response.
	Aid *string "uriparametername:\"aid\""
}

// NewEventsItemRequestBuilderInternal instantiates a new EventsItemRequestBuilder and sets the default values.
func NewEventsItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *EventsItemRequestBuilder {
	m := &EventsItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/events/{id}{?aid*}", pathParameters),
	}
	return m
}

// NewEventsItemRequestBuilder instantiates a new EventsItemRequestBuilder and sets the default values.
func NewEventsItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *EventsItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewEventsItemRequestBuilderInternal(urlParams, requestAdapter)
}

// Get returns detailed information about an event using its ID.
// returns a Event_Detection_API_EventDetailable when successful
// returns a Event_Detection_API_UnauthorizedError error when the service returns a 401 status code
// returns a Event_Detection_API_Error error when the service returns a 403 status code
// returns a Event_Detection_API_Error error when the service returns a 404 status code
// returns a Event_Detection_API_Error error when the service returns a 429 status code
// returns a Event_Detection_API_Error error when the service returns a 500 status code
// returns a Event_Detection_API_Error error when the service returns a 502 status code
func (m *EventsItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[EventsItemRequestBuilderGetQueryParameters]) (ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Event_Detection_API_EventDetailable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"401": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEvent_Detection_API_UnauthorizedErrorFromDiscriminatorValue,
		"403": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEvent_Detection_API_ErrorFromDiscriminatorValue,
		"404": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEvent_Detection_API_ErrorFromDiscriminatorValue,
		"429": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEvent_Detection_API_ErrorFromDiscriminatorValue,
		"500": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEvent_Detection_API_ErrorFromDiscriminatorValue,
		"502": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEvent_Detection_API_ErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEvent_Detection_API_EventDetailFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Event_Detection_API_EventDetailable), nil
}

// ToGetRequestInformation returns detailed information about an event using its ID.
// returns a *RequestInformation when successful
func (m *EventsItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[EventsItemRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/hal+json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *EventsItemRequestBuilder when successful
func (m *EventsItemRequestBuilder) WithUrl(rawUrl string) *EventsItemRequestBuilder {
	return NewEventsItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
