// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:5784e03978dc4aa1168b63f15b5200e4d2c21e162af10c9c1d3532b5a6e56762). DO NOT EDIT.

package role

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// RoleResourceModel is the Terraform state for a thousandeyes_role.
//
// Field order follows the schema, and the timeouts value is last.
type RoleResourceModel struct {
	IsBuiltin   types.Bool     `tfsdk:"is_builtin"`
	Name        types.String   `tfsdk:"name"`
	Permissions types.Set      `tfsdk:"permissions"`
	ID          types.String   `tfsdk:"id"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
}
