// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:c2f31b5ceae54901082d303a3578916d3c0f177b0c43d44a1e482ca80a1e9dd1). DO NOT EDIT.

package role

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// RoleResourceModel is the Terraform state for a thousandeyes_role.
//
// Field order follows the schema, and the timeouts value is last.
type RoleResourceModel struct {
	IsBuiltin   types.Bool     `tfsdk:"is_builtin"`
	Name        types.String   `tfsdk:"name"`
	Permissions types.Set      `tfsdk:"permissions"`
	ID          types.String   `tfsdk:"id"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
}
