// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:c2f31b5ceae54901082d303a3578916d3c0f177b0c43d44a1e482ca80a1e9dd1). DO NOT EDIT.

package tests_dnssec

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/client"
	sdk "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk"
	commonschema "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/schema"
)

const (
	// TypeName is the Terraform type this resource registers as.
	TypeName = "thousandeyes_tests_dnssec"

	// Default per-operation timeouts, in seconds. A practitioner overrides them
	// with the resource's timeouts block.
	CreateTimeout = 180
	ReadTimeout   = 180
	UpdateTimeout = 180
	DeleteTimeout = 180
)

// Compile-time assertions that this resource implements what it claims to. They
// turn a missing method into a build failure rather than a runtime surprise.
var (
	_ resource.Resource                = (*TestsDNSSECResource)(nil)
	_ resource.ResourceWithConfigure   = (*TestsDNSSECResource)(nil)
	_ resource.ResourceWithImportState = (*TestsDNSSECResource)(nil)
)

// NewTestsDNSSECResource returns the thousandeyes_tests_dnssec resource.
func NewTestsDNSSECResource() resource.Resource {
	return &TestsDNSSECResource{}
}

// TestsDNSSECResource implements the thousandeyes_tests_dnssec resource.
type TestsDNSSECResource struct {
	client *sdk.ThousandEyesClient
}

// Metadata returns the resource type name.
func (r *TestsDNSSECResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TypeName
}

// Configure receives the configured SDK client from the provider.
func (r *TestsDNSSECResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = client.ForResource(ctx, req, resp, TypeName)
}

// ImportState maps a terraform import into state.
func (r *TestsDNSSECResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// Schema returns the resource schema.
func (r *TestsDNSSECResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Get DNSSEC test.",
		Attributes: map[string]schema.Attribute{
			"alerts_enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Indicates if alerts are enabled. <!-- probed:7.0.98-t1785745046061 --> Observed: the API " +
					"assigns true when this is omitted. <!-- /probed -->",
			},
			"created_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "User that created the test.",
			},
			"created_date": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC created date (ISO date-time format).",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "A description of the test.",
			},
			"dns_query_class": schema.StringAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Domain class used by this test. 'in' stands for Internet, while 'ch' stands for Chaos. " +
					"Computed as well as optional: the 2026-08-03 dispatched acceptance run (#12) observed the " +
					"API applying its own value when this is omitted. <!-- probed:static --> The SDK's encoding " +
					"drops this type's zero value (omitempty), so configuring false, 0 or \"\" silently becomes " +
					"an omission. <!-- /probed -->",
				Validators: []validator.String{
					stringvalidator.OneOf("in", "ch"),
				},
			},
			"domain": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "The target record for the test, with the record type suffixed. If no record type is " +
					"specified, the test defaults to an ANY record. The test's target: the API refuses a create " +
					"without it, whatever the specification marks. <!-- probed:7.0.98-t1785745046061 --> The " +
					"API enforces this field's presence, which the specification does not declare. <!-- /probed " +
					"--> The API normalises this value (appends the record type, cloudflare.com becomes " +
					"\"cloudflare.com ANY\"; the 2026-08-03 acceptance run (#13)); state carries the configured " +
					"form.",
			},
			"enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Test is enabled. <!-- probed:7.0.98-t1785745046061 --> Observed: the API assigns true when " +
					"this is omitted. <!-- /probed --> <!-- probed:static --> The SDK's encoding drops this " +
					"type's zero value (omitempty), so configuring false, 0 or \"\" silently becomes an omission. " +
					"<!-- /probed -->",
			},
			"interval": schema.Int64Attribute{
				Optional: true,
				MarkdownDescription: "Interval between test runs in seconds. Documented intervals, in seconds: `60`, `120`, " +
					"`300`, `600`, `900`, `1800`, `3600`. The request carries this field unconditionally, so " +
					"omitting it sends zero, which the API refuses (the 2026-08-03 scheduled acceptance run). " +
					"<!-- probed:7.0.98-t1785745046061 --> The API enforces this field's presence, which the " +
					"specification does not declare. <!-- /probed -->",
			},
			"live_share": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Indicates if the test is shared with the account group.",
			},
			"modified_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "User that modified the test.",
			},
			"modified_date": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC last modification date (ISO date-time format).",
			},
			"randomized_start_time": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Indicates whether agents should randomize the start time in each test round. <!-- " +
					"probed:7.0.98-t1785745046061 --> Observed: the API assigns false when this is omitted. " +
					"<!-- /probed --> <!-- probed:static --> The SDK's encoding drops this type's zero value " +
					"(omitempty), so configuring false, 0 or \"\" silently becomes an omission. <!-- /probed -->",
			},
			"saved_event": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: "Indicates if the test is a saved event. **Note**: **Saved Events** are now called " +
					"**Private Snapshots** in the user interface. This change does not affect API.",
			},
			"id": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: "Each test is assigned an unique ID; this is used to access test information and results " +
					"from other endpoints.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"test_name": schema.StringAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "The name of the test. Test name must be unique. Computed as well as optional: the " +
					"2026-08-03 dispatched acceptance run (#12) observed the API applying its own value when " +
					"this is omitted.",
			},
			"type": schema.StringAttribute{
				Computed: true,
			},
			"agents": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"agent_id": schema.StringAttribute{
							Required: true,
							MarkdownDescription: "The agent to run the test from. Get identifiers from `/agents`; cloud agent identifiers " +
								"are stable public values.",
						},
					},
				},
				Required: true,
				MarkdownDescription: "The agents the test runs from. Sent on create and update; the read reports assignment " +
					"through its own fields, so this does not round-trip into state. <!-- " +
					"probed:7.0.98-t1785745046061 --> The API enforces this field's presence, which the " +
					"specification does not declare. <!-- /probed -->",
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": commonschema.ResourceTimeouts(ctx),
		},
	}
}
