// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:d986d7900b3714639519883166d0066510af34e4e4431384031a6f7b9dc0895a). DO NOT EDIT.

package usage_units_enterprise_agent

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// UsageUnitsEnterpriseAgentDataSourceModel is the Terraform state for a thousandeyes_usage_units_enterprise_agent.
//
// Field order follows the schema, and the timeouts value is last.
type UsageUnitsEnterpriseAgentDataSourceModel struct {
	AccountGroupName         types.String   `tfsdk:"account_group_name"`
	AgentID                  types.String   `tfsdk:"agent_id"`
	AgentName                types.String   `tfsdk:"agent_name"`
	EnterpriseUnitsProjected types.Int64    `tfsdk:"enterprise_units_projected"`
	EnterpriseUnitsUsed      types.Int64    `tfsdk:"enterprise_units_used"`
	ID                       types.String   `tfsdk:"id"`
	Timeouts                 timeouts.Value `tfsdk:"timeouts"`
}
