// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:17ccadd9f04833a0c47aa480004eff43ce664c1e4202c4da5c92d766e70cb2c7). DO NOT EDIT.

package connectors_generic

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ConnectorsGenericDataSourceModel is the Terraform state for a thousandeyes_connectors_generic.
//
// Field order follows the schema, and the timeouts value is last.
type ConnectorsGenericDataSourceModel struct {
	Headers          types.Set      `tfsdk:"headers"`
	ID               types.String   `tfsdk:"id"`
	LastModifiedDate types.Int64    `tfsdk:"last_modified_date"`
	Name             types.String   `tfsdk:"name"`
	Target           types.String   `tfsdk:"target"`
	Type             types.String   `tfsdk:"type"`
	Timeouts         timeouts.Value `tfsdk:"timeouts"`
}

// ConnectorsGenericHeaderModel is one element of a nested attribute.
//
// It is a sibling of the data source model rather than an inner type, because the
// framework decodes collection elements into a named type.
type ConnectorsGenericHeaderModel struct {
	Name  types.String `tfsdk:"name"`
	Value types.String `tfsdk:"value"`
}

// connectorsGenericHeaderAttrTypes describes ConnectorsGenericHeaderModel to the framework.
//
// It is declared once and referenced by the conversion helper, so the shape cannot
// drift between the declaration and the code that populates it.
var connectorsGenericHeaderAttrTypes = map[string]attr.Type{
	"name":  types.StringType,
	"value": types.StringType,
}

var connectorsGenericHeaderObjectType = types.ObjectType{AttrTypes: connectorsGenericHeaderAttrTypes}
