// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:5784e03978dc4aa1168b63f15b5200e4d2c21e162af10c9c1d3532b5a6e56762). DO NOT EDIT.

package tests_web_transaction

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/convert"
)

// constructResource maps Terraform configuration onto the API's request body.
//
// Only writable attributes appear here. A computed attribute has no expand
// conversion, so it cannot be sent by construction rather than by discipline.
func constructResource(ctx context.Context, data *TestsWebTransactionResourceModel) (*models.Tests_API_WebTransactionTestRequest, diag.Diagnostics) {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)
	tflog.Debug(ctx, "constructing request body", map[string]any{"resource": TypeName})

	body := models.NewTests_API_WebTransactionTestRequest()

	body.SetAlertsEnabled(convert.FrameworkToPtrBool(data.AlertsEnabled))
	body.SetAllowGeolocation(convert.FrameworkToPtrBool(data.AllowGeolocation))
	body.SetAllowMicAndCamera(convert.FrameworkToPtrBool(data.AllowMicAndCamera))
	body.SetAllowUnsafeLegacyRenegotiation(convert.FrameworkToPtrBool(data.AllowUnsafeLegacyRenegotiation))
	authTypeRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestAuthType](data.AuthType, models.ParseTests_API_TestAuthType)
	diags.Append(d...)
	body.SetAuthType(authTypeRaw)
	body.SetBandwidthMeasurements(convert.FrameworkToPtrBool(data.BandwidthMeasurements))
	body.SetBgpMeasurements(convert.FrameworkToPtrBool(data.BGPMeasurements))
	body.SetBlockDomains(convert.FrameworkToPtrString(data.BlockDomains))
	body.SetBrowserLanguage(convert.FrameworkToPtrString(data.BrowserLanguage))
	body.SetChromeOptions(convert.FrameworkToPtrString(data.ChromeOptions))
	body.SetClientCertificate(convert.FrameworkToPtrString(data.ClientCertificate))
	body.SetCollectProxyNetworkData(convert.FrameworkToPtrBool(data.CollectProxyNetworkData))
	body.SetContentRegex(convert.FrameworkToPtrString(data.ContentRegex))
	credentialsRaw, d := convert.FrameworkSetToStringSlice(ctx, data.Credentials)
	diags.Append(d...)
	body.SetCredentials(credentialsRaw)
	body.SetDescription(convert.FrameworkToPtrString(data.Description))
	body.SetDesiredStatusCode(convert.FrameworkToPtrString(data.DesiredStatusCode))
	body.SetDisableScreenshot(convert.FrameworkToPtrBool(data.DisableScreenshot))
	body.SetDistributedTracing(convert.FrameworkToPtrBool(data.DistributedTracing))
	body.SetDnsOverride(convert.FrameworkToPtrString(data.DNSOverride))
	body.SetDownloadLimit(convert.FrameworkInt64ToPtrInt32(data.DownloadLimit))
	body.SetEmulatedDeviceId(convert.FrameworkToPtrString(data.EmulatedDeviceID))
	body.SetEnabled(convert.FrameworkToPtrBool(data.Enabled))
	body.SetFixedPacketRate(convert.FrameworkInt64ToPtrInt32(data.FixedPacketRate))
	body.SetFollowRedirects(convert.FrameworkToPtrBool(data.FollowRedirects))
	body.SetHttpTargetTime(convert.FrameworkInt64ToPtrInt32(data.HTTPTargetTime))
	body.SetHttpTimeLimit(convert.FrameworkInt64ToPtrInt32(data.HTTPTimeLimit))
	body.SetHttpVersion(convert.FrameworkInt64ToPtrInt32(data.HTTPVersion))
	body.SetIdentifyAgentTrafficWithUserAgent(convert.FrameworkToPtrBool(data.IdentifyAgentTrafficWithUserAgent))
	body.SetIncludeHeaders(convert.FrameworkToPtrBool(data.IncludeHeaders))
	body.SetInterval(convert.FrameworkInt64ToPtrInt32(data.Interval))
	body.SetMtuMeasurements(convert.FrameworkToPtrBool(data.MTUMeasurements))
	body.SetNumPathTraces(convert.FrameworkInt64ToPtrInt32(data.NumPathTraces))
	body.SetOverrideAgentProxy(convert.FrameworkToPtrBool(data.OverrideAgentProxy))
	body.SetOverrideProxyId(convert.FrameworkToPtrString(data.OverrideProxyID))
	pageLoadingStrategyRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestPageLoadingStrategy](data.PageLoadingStrategy, models.ParseTests_API_TestPageLoadingStrategy)
	diags.Append(d...)
	body.SetPageLoadingStrategy(pageLoadingStrategyRaw)
	body.SetPassword(convert.FrameworkToPtrString(data.Password))
	pathTraceModeRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestPathTraceMode](data.PathTraceMode, models.ParseTests_API_TestPathTraceMode)
	diags.Append(d...)
	body.SetPathTraceMode(pathTraceModeRaw)
	probeModeRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestProbeMode](data.ProbeMode, models.ParseTests_API_TestProbeMode)
	diags.Append(d...)
	body.SetProbeMode(probeModeRaw)
	protocolRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestProtocol](data.Protocol, models.ParseTests_API_TestProtocol)
	diags.Append(d...)
	body.SetProtocol(protocolRaw)
	body.SetRandomizedStartTime(convert.FrameworkToPtrBool(data.RandomizedStartTime))
	sSLVersionIDRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestSslVersionId](data.SSLVersionID, models.ParseTests_API_TestSslVersionId)
	diags.Append(d...)
	body.SetSslVersionId(sSLVersionIDRaw)
	body.SetSubinterval(convert.FrameworkInt64ToPtrInt32(data.Subinterval))
	body.SetTargetTime(convert.FrameworkInt64ToPtrInt32(data.TargetTime))
	body.SetTestName(convert.FrameworkToPtrString(data.TestName))
	body.SetTimeLimit(convert.FrameworkInt64ToPtrInt32(data.TimeLimit))
	body.SetTransactionScript(convert.FrameworkToPtrString(data.TransactionScript))
	body.SetUrl(convert.FrameworkToPtrString(data.URL))
	body.SetUseNtlm(convert.FrameworkToPtrBool(data.UseNtlm))
	body.SetUsePublicBgp(convert.FrameworkToPtrBool(data.UsePublicBGP))
	body.SetUserAgent(convert.FrameworkToPtrString(data.UserAgent))
	body.SetUsername(convert.FrameworkToPtrString(data.Username))
	vaultCredentialsRaw, d := expandTestsWebTransactionTestVaultCredentials(ctx, data.VaultCredentials)
	diags.Append(d...)
	body.SetVaultCredentials(vaultCredentialsRaw)
	body.SetVerifyCertificate(convert.FrameworkToPtrBool(data.VerifyCertificate))
	agentsRaw, d := expandWebTransactionAgents(ctx, data.Agents)
	diags.Append(d...)
	body.SetAgents(agentsRaw)

	return body, diags
}

// expandTestsWebTransactionTestVaultCredentials converts the configured TestsWebTransactionTestVaultCredentialModel values into SDK structs.
func expandTestsWebTransactionTestVaultCredentials(ctx context.Context, v types.Set) ([]models.Tests_API_TestVaultCredentialable, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []TestsWebTransactionTestVaultCredentialModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]models.Tests_API_TestVaultCredentialable, 0, len(elements))
	for _, m := range elements {
		item := models.NewTests_API_TestVaultCredential()

		item.SetSecretId(convert.FrameworkToPtrString(m.SecretID))
		targetRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestVaultCredentialTarget](m.Target, models.ParseTests_API_TestVaultCredentialTarget)
		diags.Append(d...)
		item.SetTarget(targetRaw)
		out = append(out, item)
	}

	return out, diags
}

// expandWebTransactionAgents converts the configured WebTransactionAgentModel values into SDK structs.
func expandWebTransactionAgents(ctx context.Context, v types.Set) ([]models.Tests_API_TestAgentRequestable, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []WebTransactionAgentModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]models.Tests_API_TestAgentRequestable, 0, len(elements))
	for _, m := range elements {
		item := models.NewTests_API_TestAgentRequest()

		item.SetAgentId(convert.FrameworkToPtrString(m.AgentID))
		out = append(out, item)
	}

	return out, diags
}
