// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package cloudinsights

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// IntegrationRequestBuilder builds and executes requests for operations under \cloud-insights\integration
type IntegrationRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// Aws the aws property
// returns a *IntegrationAwsRequestBuilder when successful
func (m *IntegrationRequestBuilder) Aws() *IntegrationAwsRequestBuilder {
	return NewIntegrationAwsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Azure the azure property
// returns a *IntegrationAzureRequestBuilder when successful
func (m *IntegrationRequestBuilder) Azure() *IntegrationAzureRequestBuilder {
	return NewIntegrationAzureRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// NewIntegrationRequestBuilderInternal instantiates a new IntegrationRequestBuilder and sets the default values.
func NewIntegrationRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *IntegrationRequestBuilder {
	m := &IntegrationRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/cloud-insights/integration", pathParameters),
	}
	return m
}

// NewIntegrationRequestBuilder instantiates a new IntegrationRequestBuilder and sets the default values.
func NewIntegrationRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *IntegrationRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewIntegrationRequestBuilderInternal(urlParams, requestAdapter)
}
