// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:17ccadd9f04833a0c47aa480004eff43ce664c1e4202c4da5c92d766e70cb2c7). DO NOT EDIT.

package dashboard

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/client"
	sdk "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk"
	commonschema "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/schema"
)

const (
	// TypeName is the Terraform type this resource registers as.
	TypeName = "thousandeyes_dashboard"

	// Default per-operation timeouts, in seconds. A practitioner overrides them
	// with the resource's timeouts block.
	CreateTimeout = 180
	ReadTimeout   = 180
	UpdateTimeout = 180
	DeleteTimeout = 180
)

// Compile-time assertions that this resource implements what it claims to. They
// turn a missing method into a build failure rather than a runtime surprise.
var (
	_ resource.Resource                = (*DashboardResource)(nil)
	_ resource.ResourceWithConfigure   = (*DashboardResource)(nil)
	_ resource.ResourceWithImportState = (*DashboardResource)(nil)
)

// NewDashboardResource returns the thousandeyes_dashboard resource.
func NewDashboardResource() resource.Resource {
	return &DashboardResource{}
}

// DashboardResource implements the thousandeyes_dashboard resource.
type DashboardResource struct {
	client *sdk.ThousandEyesClient
}

// Metadata returns the resource type name.
func (r *DashboardResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TypeName
}

// Configure receives the configured SDK client from the provider.
func (r *DashboardResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = client.ForResource(ctx, req, resp, TypeName)
}

// ImportState maps a terraform import into state.
func (r *DashboardResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// Schema returns the resource schema.
func (r *DashboardResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieve dashboard.",
		Attributes: map[string]schema.Attribute{
			"account_id": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "Identifier for the account group associated with a dashboard.",
				DeprecationMessage:  "The API documents this field as deprecated.",
			},
			"aid": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Identifier for the account group associated with a dashboard.",
			},
			"created_by": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "Identifier for the user that created a dashboard.",
				DeprecationMessage:  "The API documents this field as deprecated.",
			},
			"dashboard_created_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Identifier for the user that created a dashboard.",
			},
			"dashboard_modified_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Identifier for the user that last modified a dashboard.",
			},
			"dashboard_modified_date": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC date/time when a dashboard was last modified (ISO date-time format).",
			},
			"description": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "A text description of the dashboard's purpose and functionality. This information assists " +
					"users in understanding the dashboard but isn't displayed when viewing a dashboard.",
			},
			"global_filter_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Default global dashboard filter ID (obtained from `/dashboards/filters` endpoint).",
			},
			"global_override": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: "When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If " +
					"set to `false`, the the widget's timespan is used.",
				DeprecationMessage: "The API documents this field as deprecated.",
			},
			"id": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: "Identifier of a dashboard. Named `id` per the import convention; the wire field stays " +
					"dashboardId.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"is_built_in": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: "Indicates if a dashboard is built-in. True for built-in dashboards, false for user-created " +
					"dashboards.",
			},
			"is_default_for_account": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: "Indicates whether this dashboard is the account group's default. True for default, false " +
					"if not.",
			},
			"is_default_for_user": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Indicates whether this dashboard is the user's default. True for default, false if not.",
			},
			"is_global_override": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "When set to `true`, the defaultTimespan is used and overrides the widget's timespan. If " +
					"set to `false`, the the widget's timespan is used. <!-- probed:7.0.98-t1785769218413 --> " +
					"Observed: the API assigns false when this is omitted. Observed: the API assigns false when " +
					"this is omitted from an update. Omitting this field from an update resets it rather than " +
					"preserving the stored value. <!-- /probed -->",
			},
			"is_migrated_report": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "True if this dashboard was previously a report.",
			},
			"is_private": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "A dashboard can be viewed by other users in the account. If true, only the creator of the " +
					"dashboard may view it. If false, all users in the same account may view it. <!-- " +
					"probed:7.0.98-t1785769218413 --> Observed: the API assigns false when this is omitted. " +
					"Observed: the API assigns false when this is omitted from an update. Omitting this field " +
					"from an update resets it rather than preserving the stored value. <!-- /probed -->",
			},
			"layout": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"details": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"widget_positioning": schema.SetNestedAttribute{
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"h": schema.Int64Attribute{
											Required:            true,
											MarkdownDescription: "Height in grid units.",
										},
										"id": schema.StringAttribute{
											Optional:            true,
											MarkdownDescription: "Identifier of the widget this position applies to.",
										},
										"w": schema.Int64Attribute{
											Required:            true,
											MarkdownDescription: "Width in grid units.",
										},
										"x": schema.Int64Attribute{
											Required:            true,
											MarkdownDescription: "Horizontal position.",
										},
										"y": schema.Int64Attribute{
											Required:            true,
											MarkdownDescription: "Vertical position.",
										},
									},
								},
								Optional:            true,
								MarkdownDescription: "List of widget positions within the layout.",
							},
						},
						Optional:            true,
						MarkdownDescription: "Layout details including widget positioning.",
					},
					"layout_id": schema.StringAttribute{
						Optional:            true,
						MarkdownDescription: "Unique identifier for the layout.",
					},
					"type": schema.StringAttribute{
						Required: true,
						MarkdownDescription: "Type of the layout. <!-- probed:7.0.98-t1785769218413 --> Values accepted here: `grid`, " +
							"`vertical`. Observed: the API assigns \"vertical\" when this is omitted. The API accepted a " +
							"value from outside the documented set, so no OneOf validator is generated for this " +
							"attribute. <!-- /probed -->",
					},
				},
				Optional:            true,
				MarkdownDescription: "Dashboard layout configuration for arranging widgets.",
			},
			"migrated_report": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "True if this dashboard was previously a report.",
				DeprecationMessage:  "The API documents this field as deprecated.",
			},
			"modified_by": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "Identifier for the user that last modified a dashboard.",
				DeprecationMessage:  "The API documents this field as deprecated.",
			},
			"modified_date": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC date/time when a dashboard was last modified.",
				DeprecationMessage:  "The API documents this field as deprecated.",
			},
			"refresh_rate": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Auto-refresh interval for a dashboard. Use `off` to disable auto-refresh.",
				Validators: []validator.String{
					stringvalidator.OneOf("off", "2m", "5m", "10m", "15m", "30m", "60m"),
				},
			},
			"title": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Title of a dashboard.",
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": commonschema.ResourceTimeouts(ctx),
		},
	}
}
