// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:c2f31b5ceae54901082d303a3578916d3c0f177b0c43d44a1e482ca80a1e9dd1). DO NOT EDIT.

package tests_dns_server

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/convert"
)

// constructResource maps Terraform configuration onto the API's request body.
//
// Only writable attributes appear here. A computed attribute has no expand
// conversion, so it cannot be sent by construction rather than by discipline.
func constructResource(ctx context.Context, data *TestsDNSServerResourceModel) (*models.Tests_API_DnsServerTestRequest, diag.Diagnostics) {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)
	tflog.Debug(ctx, "constructing request body", map[string]any{"resource": TypeName})

	body := models.NewTests_API_DnsServerTestRequest()

	body.SetAlertsEnabled(convert.FrameworkToPtrBool(data.AlertsEnabled))
	body.SetBandwidthMeasurements(convert.FrameworkToPtrBool(data.BandwidthMeasurements))
	body.SetBgpMeasurements(convert.FrameworkToPtrBool(data.BGPMeasurements))
	body.SetDescription(convert.FrameworkToPtrString(data.Description))
	dNSQueryClassRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_DnsQueryClass](data.DNSQueryClass, models.ParseTests_API_DnsQueryClass)
	diags.Append(d...)
	body.SetDnsQueryClass(dNSQueryClassRaw)
	dNSServersRaw, d := convert.FrameworkSetToStringSlice(ctx, data.DNSServers)
	diags.Append(d...)
	body.SetDnsServers(dNSServersRaw)
	dNSTransportProtocolRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestDnsTransportProtocol](data.DNSTransportProtocol, models.ParseTests_API_TestDnsTransportProtocol)
	diags.Append(d...)
	body.SetDnsTransportProtocol(dNSTransportProtocolRaw)
	body.SetDomain(convert.FrameworkToPtrString(data.Domain))
	body.SetEnabled(convert.FrameworkToPtrBool(data.Enabled))
	body.SetFixedPacketRate(convert.FrameworkInt64ToPtrInt32(data.FixedPacketRate))
	body.SetInterval(convert.FrameworkInt64ToPtrInt32(data.Interval))
	ipv6PolicyRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestIpv6Policy](data.Ipv6Policy, models.ParseTests_API_TestIpv6Policy)
	diags.Append(d...)
	body.SetIpv6Policy(ipv6PolicyRaw)
	body.SetMtuMeasurements(convert.FrameworkToPtrBool(data.MTUMeasurements))
	body.SetNumPathTraces(convert.FrameworkInt64ToPtrInt32(data.NumPathTraces))
	pathTraceModeRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestPathTraceMode](data.PathTraceMode, models.ParseTests_API_TestPathTraceMode)
	diags.Append(d...)
	body.SetPathTraceMode(pathTraceModeRaw)
	probeModeRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestProbeMode](data.ProbeMode, models.ParseTests_API_TestProbeMode)
	diags.Append(d...)
	body.SetProbeMode(probeModeRaw)
	protocolRaw, d := convert.FrameworkToKiotaEnum[models.Tests_API_TestProtocol](data.Protocol, models.ParseTests_API_TestProtocol)
	diags.Append(d...)
	body.SetProtocol(protocolRaw)
	body.SetRandomizedStartTime(convert.FrameworkToPtrBool(data.RandomizedStartTime))
	body.SetRecursiveQueries(convert.FrameworkToPtrBool(data.RecursiveQueries))
	body.SetTestName(convert.FrameworkToPtrString(data.TestName))
	body.SetUsePublicBgp(convert.FrameworkToPtrBool(data.UsePublicBGP))
	agentsRaw, d := expandDnsServerAgents(ctx, data.Agents)
	diags.Append(d...)
	body.SetAgents(agentsRaw)

	return body, diags
}

// expandDnsServerAgents converts the configured DnsServerAgentModel values into SDK structs.
func expandDnsServerAgents(ctx context.Context, v types.Set) ([]models.Tests_API_TestAgentRequestable, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []DnsServerAgentModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]models.Tests_API_TestAgentRequestable, 0, len(elements))
	for _, m := range elements {
		item := models.NewTests_API_TestAgentRequest()

		item.SetAgentId(convert.FrameworkToPtrString(m.AgentID))
		out = append(out, item)
	}

	return out, diags
}
