// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:0705a06d171a00d2bf9756d028fa63d1589968e3dae11ee9272c1c4039c2d00f). DO NOT EDIT.

package endpoint_tests_scheduled_tests_http_server

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// EndpointTestsScheduledTestsHTTPServerResourceModel is the Terraform state for a thousandeyes_endpoint_tests_http_server.
//
// Field order follows the schema, and the timeouts value is last.
type EndpointTestsScheduledTestsHTTPServerResourceModel struct {
	AgentSelectorType     types.String   `tfsdk:"agent_selector_type"`
	Agents                types.Set      `tfsdk:"agents"`
	AID                   types.String   `tfsdk:"aid"`
	AuthType              types.String   `tfsdk:"auth_type"`
	CreatedDate           types.String   `tfsdk:"created_date"`
	EndpointAgentLabels   types.Set      `tfsdk:"endpoint_agent_labels"`
	FollowRedirects       types.Bool     `tfsdk:"follow_redirects"`
	HasPathTraceInSession types.Bool     `tfsdk:"has_path_trace_in_session"`
	HasPing               types.Bool     `tfsdk:"has_ping"`
	HasTraceroute         types.Bool     `tfsdk:"has_traceroute"`
	HTTPTargetTime        types.Int64    `tfsdk:"http_target_time"`
	HTTPTimeLimit         types.Int64    `tfsdk:"http_time_limit"`
	HTTPVersion           types.Int64    `tfsdk:"http_version"`
	ID                    types.String   `tfsdk:"id"`
	Interval              types.Int64    `tfsdk:"interval"`
	IPVersion             types.String   `tfsdk:"ip_version"`
	IsEnabled             types.Bool     `tfsdk:"is_enabled"`
	IsPrioritized         types.Bool     `tfsdk:"is_prioritized"`
	IsSavedEvent          types.Bool     `tfsdk:"is_saved_event"`
	Labels                types.Set      `tfsdk:"labels"`
	MaxMachines           types.Int64    `tfsdk:"max_machines"`
	ModifiedDate          types.String   `tfsdk:"modified_date"`
	NetworkMeasurements   types.Bool     `tfsdk:"network_measurements"`
	Password              types.String   `tfsdk:"password"`
	Port                  types.Int64    `tfsdk:"port"`
	Protocol              types.String   `tfsdk:"protocol"`
	Server                types.String   `tfsdk:"server"`
	SSLVersion            types.String   `tfsdk:"ssl_version"`
	SSLVersionID          types.String   `tfsdk:"ssl_version_id"`
	TagIDs                types.Set      `tfsdk:"tag_ids"`
	TargetResponseTime    types.Int64    `tfsdk:"target_response_time"`
	TCPProbeMode          types.String   `tfsdk:"tcp_probe_mode"`
	TestID                types.String   `tfsdk:"test_id"`
	TestName              types.String   `tfsdk:"test_name"`
	Type                  types.String   `tfsdk:"type"`
	URL                   types.String   `tfsdk:"url"`
	UseNtlm               types.Bool     `tfsdk:"use_ntlm"`
	Username              types.String   `tfsdk:"username"`
	VerifyCertificate     types.Bool     `tfsdk:"verify_certificate"`
	Timeouts              timeouts.Value `tfsdk:"timeouts"`
}

// EndpointTestsScheduledTestsHTTPServerTestLabelsModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type EndpointTestsScheduledTestsHTTPServerTestLabelsModel struct {
	IsBuiltin types.Bool   `tfsdk:"is_builtin"`
	LabelID   types.String `tfsdk:"label_id"`
	Name      types.String `tfsdk:"name"`
}

// endpointTestsScheduledTestsHTTPServerTestLabelsAttrTypes describes EndpointTestsScheduledTestsHTTPServerTestLabelsModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var endpointTestsScheduledTestsHTTPServerTestLabelsAttrTypes = map[string]attr.Type{
	"is_builtin": types.BoolType,
	"label_id":   types.StringType,
	"name":       types.StringType,
}

var endpointTestsScheduledTestsHTTPServerTestLabelsObjectType = types.ObjectType{AttrTypes: endpointTestsScheduledTestsHTTPServerTestLabelsAttrTypes}
