# Code generated by tfpfgen from blueprints/thousandeyes
# (sha256:0705a06d171a00d2bf9756d028fa63d1589968e3dae11ee9272c1c4039c2d00f). DO NOT EDIT.

# The widest configuration the evidence supports: every writable attribute with a derivable
# value, chosen by the same derivation the rehearsal probe sends to the live API.
#
# Regenerated and policed, deliberately. This file used to be a hand-owned scaffold, and
# hand edits are how its values drifted from the generated assertions -- the checks derive
# from the blueprint, so the blueprint is where a value is corrected: an accFixture hint for
# something only a human knows, recorded behaviour for everything the probe observed. What
# could not be derived is listed inside the block, each with the reason.

resource "thousandeyes_tests_web_transaction" "test" {
  # Where a value came from.
  #
  # auth_type: documented; unprobed
  #
  # bandwidth_measurements: curated in the blueprint's accFixture; the generator cannot derive
  # it
  #
  # browser_language: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # chrome_options: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # collect_proxy_network_data: curated in the blueprint's accFixture; the generator cannot
  # derive it
  #
  # desired_status_code: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # dns_override: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # fixed_packet_rate: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # interval: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # num_path_traces: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # page_loading_strategy: documented; unprobed
  #
  # path_trace_mode: documented; unprobed
  #
  # probe_mode: documented; unprobed
  #
  # protocol: documented; unprobed
  #
  # randomized_start_time: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # ssl_version_id: documented; unprobed
  #
  # subinterval: documented; unprobed
  #
  # url: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # use_ntlm: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # user_agent: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # agents: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # Not filled in, because no correct value could be derived. Each of these is optional, so this
  # configuration is valid as it stands -- but it is testing less than it could.
  #
  # client_certificate: it is credential-shaped, and a generated fixture must not invent values
  # that read as secrets; supply one through accFixture if the test needs it
  #
  # credentials: its elements have no derivable value: it is credential-shaped, and a generated
  # fixture must not invent values that read as secrets; supply one through accFixture if the
  # test needs it
  #
  # emulated_device_id: it references an object that must already exist, which a synthesised
  # value cannot name; supply one through accFixture if the test has the object
  #
  # override_proxy_id: it references an object that must already exist, which a synthesised
  # value cannot name; supply one through accFixture if the test has the object
  #
  # password: it is credential-shaped, and a generated fixture must not invent values that read
  # as secrets; supply one through accFixture if the test needs it
  #
  # username: it is credential-shaped, and a generated fixture must not invent values that read
  # as secrets; supply one through accFixture if the test needs it
  #
  # vault_credentials: a nested object's members may be identifiers of objects that must already
  # exist, and nothing in the specification says whether they are
  alerts_enabled                         = true
  allow_geolocation                      = true
  allow_mic_and_camera                   = true
  allow_unsafe_legacy_renegotiation      = true
  auth_type                              = "none"
  bandwidth_measurements                 = false
  bgp_measurements                       = true
  block_domains                          = "tfacc-block-domains"
  browser_language                       = "en-US"
  chrome_options                         = "--disable-gpu"
  collect_proxy_network_data             = false
  content_regex                          = "tfacc-content-regex"
  description                            = "tfacc-description"
  desired_status_code                    = "200"
  disable_screenshot                     = true
  distributed_tracing                    = true
  dns_override                           = "8.8.8.8"
  download_limit                         = 1
  enabled                                = true
  fixed_packet_rate                      = 50
  follow_redirects                       = true
  http_target_time                       = 100
  http_time_limit                        = 5
  http_version                           = 1
  identify_agent_traffic_with_user_agent = true
  include_headers                        = true
  interval                               = 3600
  mtu_measurements                       = true
  num_path_traces                        = 3
  override_agent_proxy                   = true
  page_loading_strategy                  = "normal"
  path_trace_mode                        = "classic"
  probe_mode                             = "auto"
  protocol                               = "tcp"
  randomized_start_time                  = false
  ssl_version_id                         = "0"
  subinterval                            = "60"
  target_time                            = 1
  test_name                              = "tfacc-test-name"
  time_limit                             = 5
  transaction_script                     = "tfacc-transaction-script"
  url                                    = "https://www.example.com"
  use_ntlm                               = false
  use_public_bgp                         = true
  user_agent                             = "tfacc (ThousandEyes Agent)"
  verify_certificate                     = true
  agents                                 = [{ agent_id = "3" }]
}
