// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package internetinsights

import (
	"context"

	ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3 "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CatalogProvidersFilterRequestBuilder builds and executes requests for operations under \internet-insights\catalog\providers\filter
type CatalogProvidersFilterRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// CatalogProvidersFilterRequestBuilderPostQueryParameters returns a list of catalog providers using the specified filters. Returns high-level information about each catalog provider. For more details about a specific provider, call the Get a catalog provider endpoint.<b>Note:</b> Support for pagination will be added in the future.
type CatalogProvidersFilterRequestBuilderPostQueryParameters struct {
	// A unique identifier associated with your account group. You can retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note that you must be assigned to the target account group. Specifying this parameter without being assigned to the target account group will result in an error response.
	Aid *string "uriparametername:\"aid\""
}

// NewCatalogProvidersFilterRequestBuilderInternal instantiates a new CatalogProvidersFilterRequestBuilder and sets the default values.
func NewCatalogProvidersFilterRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CatalogProvidersFilterRequestBuilder {
	m := &CatalogProvidersFilterRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/internet-insights/catalog/providers/filter{?aid*}", pathParameters),
	}
	return m
}

// NewCatalogProvidersFilterRequestBuilder instantiates a new CatalogProvidersFilterRequestBuilder and sets the default values.
func NewCatalogProvidersFilterRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CatalogProvidersFilterRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewCatalogProvidersFilterRequestBuilderInternal(urlParams, requestAdapter)
}

// Post returns a list of catalog providers using the specified filters. Returns high-level information about each catalog provider. For more details about a specific provider, call the Get a catalog provider endpoint.<b>Note:</b> Support for pagination will be added in the future.
// returns a Internet_Insights_API_ApiCatalogProviderResponseable when successful
// returns a Internet_Insights_API_ValidationError error when the service returns a 400 status code
// returns a Internet_Insights_API_UnauthorizedError error when the service returns a 401 status code
// returns a Internet_Insights_API_Error error when the service returns a 403 status code
// returns a Internet_Insights_API_Error error when the service returns a 404 status code
// returns a Internet_Insights_API_Error error when the service returns a 429 status code
// returns a Internet_Insights_API_Error error when the service returns a 500 status code
// returns a Internet_Insights_API_Error error when the service returns a 502 status code
func (m *CatalogProvidersFilterRequestBuilder) Post(ctx context.Context, body ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Internet_Insights_API_ApiCatalogProviderFilterable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[CatalogProvidersFilterRequestBuilderPostQueryParameters]) (ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Internet_Insights_API_ApiCatalogProviderResponseable, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateInternet_Insights_API_ValidationErrorFromDiscriminatorValue,
		"401": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateInternet_Insights_API_UnauthorizedErrorFromDiscriminatorValue,
		"403": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateInternet_Insights_API_ErrorFromDiscriminatorValue,
		"404": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateInternet_Insights_API_ErrorFromDiscriminatorValue,
		"429": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateInternet_Insights_API_ErrorFromDiscriminatorValue,
		"500": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateInternet_Insights_API_ErrorFromDiscriminatorValue,
		"502": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateInternet_Insights_API_ErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateInternet_Insights_API_ApiCatalogProviderResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Internet_Insights_API_ApiCatalogProviderResponseable), nil
}

// ToPostRequestInformation returns a list of catalog providers using the specified filters. Returns high-level information about each catalog provider. For more details about a specific provider, call the Get a catalog provider endpoint.<b>Note:</b> Support for pagination will be added in the future.
// returns a *RequestInformation when successful
func (m *CatalogProvidersFilterRequestBuilder) ToPostRequestInformation(ctx context.Context, body ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Internet_Insights_API_ApiCatalogProviderFilterable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[CatalogProvidersFilterRequestBuilderPostQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/hal+json")
	err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
	if err != nil {
		return nil, err
	}
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CatalogProvidersFilterRequestBuilder when successful
func (m *CatalogProvidersFilterRequestBuilder) WithUrl(rawUrl string) *CatalogProvidersFilterRequestBuilder {
	return NewCatalogProvidersFilterRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
