// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:17ccadd9f04833a0c47aa480004eff43ce664c1e4202c4da5c92d766e70cb2c7). DO NOT EDIT.

package stream

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/convert"
)

// constructResource maps Terraform configuration onto the API's request body.
//
// Only writable attributes appear here. A computed attribute has no expand
// conversion, so it cannot be sent by construction rather than by discipline.
func constructResource(ctx context.Context, data *StreamResourceModel) (*models.ThousandEyes_for_OpenTelemetry_API_Stream, diag.Diagnostics) {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)
	tflog.Debug(ctx, "constructing request body", map[string]any{"resource": TypeName})

	body := models.NewThousandEyes_for_OpenTelemetry_API_Stream()

	body.SetEnabled(convert.FrameworkToPtrBool(data.Enabled))
	endpointAgentLabelRaw, d := expandStreamEndpointAgentLabels(ctx, data.EndpointAgentLabel)
	diags.Append(d...)
	body.SetEndpointAgentLabel(endpointAgentLabelRaw)
	endpointAgentTagRaw, d := expandStreamEndpointAgentTags(ctx, data.EndpointAgentTag)
	diags.Append(d...)
	body.SetEndpointAgentTag(endpointAgentTagRaw)
	exporterConfigRaw, d := expandStreamExporterConfig(ctx, data.ExporterConfig)
	diags.Append(d...)
	body.SetExporterConfig(exporterConfigRaw)
	filtersRaw, d := expandStreamFilters(ctx, data.Filters)
	diags.Append(d...)
	body.SetFilters(filtersRaw)
	inputConfigRaw, d := expandStreamInputConfig(ctx, data.InputConfig)
	diags.Append(d...)
	body.SetInputConfig(inputConfigRaw)
	body.SetStreamEndpointUrl(convert.FrameworkToPtrString(data.StreamEndpointURL))
	tagMatchRaw, d := expandStreamTagMatches(ctx, data.TagMatch)
	diags.Append(d...)
	body.SetTagMatch(tagMatchRaw)
	testMatchRaw, d := expandStreamTestMatches(ctx, data.TestMatch)
	diags.Append(d...)
	body.SetTestMatch(testMatchRaw)

	return body, diags
}

// constructResourceUpdate builds the update request body.
//
// A separate function because this SDK gives update its own request type. The
// assignment list is create's except where an attribute declares updateExpand --
// an SDK whose update type spells a field differently from create's -- and the
// bindings check has proven every assigned field exists on its own type.
func constructResourceUpdate(ctx context.Context, data *StreamResourceModel) (*models.ThousandEyes_for_OpenTelemetry_API_PutStream, diag.Diagnostics) {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)
	tflog.Debug(ctx, "constructing update request body", map[string]any{"resource": TypeName})

	body := models.NewThousandEyes_for_OpenTelemetry_API_PutStream()

	body.SetEnabled(convert.FrameworkToPtrBool(data.Enabled))
	endpointAgentLabelRaw, d := expandStreamEndpointAgentLabels(ctx, data.EndpointAgentLabel)
	diags.Append(d...)
	body.SetEndpointAgentLabel(endpointAgentLabelRaw)
	endpointAgentTagRaw, d := expandStreamEndpointAgentTags(ctx, data.EndpointAgentTag)
	diags.Append(d...)
	body.SetEndpointAgentTag(endpointAgentTagRaw)
	exporterConfigRaw, d := expandStreamExporterConfig(ctx, data.ExporterConfig)
	diags.Append(d...)
	body.SetExporterConfig(exporterConfigRaw)
	filtersRaw, d := expandStreamFilters(ctx, data.Filters)
	diags.Append(d...)
	body.SetFilters(filtersRaw)
	inputConfigRaw, d := expandStreamInputConfig(ctx, data.InputConfig)
	diags.Append(d...)
	body.SetInputConfig(inputConfigRaw)
	body.SetStreamEndpointUrl(convert.FrameworkToPtrString(data.StreamEndpointURL))
	tagMatchRaw, d := expandStreamTagMatches(ctx, data.TagMatch)
	diags.Append(d...)
	body.SetTagMatch(tagMatchRaw)
	testMatchRaw, d := expandStreamTestMatches(ctx, data.TestMatch)
	diags.Append(d...)
	body.SetTestMatch(testMatchRaw)

	return body, diags
}

// expandStreamEndpointAgentLabels converts the configured StreamEndpointAgentLabelModel values into SDK structs.
func expandStreamEndpointAgentLabels(ctx context.Context, v types.Set) ([]models.ThousandEyes_for_OpenTelemetry_API_EndpointAgentLabelable, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []StreamEndpointAgentLabelModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]models.ThousandEyes_for_OpenTelemetry_API_EndpointAgentLabelable, 0, len(elements))
	for _, m := range elements {
		item := models.NewThousandEyes_for_OpenTelemetry_API_EndpointAgentLabel()

		item.SetId(convert.FrameworkToPtrString(m.ID))
		out = append(out, item)
	}

	return out, diags
}

// expandStreamEndpointAgentTags converts the configured StreamEndpointAgentTagModel values into SDK structs.
func expandStreamEndpointAgentTags(ctx context.Context, v types.Set) ([]models.ThousandEyes_for_OpenTelemetry_API_EndpointAgentTagable, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []StreamEndpointAgentTagModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]models.ThousandEyes_for_OpenTelemetry_API_EndpointAgentTagable, 0, len(elements))
	for _, m := range elements {
		item := models.NewThousandEyes_for_OpenTelemetry_API_EndpointAgentTag()

		item.SetId(convert.FrameworkToPtrString(m.ID))
		out = append(out, item)
	}

	return out, diags
}

// expandStreamExporterConfig converts the configured StreamExporterConfigModel values into SDK structs.
func expandStreamExporterConfig(ctx context.Context, v types.Object) (models.ThousandEyes_for_OpenTelemetry_API_ExporterConfigable, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var m StreamExporterConfigModel
	diags.Append(v.As(ctx, &m, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return nil, diags
	}

	item := models.NewThousandEyes_for_OpenTelemetry_API_ExporterConfig()

	authorizationRaw, d := expandStreamExporterConfigAuthorization(ctx, m.Authorization)
	diags.Append(d...)
	item.SetAuthorization(authorizationRaw)
	splunkHecRaw, d := expandStreamExporterConfigSplunkHec(ctx, m.SplunkHec)
	diags.Append(d...)
	item.SetSplunkHec(splunkHecRaw)

	return item, diags
}

// expandStreamExporterConfigAuthorization converts the configured StreamExporterConfigAuthorizationModel values into SDK structs.
func expandStreamExporterConfigAuthorization(ctx context.Context, v types.Object) (models.ThousandEyes_for_OpenTelemetry_API_ExporterConfigAuthorizationable, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var m StreamExporterConfigAuthorizationModel
	diags.Append(v.As(ctx, &m, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return nil, diags
	}

	item := models.NewThousandEyes_for_OpenTelemetry_API_ExporterConfigAuthorization()

	oAuth2Raw, d := expandStreamExporterConfigOAuth2(ctx, m.OAuth2)
	diags.Append(d...)
	item.SetOAuth2(oAuth2Raw)

	return item, diags
}

// expandStreamExporterConfigOAuth2 converts the configured StreamExporterConfigOAuth2Model values into SDK structs.
func expandStreamExporterConfigOAuth2(ctx context.Context, v types.Object) (models.ThousandEyes_for_OpenTelemetry_API_ExporterConfigOAuth2able, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var m StreamExporterConfigOAuth2Model
	diags.Append(v.As(ctx, &m, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return nil, diags
	}

	item := models.NewThousandEyes_for_OpenTelemetry_API_ExporterConfigOAuth2()

	item.SetClientId(convert.FrameworkToPtrString(m.ClientID))
	item.SetClientSecret(convert.FrameworkToPtrString(m.ClientSecret))
	scopesRaw, d := convert.FrameworkSetToStringSlice(ctx, m.Scopes)
	diags.Append(d...)
	item.SetScopes(scopesRaw)
	item.SetTokenUrl(convert.FrameworkToPtrString(m.TokenURL))

	return item, diags
}

// expandStreamExporterConfigSplunkHec converts the configured StreamExporterConfigSplunkHecModel values into SDK structs.
func expandStreamExporterConfigSplunkHec(ctx context.Context, v types.Object) (models.ThousandEyes_for_OpenTelemetry_API_ExporterConfigSplunkHecable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var m StreamExporterConfigSplunkHecModel
	diags.Append(v.As(ctx, &m, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return nil, diags
	}

	item := models.NewThousandEyes_for_OpenTelemetry_API_ExporterConfigSplunkHec()

	item.SetIndex(convert.FrameworkToPtrString(m.Index))
	item.SetSource(convert.FrameworkToPtrString(m.Source))
	item.SetSourceType(convert.FrameworkToPtrString(m.SourceType))
	item.SetToken(convert.FrameworkToPtrString(m.Token))

	return item, diags
}

// expandStreamFilters converts the configured StreamFiltersModel values into SDK structs.
func expandStreamFilters(ctx context.Context, v types.Object) (models.ThousandEyes_for_OpenTelemetry_API_Filtersable, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var m StreamFiltersModel
	diags.Append(v.As(ctx, &m, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return nil, diags
	}

	item := models.NewThousandEyes_for_OpenTelemetry_API_Filters()

	testTypesRaw, d := expandStreamFiltersTestTypes(ctx, m.TestTypes)
	diags.Append(d...)
	item.SetTestTypes(testTypesRaw)

	return item, diags
}

// expandStreamFiltersTestTypes converts the configured StreamFiltersTestTypesModel values into SDK structs.
func expandStreamFiltersTestTypes(ctx context.Context, v types.Object) (models.ThousandEyes_for_OpenTelemetry_API_FiltersTestTypesable, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var m StreamFiltersTestTypesModel
	diags.Append(v.As(ctx, &m, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return nil, diags
	}

	item := models.NewThousandEyes_for_OpenTelemetry_API_FiltersTestTypes()

	valuesRaw, d := convert.FrameworkSetToKiotaEnumSlice[models.ThousandEyes_for_OpenTelemetry_API_TestType](ctx, m.Values, models.ParseThousandEyes_for_OpenTelemetry_API_TestType)
	diags.Append(d...)
	item.SetValues(valuesRaw)

	return item, diags
}

// expandStreamInputConfig converts the configured StreamInputConfigModel values into SDK structs.
func expandStreamInputConfig(ctx context.Context, v types.Object) (models.ThousandEyes_for_OpenTelemetry_API_InputConfigable, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var m StreamInputConfigModel
	diags.Append(v.As(ctx, &m, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return nil, diags
	}

	item := models.NewThousandEyes_for_OpenTelemetry_API_InputConfig()

	metricRaw, d := expandStreamInputConfigMetric(ctx, m.Metric)
	diags.Append(d...)
	item.SetMetric(metricRaw)

	return item, diags
}

// expandStreamInputConfigMetric converts the configured StreamInputConfigMetricModel values into SDK structs.
func expandStreamInputConfigMetric(ctx context.Context, v types.Object) (models.ThousandEyes_for_OpenTelemetry_API_InputConfigMetricable, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var m StreamInputConfigMetricModel
	diags.Append(v.As(ctx, &m, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return nil, diags
	}

	item := models.NewThousandEyes_for_OpenTelemetry_API_InputConfigMetric()

	connectedDevicesRaw, d := expandStreamConnectedDevices(ctx, m.ConnectedDevices)
	diags.Append(d...)
	item.SetConnectedDevices(connectedDevicesRaw)

	return item, diags
}

// expandStreamConnectedDevices converts the configured StreamConnectedDevicesModel values into SDK structs.
func expandStreamConnectedDevices(ctx context.Context, v types.Object) (models.ThousandEyes_for_OpenTelemetry_API_ConnectedDevicesable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var m StreamConnectedDevicesModel
	diags.Append(v.As(ctx, &m, basetypes.ObjectAsOptions{})...)
	if diags.HasError() {
		return nil, diags
	}

	item := models.NewThousandEyes_for_OpenTelemetry_API_ConnectedDevices()

	item.SetEnabled(convert.FrameworkToPtrBool(m.Enabled))

	return item, diags
}

// expandStreamTagMatches converts the configured StreamTagMatchModel values into SDK structs.
func expandStreamTagMatches(ctx context.Context, v types.Set) ([]models.ThousandEyes_for_OpenTelemetry_API_TagMatchable, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []StreamTagMatchModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]models.ThousandEyes_for_OpenTelemetry_API_TagMatchable, 0, len(elements))
	for _, m := range elements {
		item := models.NewThousandEyes_for_OpenTelemetry_API_TagMatch()

		item.SetKey(convert.FrameworkToPtrString(m.Key))
		item.SetValue(convert.FrameworkToPtrString(m.Value))
		out = append(out, item)
	}

	return out, diags
}

// expandStreamTestMatches converts the configured StreamTestMatchModel values into SDK structs.
func expandStreamTestMatches(ctx context.Context, v types.Set) ([]models.ThousandEyes_for_OpenTelemetry_API_TestMatchable, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []StreamTestMatchModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]models.ThousandEyes_for_OpenTelemetry_API_TestMatchable, 0, len(elements))
	for _, m := range elements {
		item := models.NewThousandEyes_for_OpenTelemetry_API_TestMatch()

		domainRaw, d := convert.FrameworkToKiotaEnum[models.ThousandEyes_for_OpenTelemetry_API_TestMatchDomain](m.Domain, models.ParseThousandEyes_for_OpenTelemetry_API_TestMatchDomain)
		diags.Append(d...)
		item.SetDomain(domainRaw)
		item.SetId(convert.FrameworkToPtrString(m.ID))
		out = append(out, item)
	}

	return out, diags
}
