// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:c2f31b5ceae54901082d303a3578916d3c0f177b0c43d44a1e482ca80a1e9dd1). DO NOT EDIT.

package tests_agent_to_agent

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/client"
	sdk "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk"
	commonschema "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/schema"
)

const (
	// TypeName is the Terraform type this resource registers as.
	TypeName = "thousandeyes_tests_agent_to_agent"

	// Default per-operation timeouts, in seconds. A practitioner overrides them
	// with the resource's timeouts block.
	CreateTimeout = 180
	ReadTimeout   = 180
	UpdateTimeout = 180
	DeleteTimeout = 180
)

// Compile-time assertions that this resource implements what it claims to. They
// turn a missing method into a build failure rather than a runtime surprise.
var (
	_ resource.Resource                = (*TestsAgentToAgentResource)(nil)
	_ resource.ResourceWithConfigure   = (*TestsAgentToAgentResource)(nil)
	_ resource.ResourceWithImportState = (*TestsAgentToAgentResource)(nil)
)

// NewTestsAgentToAgentResource returns the thousandeyes_tests_agent_to_agent resource.
func NewTestsAgentToAgentResource() resource.Resource {
	return &TestsAgentToAgentResource{}
}

// TestsAgentToAgentResource implements the thousandeyes_tests_agent_to_agent resource.
type TestsAgentToAgentResource struct {
	client *sdk.ThousandEyesClient
}

// Metadata returns the resource type name.
func (r *TestsAgentToAgentResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TypeName
}

// Configure receives the configured SDK client from the provider.
func (r *TestsAgentToAgentResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = client.ForResource(ctx, req, resp, TypeName)
}

// ImportState maps a terraform import into state.
func (r *TestsAgentToAgentResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// Schema returns the resource schema.
func (r *TestsAgentToAgentResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Get Agent to Agent test.",
		Attributes: map[string]schema.Attribute{
			"alerts_enabled": schema.BoolAttribute{
				Optional:            true,
				MarkdownDescription: "Indicates if alerts are enabled.",
			},
			"bgp_measurements": schema.BoolAttribute{
				Optional: true,
				MarkdownDescription: "Set to `true` to enable bgp measurements. <!-- probed:static --> The SDK's encoding drops " +
					"this type's zero value (omitempty), so configuring false, 0 or \"\" silently becomes an " +
					"omission. <!-- /probed -->",
			},
			"created_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "User that created the test.",
			},
			"created_date": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC created date (ISO date-time format).",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "A description of the test.",
			},
			"direction": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "Direction of the test, which affects how results are shown. <!-- probed:static --> The " +
					"SDK's encoding drops this type's zero value (omitempty), so configuring false, 0 or \"\" " +
					"silently becomes an omission. <!-- /probed -->",
				Validators: []validator.String{
					stringvalidator.OneOf("to-target", "from-target", "bidirectional"),
				},
			},
			"dscp": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "DSCP label.",
			},
			"dscp_id": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "DSCP ID [to see list for acceptable " +
					"values](https://docs.thousandeyes.com/product-documentation/tests/dscp-options-in-network-tests) " +
					"<!-- probed:static --> The SDK's encoding drops this type's zero value (omitempty), so " +
					"configuring false, 0 or \"\" silently becomes an omission. <!-- /probed -->",
				Validators: []validator.String{
					stringvalidator.OneOf("0", "8", "16", "24", "32", "40", "48", "56", "10", "12", "14", "18", "20", "22", "26", "28", "30", "34", "36", "38", "46", "44"),
				},
			},
			"enabled": schema.BoolAttribute{
				Optional: true,
				MarkdownDescription: "Test is enabled. <!-- probed:static --> The SDK's encoding drops this type's zero value " +
					"(omitempty), so configuring false, 0 or \"\" silently becomes an omission. <!-- /probed -->",
			},
			"fixed_packet_rate": schema.Int64Attribute{
				Optional: true,
				MarkdownDescription: "Sets packets rate sent to measure the network in packets per second. <!-- probed:static " +
					"--> The SDK's encoding drops this type's zero value (omitempty), so configuring false, 0 " +
					"or \"\" silently becomes an omission. <!-- /probed -->",
				Validators: []validator.Int64{
					int64validator.Between(0, 100),
				},
			},
			"interval": schema.Int64Attribute{
				Optional: true,
				MarkdownDescription: "Interval between test runs in seconds. Documented intervals, in seconds: `60`, `120`, " +
					"`300`, `600`, `900`, `1800`, `3600`. The request carries this field unconditionally, so " +
					"omitting it sends zero, which the API refuses (the 2026-08-03 scheduled acceptance run).",
			},
			"live_share": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Indicates if the test is shared with the account group.",
			},
			"modified_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "User that modified the test.",
			},
			"modified_date": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC last modification date (ISO date-time format).",
			},
			"mss": schema.Int64Attribute{
				Optional:            true,
				MarkdownDescription: "Maximum segment size, in bytes.",
				Validators: []validator.Int64{
					int64validator.Between(20, 1400),
				},
			},
			"num_path_traces": schema.Int64Attribute{
				Optional: true,
				MarkdownDescription: "Number of path traces executed by the agent. <!-- probed:static --> The SDK's encoding " +
					"drops this type's zero value (omitempty), so configuring false, 0 or \"\" silently becomes " +
					"an omission. <!-- /probed -->",
				Validators: []validator.Int64{
					int64validator.Between(1, 10),
				},
			},
			"path_trace_mode": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "Select `inSession` to perform the path trace within a TCP session. <!-- probed:static --> " +
					"The SDK's encoding drops this type's zero value (omitempty), so configuring false, 0 or \"\" " +
					"silently becomes an omission. <!-- /probed -->",
				Validators: []validator.String{
					stringvalidator.OneOf("classic", "in-session"),
				},
			},
			"port": schema.Int64Attribute{
				Optional: true,
				MarkdownDescription: "Target port. <!-- probed:static --> The SDK's encoding drops this type's zero value " +
					"(omitempty), so configuring false, 0 or \"\" silently becomes an omission. <!-- /probed -->",
				Validators: []validator.Int64{
					int64validator.Between(1, 65535),
				},
			},
			"protocol": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "<!-- probed:static --> The SDK's encoding drops this type's zero value (omitempty), so " +
					"configuring false, 0 or \"\" silently becomes an omission. <!-- /probed -->",
				Validators: []validator.String{
					stringvalidator.OneOf("tcp", "udp"),
				},
			},
			"randomized_start_time": schema.BoolAttribute{
				Optional: true,
				MarkdownDescription: "Indicates whether agents should randomize the start time in each test round. <!-- " +
					"probed:static --> The SDK's encoding drops this type's zero value (omitempty), so " +
					"configuring false, 0 or \"\" silently becomes an omission. <!-- /probed -->",
			},
			"saved_event": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: "Indicates if the test is a saved event. **Note**: **Saved Events** are now called " +
					"**Private Snapshots** in the user interface. This change does not affect API.",
			},
			"target_agent_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "`agentId` of the target agent for the test.",
			},
			"id": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: "Each test is assigned an unique ID; this is used to access test information and results " +
					"from other endpoints.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"test_name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "The name of the test. Test name must be unique.",
			},
			"throughput_duration": schema.Int64Attribute{
				Optional:            true,
				MarkdownDescription: "The throughput duration.",
				Validators: []validator.Int64{
					int64validator.Between(5000, 30000),
				},
			},
			"throughput_measurements": schema.BoolAttribute{
				Optional: true,
				MarkdownDescription: "Enable or disable throughput measurements. Throughput measurements cannot be enabled when " +
					"the source or target of the test is a cloud agent.",
			},
			"throughput_rate": schema.Int64Attribute{
				Optional:            true,
				MarkdownDescription: "The throughput rate, only applicable for UDP protocol.",
				Validators: []validator.Int64{
					int64validator.Between(8, 1000),
				},
			},
			"type": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "This is a read only value, as test type is implicit in the test creation url.",
			},
			"use_public_bgp": schema.BoolAttribute{
				Optional: true,
				MarkdownDescription: "Indicate if all available public BGP monitors should be used, when omitted defaults to " +
					"`bgpMeasurements` value. <!-- probed:static --> The SDK's encoding drops this type's zero " +
					"value (omitempty), so configuring false, 0 or \"\" silently becomes an omission. <!-- " +
					"/probed -->",
			},
			"agents": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"agent_id": schema.StringAttribute{
							Required: true,
							MarkdownDescription: "The agent to run the test from. Get identifiers from `/agents`; cloud agent identifiers " +
								"are stable public values.",
						},
					},
				},
				Required: true,
				MarkdownDescription: "The agents the test runs from. Sent on create and update; the read reports assignment " +
					"through its own fields, so this does not round-trip into state.",
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": commonschema.ResourceTimeouts(ctx),
		},
	}
}
