// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:17ccadd9f04833a0c47aa480004eff43ce664c1e4202c4da5c92d766e70cb2c7). DO NOT EDIT.

package tests_api

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/client"
	sdk "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk"
	commonschema "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/schema"
)

const (
	// TypeName is the Terraform type this resource registers as.
	TypeName = "thousandeyes_tests_api"

	// Default per-operation timeouts, in seconds. A practitioner overrides them
	// with the resource's timeouts block.
	CreateTimeout = 180
	ReadTimeout   = 180
	UpdateTimeout = 180
	DeleteTimeout = 180
)

// Compile-time assertions that this resource implements what it claims to. They
// turn a missing method into a build failure rather than a runtime surprise.
var (
	_ resource.Resource                = (*TestsAPIResource)(nil)
	_ resource.ResourceWithConfigure   = (*TestsAPIResource)(nil)
	_ resource.ResourceWithImportState = (*TestsAPIResource)(nil)
)

// NewTestsAPIResource returns the thousandeyes_tests_api resource.
func NewTestsAPIResource() resource.Resource {
	return &TestsAPIResource{}
}

// TestsAPIResource implements the thousandeyes_tests_api resource.
type TestsAPIResource struct {
	client *sdk.ThousandEyesClient
}

// Metadata returns the resource type name.
func (r *TestsAPIResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TypeName
}

// Configure receives the configured SDK client from the provider.
func (r *TestsAPIResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = client.ForResource(ctx, req, resp, TypeName)
}

// ImportState maps a terraform import into state.
func (r *TestsAPIResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// Schema returns the resource schema.
func (r *TestsAPIResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Get API test.",
		Attributes: map[string]schema.Attribute{
			"alerts_enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Indicates if alerts are enabled. <!-- probed:7.0.98-t1785744867250 --> Observed: the API " +
					"assigns true when this is omitted. <!-- /probed -->",
			},
			"bgp_measurements": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Set to `true` to enable bgp measurements. <!-- probed:7.0.98-t1785744867250 --> Observed: " +
					"the API assigns true when this is omitted. <!-- /probed -->",
			},
			"client_cert_domains_allow_list": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Comma separated list of domains to send the client certificate.",
			},
			"client_certificate": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "String representation (containing newline characters) of client certificate, the private " +
					"key must be placed first, then the certificate.",
			},
			"collect_proxy_network_data": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Indicates whether network data to the proxy should be collected. <!-- " +
					"probed:7.0.98-t1785744867250 --> Observed: the API assigns false when this is omitted. " +
					"<!-- /probed -->",
			},
			"created_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "User that created the test.",
			},
			"created_date": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC created date (ISO date-time format).",
			},
			"credentials": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				MarkdownDescription: "Contains a list of credential IDs (get `credentialId` from `/credentials` endpoint).",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "A description of the test.",
			},
			"distributed_tracing": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Adds distributed tracing headers to API requests using B3 and W3C standards. <!-- " +
					"probed:7.0.98-t1785758194545 --> Observed: the API assigns false when this is omitted from " +
					"an update. Omitting this field from an update resets it rather than preserving the stored " +
					"value. <!-- /probed -->",
			},
			"enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Test is enabled. <!-- probed:7.0.98-t1785744867250 --> Observed: the API assigns true when " +
					"this is omitted. <!-- /probed -->",
			},
			"follow_redirects": schema.BoolAttribute{
				Optional: true,
				MarkdownDescription: "To disable following HTTP/301 or HTTP/302 redirect directives, set this parameter to " +
					"`false`. <!-- probed:7.0.98-t1785758194545 --> Neither the update response nor a read " +
					"returns this field: it is write-only in practice, and state carries the configured value. " +
					"<!-- /probed -->",
			},
			"id": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: "Each test is assigned an unique ID; this is used to access test information and results " +
					"from other endpoints. Named `id` per the import convention; the wire field stays testId.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"interval": schema.Int64Attribute{
				Optional: true,
				MarkdownDescription: "Interval between test runs in seconds. <!-- probed:7.0.98-t1785744867250 --> The API " +
					"enforces this field's presence, which the specification does not declare. <!-- /probed -->",
			},
			"labels": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"is_builtin": schema.BoolAttribute{
							Computed: true,
							MarkdownDescription: "Value indicating if the label in question is BuiltIn (Account Admin, Organization Admin, " +
								"Regular User).",
						},
						"label_id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Label ID.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Name of the label.",
						},
					},
				},
				Computed:            true,
				MarkdownDescription: "Labels to which the test is assigned. This field is not returned for Instant Tests.",
			},
			"live_share": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Indicates if the test is shared with the account group.",
			},
			"modified_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "User that modified the test.",
			},
			"modified_date": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC last modification date (ISO date-time format).",
			},
			"monitors": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"country_id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Country ID",
						},
						"ip_address": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "IP address of the BGP monitor",
						},
						"monitor_id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "BGP monitor ID",
						},
						"monitor_name": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Display name of the BGP monitor",
						},
						"monitor_type": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Type of monitor",
						},
						"network": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Name of the autonomous system in which the monitor is found",
						},
					},
				},
				Computed:            true,
				MarkdownDescription: "Contains list of enabled BGP monitors.",
			},
			"mtu_measurements": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Set `true` to measure MTU sizes on network from agents to the target. <!-- " +
					"probed:7.0.98-t1785744867250 --> Observed: the API assigns true when this is omitted. <!-- " +
					"/probed -->",
			},
			"network_measurements": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Enable or disable network measurements. Set to true to enable or false to disable network " +
					"measurements. <!-- probed:7.0.98-t1785744867250 --> Observed: the API assigns true when " +
					"this is omitted. <!-- /probed -->",
			},
			"num_path_traces": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Number of path traces executed by the agent. <!-- probed:7.0.98-t1785758194545 --> " +
					"Conditionally, when networkMeasurements is \"false\": round-trips alone, and is stored as " +
					"null the moment \"networkMeasurements\" rides along; isolated by bisecting the maximal " +
					"body's delta. Not applied to the schema, because this holds only under that condition and " +
					"the schema has no way to say so. Neither the update response nor a read returns this " +
					"field: it is write-only in practice, and state carries the configured value. <!-- /probed " +
					"-->",
				Validators: []validator.Int64{
					int64validator.Between(1, 10),
				},
			},
			"override_agent_proxy": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Flag indicating if a proxy other than the default should be used. To override the default " +
					"proxy for agents, set to `true` and specify a value for `overrideProxyId`. <!-- " +
					"probed:7.0.98-t1785744867250 --> Observed: the API assigns false when this is omitted. " +
					"<!-- /probed -->",
			},
			"override_proxy_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "ID of the proxy to be used if the default proxy is overridden.",
			},
			"path_trace_mode": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Select `inSession` to perform the path trace within a TCP session.",
				Validators: []validator.String{
					stringvalidator.OneOf("classic", "in-session"),
				},
			},
			"predefined_variables": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "Variable name. Must be unique.",
						},
						"value": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "Variable value, will be treated as string.",
						},
					},
				},
				Optional: true,
			},
			"probe_mode": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Probe mode used by network test, only valid when the protocol is set to TCP.",
				Validators: []validator.String{
					stringvalidator.OneOf("auto", "sack", "syn"),
				},
			},
			"protocol": schema.StringAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Protocol used by dependent network tests (end-to-end, path trace, PMTUD). <!-- " +
					"probed:7.0.98-t1785744867250 --> Values accepted here: `tcp`, `icmp`. The specification " +
					"documents `udp`, which the API rejected. Observed: the API assigns \"tcp\" when this is " +
					"omitted. <!-- /probed -->",
				// The API refused "udp" from the documented set when probed. Still permitted here: a value one
				// tenant rejects may be licence-gated rather than nonexistent.
				Validators: []validator.String{
					stringvalidator.OneOf("tcp", "icmp", "udp"),
				},
			},
			"randomized_start_time": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Indicates whether agents should randomize the start time in each test round. <!-- " +
					"probed:7.0.98-t1785744867250 --> Observed: the API assigns false when this is omitted. " +
					"<!-- /probed -->",
			},
			"requests": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"assertions": schema.SetNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"name": schema.StringAttribute{
										Optional: true,
										MarkdownDescription: "Set to `status-code` to assert the response status code. Set to `response-body` to assert " +
											"data is present in the response body. Use `ApiRequestAssertion` to set the value for the " +
											"assertion. <!-- probed:7.0.98-t1785744867250 --> Values accepted here: `status-code`, " +
											"`response-body`. The API accepted a value from outside the documented set, so no OneOf " +
											"validator is generated for this attribute. <!-- /probed -->",
									},
									"operator": schema.StringAttribute{
										Optional: true,
										MarkdownDescription: "If `name = status-code``, accepted values are [is, is-not]. If `name = response-body``, " +
											"accepted values are [includes, not-includes, matches, not-matches]`. <!-- " +
											"probed:7.0.98-t1785744867250 --> Values accepted here: `is`, `is-not`, `includes`, " +
											"`not-includes`, `matches`, `not-matches`. The API accepted a value from outside the " +
											"documented set, so no OneOf validator is generated for this attribute. <!-- /probed -->",
									},
									"value": schema.StringAttribute{
										Optional: true,
										MarkdownDescription: "The value of the assertion. If name = `status-code`, the status code to assert. If name = " +
											"`response-body`, the lookup value to assert.",
									},
								},
							},
							Optional:            true,
							MarkdownDescription: "List of assertion objects.",
						},
						"auth_type": schema.StringAttribute{
							Optional: true,
							Computed: true,
							MarkdownDescription: "Will override the Authorization request header. <!-- probed:7.0.98-t1785744867250 --> " +
								"Values accepted here: `none`, `basic`, `bearer-token`, `oauth2`. Observed: the API assigns " +
								"\"none\" when this is omitted. The API accepted a value from outside the documented set, so " +
								"no OneOf validator is generated for this attribute. <!-- /probed -->",
						},
						"bearer_token": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "The bearer token if `authType = bearer-token`.",
						},
						"body": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "POST/PUT request body. Must be in JSON format.",
						},
						"client_authentication": schema.StringAttribute{
							Optional: true,
							MarkdownDescription: "The OAuth2 client authentication location type. <!-- probed:7.0.98-t1785744867250 --> " +
								"Values accepted here: `basic-auth-header`, `in-body`. The API accepted a value from " +
								"outside the documented set, so no OneOf validator is generated for this attribute. <!-- " +
								"/probed -->",
						},
						"client_id": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "The application ID used when `authType` is set to \"oauth2\".",
						},
						"client_secret": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "The private client secret used when `authType` is set to \"oauth2\".",
						},
						"collect_api_response": schema.BoolAttribute{
							Optional: true,
							Computed: true,
							MarkdownDescription: "Set to `true` if API response body should be collected and saved. Set to `false` if API " +
								"response body should not be saved. <!-- probed:7.0.98-t1785744867250 --> Observed: the API " +
								"assigns false when this is omitted. <!-- /probed -->",
						},
						"headers": schema.SetNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"key": schema.StringAttribute{
										Optional:            true,
										MarkdownDescription: "Request header key.",
									},
									"value": schema.StringAttribute{
										Optional:            true,
										MarkdownDescription: "Request header value. Supports variables `{{variableName}}`.",
									},
								},
							},
							Optional:            true,
							MarkdownDescription: "Array of API Request Header objects.",
						},
						"method": schema.StringAttribute{
							Optional: true,
							Computed: true,
							MarkdownDescription: "HTTP request method. <!-- probed:7.0.98-t1785744867250 --> Values accepted here: `get`, " +
								"`post`, `put`, `delete`, `patch`. Observed: the API assigns \"get\" when this is omitted. " +
								"The API accepted a value from outside the documented set, so no OneOf validator is " +
								"generated for this attribute. <!-- /probed -->",
						},
						"name": schema.StringAttribute{
							Required: true,
							MarkdownDescription: "API step name, must be unique. <!-- probed:7.0.98-t1785744867250 --> Observed: the API " +
								"assigns \"step-1\" when this is omitted. <!-- /probed -->",
						},
						"password": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "The password if `authType = basic`.",
						},
						"scope": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "Application-specific scope values for the access token when `authType` is \"oauth2\".",
						},
						"token_url": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "The endpoint used to request the access token when `authType` is \"oauth2\".",
						},
						"url": schema.StringAttribute{
							Required: true,
							MarkdownDescription: "Request url. Supports variables in the format `{{variableName}}`. <!-- " +
								"probed:7.0.98-t1785744867250 --> Observed: the API assigns " +
								"\"https://api.stripe.com/healthcheck\" when this is omitted. <!-- /probed -->",
						},
						"username": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "The username if `authType = basic`.",
						},
						"variables": schema.SetNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"name": schema.StringAttribute{
										Optional:            true,
										MarkdownDescription: "Variable name",
									},
									"value": schema.StringAttribute{
										Optional:            true,
										MarkdownDescription: "The JSON path of data within the Response Body to assign to this variable.",
									},
								},
							},
							Optional:            true,
							MarkdownDescription: "Array of API post request variable objects.",
						},
						"verify_certificate": schema.BoolAttribute{
							Optional: true,
							Computed: true,
							MarkdownDescription: "Ignore or acknowledge certificate errors. Set to false to ignore certificate errors. <!-- " +
								"probed:7.0.98-t1785744867250 --> Observed: the API assigns false when this is omitted. " +
								"<!-- /probed -->",
						},
						"wait_time_ms": schema.Int64Attribute{
							Optional:            true,
							MarkdownDescription: "Post request delay before executing the next API requests, in milliseconds.",
						},
					},
				},
				Required: true,
				MarkdownDescription: "<!-- probed:7.0.98-t1785744867250 --> The API enforces this field's presence, which the " +
					"specification does not declare. <!-- /probed -->",
			},
			"saved_event": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: "Indicates if the test is a saved event. **Note**: **Saved Events** are now called " +
					"**Private Snapshots** in the user interface. This change does not affect API.",
			},
			"shared_with_accounts": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"aid": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Account group ID.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Account group name.",
						},
					},
				},
				Computed: true,
				MarkdownDescription: "Contains list of account group IDs. Test is shared with the listed account groups (get " +
					"`aid` from `/account-groups` endpoint)",
			},
			"ssl_version_id": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "SSL version options: * Use '0' for automatic selection. * Use '3' for SSLv3. * Use '4' for " +
					"TLS v1.0. * Use '5' for TLS v1.1. * Use '6' for TLS v1.2. * Use '7' for TLS v1.3. <!-- " +
					"probed:7.0.98-t1785758194545 --> Neither the update response nor a read returns this " +
					"field: it is write-only in practice, and state carries the configured value. <!-- /probed " +
					"-->",
				Validators: []validator.String{
					stringvalidator.OneOf("0", "3", "4", "5", "6", "7"),
				},
			},
			"tags": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Unique tag ID.",
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
							},
						},
						"key": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Tag key. For example, \"Location\" or \"Department\".",
						},
						"value": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Tag value. For example, \"San Francisco\" or \"Engineering\".",
						},
					},
				},
				Computed: true,
				MarkdownDescription: "Tags assigned to the test. Returned only when `expand=tag` is specified. This field is not " +
					"returned for Instant Tests. For more information, see `/tags`.",
			},
			"target_time": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Target time for completion metric, defaults to 50% of time limit specified in seconds. (0 " +
					"means default behavior) <!-- probed:7.0.98-t1785744867250 --> Observed: the API assigns 6 " +
					"when this is omitted. <!-- /probed -->",
				Validators: []validator.Int64{
					int64validator.Between(0, 60),
				},
			},
			"test_name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "The name of the test. Test name must be unique.",
			},
			"time_limit": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Time limit for transaction in seconds. Exceeding this limit will result in a Timeout " +
					"error. <!-- probed:7.0.98-t1785744867250 --> Observed: the API assigns 10 when this is " +
					"omitted. <!-- /probed -->",
				Validators: []validator.Int64{
					int64validator.Between(5, 180),
				},
			},
			"type": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "This is a read only value, as test type is implicit in the test creation url.",
			},
			"url": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "Target for the test. <!-- probed:7.0.98-t1785744867250 --> The API enforces this field's " +
					"presence, which the specification does not declare. <!-- /probed -->",
			},
			"use_public_bgp": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				MarkdownDescription: "Indicate if all available public BGP monitors should be used, when ommited defaults to " +
					"`bgpMeasurements` value. <!-- probed:7.0.98-t1785744867250 --> Observed: the API assigns " +
					"true when this is omitted. <!-- /probed -->",
			},
			"vault_credentials": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"secret_id": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "UUID of the configured secret.",
						},
						"target": schema.StringAttribute{
							Optional: true,
							MarkdownDescription: "The target setting that the credential should be used for. <!-- " +
								"probed:7.0.98-t1785744867250 --> Values accepted here: `username`, `password`, `script`. " +
								"The API accepted a value from outside the documented set, so no OneOf validator is " +
								"generated for this attribute. <!-- /probed -->",
						},
					},
				},
				Optional:            true,
				MarkdownDescription: "List of credential IDs that are stored in an external vault.",
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": commonschema.ResourceTimeouts(ctx),
		},
	}
}
