// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package endpoint

import (
	"context"

	ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3 "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// AgentsConnectionStringRequestBuilder builds and executes requests for operations under \endpoint\agents\connection-string
type AgentsConnectionStringRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// AgentsConnectionStringRequestBuilderGetQueryParameters get agent connection string
type AgentsConnectionStringRequestBuilderGetQueryParameters struct {
	// A unique identifier associated with your account group. You can retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note that you must be assigned to the target account group. Specifying this parameter without being assigned to the target account group will result in an error response.
	Aid *string "uriparametername:\"aid\""
}

// NewAgentsConnectionStringRequestBuilderInternal instantiates a new AgentsConnectionStringRequestBuilder and sets the default values.
func NewAgentsConnectionStringRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *AgentsConnectionStringRequestBuilder {
	m := &AgentsConnectionStringRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/endpoint/agents/connection-string{?aid*}", pathParameters),
	}
	return m
}

// NewAgentsConnectionStringRequestBuilder instantiates a new AgentsConnectionStringRequestBuilder and sets the default values.
func NewAgentsConnectionStringRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *AgentsConnectionStringRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewAgentsConnectionStringRequestBuilderInternal(urlParams, requestAdapter)
}

// Get get agent connection string
// returns a Endpoint_Agents_API_ConnectionStringable when successful
// returns a Endpoint_Agents_API_UnauthorizedError error when the service returns a 401 status code
// returns a Endpoint_Agents_API_Error error when the service returns a 403 status code
// returns a Endpoint_Agents_API_Error error when the service returns a 429 status code
func (m *AgentsConnectionStringRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[AgentsConnectionStringRequestBuilderGetQueryParameters]) (ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Endpoint_Agents_API_ConnectionStringable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"401": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEndpoint_Agents_API_UnauthorizedErrorFromDiscriminatorValue,
		"403": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEndpoint_Agents_API_ErrorFromDiscriminatorValue,
		"429": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEndpoint_Agents_API_ErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEndpoint_Agents_API_ConnectionStringFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Endpoint_Agents_API_ConnectionStringable), nil
}

// ToGetRequestInformation get agent connection string
// returns a *RequestInformation when successful
func (m *AgentsConnectionStringRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[AgentsConnectionStringRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/hal+json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *AgentsConnectionStringRequestBuilder when successful
func (m *AgentsConnectionStringRequestBuilder) WithUrl(rawUrl string) *AgentsConnectionStringRequestBuilder {
	return NewAgentsConnectionStringRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
