// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package endpoint

import (
	"context"

	ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3 "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// AgentsItemEnableRequestBuilder builds and executes requests for operations under \endpoint\agents\{agentId}\enable
type AgentsItemEnableRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// AgentsItemEnableRequestBuilderPostQueryParameters enables an endpoint agent. If it's already enabled, it has no effect (no operation).
type AgentsItemEnableRequestBuilderPostQueryParameters struct {
	// A unique identifier associated with your account group. You can retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note that you must be assigned to the target account group. Specifying this parameter without being assigned to the target account group will result in an error response.
	Aid *string "uriparametername:\"aid\""
}

// NewAgentsItemEnableRequestBuilderInternal instantiates a new AgentsItemEnableRequestBuilder and sets the default values.
func NewAgentsItemEnableRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *AgentsItemEnableRequestBuilder {
	m := &AgentsItemEnableRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/endpoint/agents/{agentId}/enable{?aid*}", pathParameters),
	}
	return m
}

// NewAgentsItemEnableRequestBuilder instantiates a new AgentsItemEnableRequestBuilder and sets the default values.
func NewAgentsItemEnableRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *AgentsItemEnableRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewAgentsItemEnableRequestBuilderInternal(urlParams, requestAdapter)
}

// Post enables an endpoint agent. If it's already enabled, it has no effect (no operation).
// returns a Endpoint_Agents_API_EndpointAgentable when successful
// returns a Endpoint_Agents_API_UnauthorizedError error when the service returns a 401 status code
// returns a Endpoint_Agents_API_Error error when the service returns a 403 status code
// returns a Endpoint_Agents_API_Error error when the service returns a 404 status code
// returns a Endpoint_Agents_API_Error error when the service returns a 429 status code
func (m *AgentsItemEnableRequestBuilder) Post(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[AgentsItemEnableRequestBuilderPostQueryParameters]) (ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Endpoint_Agents_API_EndpointAgentable, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"401": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEndpoint_Agents_API_UnauthorizedErrorFromDiscriminatorValue,
		"403": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEndpoint_Agents_API_ErrorFromDiscriminatorValue,
		"404": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEndpoint_Agents_API_ErrorFromDiscriminatorValue,
		"429": ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEndpoint_Agents_API_ErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.CreateEndpoint_Agents_API_EndpointAgentFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(ibe12bd88d9fd0b0649f512e0a68362a5e14fb418f868063d753631b46b3d2dd3.Endpoint_Agents_API_EndpointAgentable), nil
}

// ToPostRequestInformation enables an endpoint agent. If it's already enabled, it has no effect (no operation).
// returns a *RequestInformation when successful
func (m *AgentsItemEnableRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[AgentsItemEnableRequestBuilderPostQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/hal+json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *AgentsItemEnableRequestBuilder when successful
func (m *AgentsItemEnableRequestBuilder) WithUrl(rawUrl string) *AgentsItemEnableRequestBuilder {
	return NewAgentsItemEnableRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
