// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:5784e03978dc4aa1168b63f15b5200e4d2c21e162af10c9c1d3532b5a6e56762). DO NOT EDIT.

package tags

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *TagsDataSourceModel, remote models.Tags_API_Tagsable) diag.Diagnostics {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)

	if remote == nil {
		tflog.Debug(ctx, "remote object is nil, leaving state untouched", map[string]any{
			"dataSource": TypeName,
		})
		return diags
	}

	data.Tags, d = flattenTagSummaries(ctx, remote.GetTags())
	diags.Append(d...)

	tflog.Debug(ctx, "mapped remote state", map[string]any{"dataSource": TypeName})

	return diags
}

// flattenTagSummaries converts SDK structs into the framework value state holds.
func flattenTagSummaries(ctx context.Context, in []models.Tags_API_Tagable) (types.List, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	// A nil slice is null and an empty slice is empty. Conflating them produces a
	// diff no configuration change can resolve.
	if in == nil {
		return types.ListNull(tagSummaryObjectType), diags
	}

	elements := make([]TagSummaryModel, 0, len(in))
	for _, item := range in {
		var m TagSummaryModel

		m.ID = convert.PtrStringerToFramework(item.GetId())
		m.Key = convert.PtrStringToFramework(item.GetKey())
		m.Value = convert.PtrStringToFramework(item.GetValue())
		m.Color = convert.PtrStringToFramework(item.GetColor())
		m.Description = convert.PtrStringToFramework(item.GetDescription())
		m.Icon = convert.PtrStringToFramework(item.GetIcon())
		m.ObjectType = convert.PtrStringerToFramework(item.GetObjectType())
		m.AccessType = convert.PtrStringerToFramework(item.GetAccessType())
		m.MatchType = convert.PtrStringerToFramework(item.GetMatchType())
		m.Type = convert.PtrStringerToFramework(item.GetTypeEscaped())
		m.BuiltIn = convert.PtrBoolToFramework(item.GetBuiltIn())
		m.AccountGroupID = convert.PtrInt64ToFramework(item.GetAid())
		m.CreateDate = convert.PtrStringToFramework(item.GetCreateDate())
		m.ModifiedDate = convert.PtrTimeToFramework(item.GetModifiedDate())
		m.LegacyID = convert.PtrFloat64ToFramework(item.GetLegacyId())
		m.Assignments, d = flattenTagSummaryAssignments(ctx, item.GetAssignments())
		diags.Append(d...)
		m.Filters, d = flattenTagSummaryFilters(ctx, item.GetFilters())
		diags.Append(d...)
		elements = append(elements, m)
	}

	out, d2 := types.ListValueFrom(ctx, tagSummaryObjectType, elements)
	diags.Append(d2...)

	return out, diags
}

// flattenTagSummaryAssignments converts SDK structs into the framework value state holds.
func flattenTagSummaryAssignments(ctx context.Context, in []models.Tags_API_Assignmentable) (types.Set, diag.Diagnostics) {
	var diags diag.Diagnostics

	// A nil slice is null and an empty slice is empty. Conflating them produces a
	// diff no configuration change can resolve.
	if in == nil {
		return types.SetNull(tagSummaryAssignmentObjectType), diags
	}

	elements := make([]TagSummaryAssignmentModel, 0, len(in))
	for _, item := range in {
		var m TagSummaryAssignmentModel

		m.ID = convert.PtrStringToFramework(item.GetId())
		m.Type = convert.PtrStringerToFramework(item.GetTypeEscaped())
		elements = append(elements, m)
	}

	out, d2 := types.SetValueFrom(ctx, tagSummaryAssignmentObjectType, elements)
	diags.Append(d2...)

	return out, diags
}

// flattenTagSummaryFilters converts SDK structs into the framework value state holds.
func flattenTagSummaryFilters(ctx context.Context, in []models.Tags_API_TagFilterable) (types.Set, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	// A nil slice is null and an empty slice is empty. Conflating them produces a
	// diff no configuration change can resolve.
	if in == nil {
		return types.SetNull(tagSummaryFilterObjectType), diags
	}

	elements := make([]TagSummaryFilterModel, 0, len(in))
	for _, item := range in {
		var m TagSummaryFilterModel

		m.Key = convert.PtrStringToFramework(item.GetKey())
		m.Mode = convert.PtrStringerToFramework(item.GetMode())
		m.Scope = convert.PtrStringerToFramework(item.GetScope())
		m.Values, d = convert.StringSliceToFrameworkSet(ctx, item.GetValues())
		diags.Append(d...)
		elements = append(elements, m)
	}

	out, d2 := types.SetValueFrom(ctx, tagSummaryFilterObjectType, elements)
	diags.Append(d2...)

	return out, diags
}
