# Code generated by tfpfgen from blueprints/thousandeyes
# (sha256:a77202f0cc7a39428530f850d05261677e790870fef8f388f4f138a1398994df). DO NOT EDIT.

# The smallest configuration this resource accepts: its required attributes and nothing else.
#
# Regenerated, so it follows the schema. If the API starts requiring a field, this file gains it
# on the next emit rather than an acceptance run discovering it.

resource "thousandeyes_alerts_rule" "test" {
  # Where a value came from. A fixture takes what the API was observed to accept, not the first
  # value the specification documents -- which is the opposite of how a generated validator is
  # built. A validator errs toward permitting, because blocking a configuration the API would
  # have taken is a harm nobody can work around; a fixture errs toward working, because it is an
  # input rather than a contract.
  #
  # alert_type: documented; unprobed
  alert_type              = "page-load"
  expression              = "tfacc-expression"
  rounds_violating_out_of = 1
  rule_name               = "tfacc-rule-name"
}
