// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:0705a06d171a00d2bf9756d028fa63d1589968e3dae11ee9272c1c4039c2d00f). DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"

	v7TagData "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/datasources/tags/v7/tag"
	v7TagsData "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/datasources/tags/v7/tags"
)

// DataSources returns every data source this provider serves.
//
// This file is generated in full. Add a data source by adding a blueprint and
// regenerating, not by editing here.
func (p *Provider) DataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		v7TagData.NewTagDataSource,
		v7TagsData.NewTagsDataSource,
	}
}
