// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:0705a06d171a00d2bf9756d028fa63d1589968e3dae11ee9272c1c4039c2d00f). DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/list"

	v7Tag "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/resources/tags/v7/tag"
)

// ListResources returns every list resource this provider serves.
//
// Declaring this method is what makes the provider satisfy
// provider.ProviderWithListResources, so a resource gaining a list facet needs no
// hand-written change here -- which is the point of generating the file whole.
//
// This file is generated in full. Add a list resource by giving a resource a list facet in
// its blueprint and regenerating, not by editing here.
func (p *Provider) ListResources(_ context.Context) []func() list.ListResource {
	return []func() list.ListResource{
		v7Tag.NewTagListResource,
	}
}
