// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:d986d7900b3714639519883166d0066510af34e4e4431384031a6f7b9dc0895a). DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/list"
)

// ListResources returns every list resource this provider serves.
//
// Declaring this method is what makes the provider satisfy
// provider.ProviderWithListResources, so a resource gaining a list facet needs no
// hand-written change here -- which is the point of generating the file whole.
//
// This file is generated in full. Add a list resource by giving a resource a list facet in
// its blueprint and regenerating, not by editing here.
func (p *Provider) ListResources(_ context.Context) []func() list.ListResource {
	return []func() list.ListResource{}
}
