// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:17ccadd9f04833a0c47aa480004eff43ce664c1e4202c4da5c92d766e70cb2c7). DO NOT EDIT.

package connectors_panorama

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/convert"
)

// constructResource maps Terraform configuration onto the API's request body.
//
// Only writable attributes appear here. A computed attribute has no expand
// conversion, so it cannot be sent by construction rather than by discipline.
func constructResource(ctx context.Context, data *ConnectorsPanoramaResourceModel) (*models.Integrations_API_PanoramaConnector, diag.Diagnostics) {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)
	tflog.Debug(ctx, "constructing request body", map[string]any{"resource": TypeName})

	body := models.NewIntegrations_API_PanoramaConnector()

	body.SetName(convert.FrameworkToPtrString(data.Name))
	body.SetTarget(convert.FrameworkToPtrString(data.Target))
	typeRaw, d := convert.FrameworkToKiotaEnum[models.Integrations_API_PanoramaConnector_type](data.Type, models.ParseIntegrations_API_PanoramaConnector_type)
	diags.Append(d...)
	body.SetTypeEscaped(typeRaw)

	return body, diags
}
