// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:17ccadd9f04833a0c47aa480004eff43ce664c1e4202c4da5c92d766e70cb2c7). DO NOT EDIT.

package credential

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/client"
	sdk "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk"
	commonschema "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/schema"
)

const (
	// TypeName is the Terraform type this data source registers as.
	TypeName = "thousandeyes_credential"

	// ReadTimeout is the default read deadline in seconds. A practitioner overrides it
	// with the data source's timeouts block. Read is the only operation a data source
	// has, so it is the only deadline there is.
	ReadTimeout = 180
)

// Compile-time assertions that this data source implements what it claims to. They
// turn a missing method into a build failure rather than a runtime surprise.
var (
	_ datasource.DataSource              = &CredentialDataSource{}
	_ datasource.DataSourceWithConfigure = &CredentialDataSource{}
)

// NewCredentialDataSource returns the thousandeyes_credential data source.
func NewCredentialDataSource() datasource.DataSource {
	return &CredentialDataSource{}
}

// CredentialDataSource implements the thousandeyes_credential data source.
type CredentialDataSource struct {
	client *sdk.ThousandEyesClient
}

// Metadata returns the data source type name.
func (d *CredentialDataSource) Metadata(_ context.Context, _ datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = TypeName
}

// Configure receives the configured SDK client from the provider.
func (d *CredentialDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = client.ForDataSource(ctx, req, resp, TypeName)
}

// Schema returns the data source schema.
func (d *CredentialDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieve credential.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Unique ID of the credential.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "The name of the credential.",
			},
			"value": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The value of the credential that will be encrypted.",
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": commonschema.DataSourceTimeouts(ctx),
		},
	}
}
