// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:d986d7900b3714639519883166d0066510af34e4e4431384031a6f7b9dc0895a). DO NOT EDIT.

package agents_proxy

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-provider-thousandeyes/internal/sdk/models"
	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/crud"
	"github.com/deploymenttheory/terraform-provider-thousandeyes/internal/services/common/errors"
)

// Read fetches thousandeyes_agents_proxy from the API.
//
// A data source reads its arguments from configuration rather than from prior state:
// there is no prior state to read, because nothing here was created by Terraform.
func (d *AgentsProxyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data AgentsProxyDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "reading data source", map[string]any{"dataSource": TypeName})

	ctx, cancel := crud.HandleTimeout(ctx, data.Timeouts.Read, ReadTimeout*time.Second, &resp.Diagnostics)
	if cancel == nil {
		return
	}
	defer cancel()

	// A lookup must be predictable: exactly one selector chooses the object,
	// and the resolver below refuses zero matches and several matches alike.
	selectorsSet := 0
	if !data.Name.IsNull() {
		selectorsSet++
	}
	if selectorsSet != 1 {
		resp.Diagnostics.AddError(
			"Exactly one selector is required",
			"Set exactly one of: name.",
		)
		return
	}

	listing, err := d.client.Agents().Proxies().Get(ctx, nil)
	if err != nil {
		errors.Handle(&resp.Diagnostics, TypeName, errors.OpRead, err)
		return
	}
	if listing == nil {
		errors.Handle(&resp.Diagnostics, TypeName, errors.OpRead, errors.ErrEmptyResponse)
		return
	}
	var matches []models.Agents_API_AgentProxyable
	for _, el := range listing.GetAgentProxies() {
		if !data.Name.IsNull() && (el.GetName() == nil || *el.GetName() != data.Name.ValueString()) {
			continue
		}
		matches = append(matches, el)
	}
	switch len(matches) {
	case 1:
	case 0:
		resp.Diagnostics.AddError(
			"No match",
			"The configured selector matched nothing. The object may not exist, or may be invisible to this account group.",
		)
		return
	default:
		resp.Diagnostics.AddError(
			"Ambiguous match",
			fmt.Sprintf("The configured selector matched %d objects; a lookup must resolve to exactly one. Narrow the selector.", len(matches)),
		)
		return
	}
	resp.Diagnostics.Append(mapRemoteStateToTerraform(ctx, &data, matches[0])...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	return
}
